"""
Writes src/data/solar-history.ts (roadmap R05): the monthly means of the
observed 10.7 cm solar radio flux and of the daily planetary Ap, from GFZ's
file of the indices since 1932 (README.md here says where and when it was
fetched, and its licence).

A month is kept when at least ten of its days have a flux; the flux is the
mean of those days' F10.7obs (GFZ: "for ionospheric and atmospheric studies
the use of F10.7obs is recommended"), the Ap the mean of all its days' Ap.
The last month kept is the last complete one in the file.

    python3 make_solar_history.py Kp_ap_Ap_SN_F107_since_1932.txt > ../../../src/data/solar-history.ts
"""
import sys

rows = {}
last_day = None
for line in open(sys.argv[1]):
    if line.startswith('#'):
        continue
    p = line.split()
    y, m, d = int(p[0]), int(p[1]), int(p[2])
    ap, f107 = int(p[23]), float(p[25])
    rows.setdefault((y, m), []).append((ap, f107))
    last_day = (y, m, d)

# the last complete month: the file's last day must be that month's last
months = sorted(rows)
y, m, d = last_day
days_in = [31, 29 if (y % 4 == 0 and (y % 100 != 0 or y % 400 == 0)) else 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][m - 1]
if d < days_in:
    months = months[:-1]

first = None
f107, ap = [], []
for key in months:
    days = rows[key]
    fluxes = [f for _, f in days if f > 0]
    aps = [a for a, _ in days if a >= 0]
    if first is None:
        if len(fluxes) < 10:
            continue
        first = key
    if len(fluxes) < 10 or len(aps) < len(days):
        sys.exit(f'{key}: only {len(fluxes)} days of flux, {len(aps)} of {len(days)} of Ap')
    f107.append(round(sum(fluxes) / len(fluxes), 1))
    ap.append(round(sum(aps) / len(aps), 1))

end = months[-1]


def fmt(values):
    out, line = [], '    '
    for v in values:
        s = f'{v:g}, '
        if len(line) + len(s) > 118:
            out.append(line.rstrip())
            line = '    '
        line += s
    out.append(line.rstrip())
    return '\n'.join(out)


print(f'''/**
 * The Sun and the geomagnetic field month by month (roadmap R05), for the
 * lifetime model's measured indices: the monthly mean of the observed 10.7 cm
 * solar radio flux F10.7 (solar flux units, 10⁻²² W m⁻² Hz⁻¹) and of the
 * daily planetary Ap, from {first[0]}-{first[1]:02d} to {end[0]}-{end[1]:02d}.
 *
 * Source: GFZ Helmholtz Centre for Geosciences, "Kp_ap_Ap_SN_F107_since_1932.txt",
 * CC BY 4.0 — Matzka, J., Bronkalla, O., Tornow, K., Elger, K. and Stolle, C.
 * (2021), Geomagnetic Kp index, V. 1.0, GFZ Data Services,
 * https://doi.org/10.5880/Kp.0001; the flux is the Dominion Radio
 * Astrophysical Observatory's (Natural Resources Canada; Tapping 2013,
 * https://doi.org/10.1002/swe.20064). A past month does not change, so the
 * table is fixed; the months after it come from NOAA SWPC through the
 * space-weather dataset.
 *
 * Generated by tests/fixtures/space-weather/make_solar_history.py — do not edit.
 */
export const SOLAR_HISTORY = {{
  /** the first month, YYYY-MM */
  from: '{first[0]}-{first[1]:02d}',
  /** monthly mean F10.7 (observed, not adjusted to 1 AU), sfu */
  f107: [
{fmt(f107)}
  ],
  /** monthly mean of the daily Ap */
  ap: [
{fmt(ap)}
  ],
}} as const;''')
