import { getLang, type Lang } from '../../i18n';
import { PROFILE_CONTEXT_TEXT } from './context-text';

/** Full profile and backup vocabulary loads with the on-demand menu. */
export const PROFILE_TEXT = {
  en: { ...PROFILE_CONTEXT_TEXT.en,
    "local": "Profiles are stored on this device. They separate your work; they are not online accounts or a sign-in.",
    "empty": "No learner profiles yet.",
    "name": "Learner name",
    "create": "Create a profile",
    "rename": "Rename",
    "switch": "Open this workspace",
    "current": "Current",
    "delete": "Delete profile",
    "cancel": "Cancel",
    "back": "Back",
    "save": "Save name",
    "confirm": "Confirm",
    "backup": "Export a backup first",
    "backupDone": "Backup exported. Keep the downloaded file before continuing.",
    "backupPartial": "Backup exported with the readable profiles. Profiles that cannot be read were not included; save a copy of each from the profile list.",
    "unreadableName": "Unreadable profile",
    "rowUnreadable": "This version of the app cannot read this profile. Its stored data is kept unchanged on this device. Save a copy, or delete it if you no longer need it.",
    "rowNewer": "This profile was made by a newer version of the app. Its stored data is kept unchanged on this device. Open it with the newer version, save a copy, or delete it if you no longer need it.",
    "rowMissing": "The stored data of this profile is no longer on this device. Only its entry in the list remains; you can delete the entry.",
    "backupNoneReadable": "No profile could be read, so no backup file was made. Save a copy of each profile from the profile list.",
    "rowAction": "{action}: {name}",
    "mediaUnavailable": "Audio can be exported after the page is reloaded with durable storage.",
    "exportRaw": "Save a copy of the stored data",
    "deleteUnreadableTitle": "Delete the unreadable profile “{name}”?",
    "deleteUnreadableLead": "This permanently removes this profile’s stored data and uploaded audio from this device. This app cannot show what it contains. Save a copy first if you might need it, for example with a newer version of the app.",
    "deleteUnreadableConfirm": "Delete this profile’s stored data",
    "createLead": "Each learner has separate lessons, tests, designs, missions and notes.",
    "transition": "The page will reload to open the selected workspace. Saved work stays with its learner. A live flight or a test screen will close; a saved test can be continued later. Live flights are not restored by profile switching.",
    "switchTitle": "Open the workspace for {name}?",
    "createTitle": "Create a workspace for {name}?",
    "deleteTitle": "Delete the profile “{name}”?",
    "deleteLead": "This removes this learner’s saved work, personal settings and uploaded audio from this device. Other learners are kept. Export a backup if you want to keep a copy.",
    "deleteActive": "This is the current learner. After deletion, choose or create a learner explicitly.",
    "deleteConfirm": "Delete this learner and their work",
    "resetTitle": "Reset records for {name}",
    "resetLead": "Choose the records to remove. Designs, missions, notes and your imported or authored lessons and questions are kept.",
    "scope": "Records to remove",
    "learning": "All learning history",
    "exams": "All tests, including unfinished tests",
    "all": "Learning history and tests",
    "lesson": "One lesson’s learning history",
    "chooseLesson": "Lesson",
    "noLessons": "No recorded lessons to reset.",
    "resetConfirm": "Delete these records",
    "resetEffects": "Selected history, attempts, saved grades, hints and revealed answers will be removed. The page will reload so an old open session cannot put the deleted records back.",
    "countsTitle": "Saved records in this scope",
    "lessons": "Lessons with history",
    "assessments": "Tests",
    "designs": "Saved designs",
    "experiments": "Experiment notes",
    "drafts": "Drafts",
    "customLessons": "Personal lessons",
    "customQuestions": "Personal questions",
    "audio": "Uploaded audio",
    "busy": "Saving changes…",
    "error": "Could not complete this change: {reason}",
    "invalidName": "Enter a learner name (up to 80 characters).",
    "reload": "Reload page",
    "status": "Storage status",
    "backups": "Profile backups",
    "exportProfile": "Export this learner’s workspace",
    "exportAll": "Export all learner profiles",
    "jsonMedia": "Workspace JSON files exclude uploaded audio. Export your audio separately if you want it in your backup.",
    "exportMedia": "Export this learner’s uploaded audio",
    "importMedia": "Restore uploaded audio to this learner",
    "importBackup": "Import a workspace backup",
    "importLead": "Review the file and choose its destination before any records are changed.",
    "sourceProfiles": "Profiles in this file",
    "legacy": "Legacy project file: only the sections present in that file can be restored.",
    "destination": "Import destination",
    "newProfile": "Create a new learner",
    "importName": "Name for the new learner",
    "merge": "Existing records",
    "keep": "Keep existing records",
    "replace": "Replace records present in the file",
    "replaceWarning": "Records in the selected learner’s workspace that are present in this file will be replaced. Export a backup before continuing.",
    "multiImport": "Each profile in this file will be imported as a new learner. Existing learners will be kept.",
    "importConfirm": "Import the reviewed file",
    "reading": "Reading backup…",
    "mediaDone": "Uploaded audio restored to this learner.",
    "mediaWarning": "Audio restore belongs to the selected learner. Keep existing audio is the default; Replace overwrites audio with matching mission names. Export the current audio before replacing it.",
    "mediaSource": "Audio from {name}: {count} track(s)",
    "errorStorage": "Browser storage could not save this change. Keep a backup and check available device storage.",
    "errorInvalid": "The file, name or saved records are not valid. Existing work has been kept.",
    "errorNewer": "These records use a newer format than this app can read. Update the app before importing them.",
    "errorStale": "This workspace changed or was closed. Reload before making further changes.",
    "errorMissing": "This learner or backup record is no longer available. Reload and choose a learner.",
    "errorLimit": "The maximum number of learner profiles has been reached. Back up and remove an unused profile first.",
    "errorOversize": "This backup exceeds the supported size limit. No records have been imported.",
    "errorPending": "A previous storage operation needs recovery. Reload before changing these records.",
    "quarantine": "{count} stored value(s) will be preserved as recovery data. Unsupported or invalid content will not be activated.",
  },
  th: { ...PROFILE_CONTEXT_TEXT.th,
    "local": "โปรไฟล์เก็บอยู่ในอุปกรณ์นี้ ใช้แยกงานของแต่ละคน ไม่ใช่บัญชีออนไลน์หรือระบบเข้าสู่ระบบ",
    "empty": "ยังไม่มีโปรไฟล์ผู้เรียน",
    "name": "ชื่อผู้เรียน",
    "create": "สร้างโปรไฟล์",
    "rename": "เปลี่ยนชื่อ",
    "switch": "เปิดพื้นที่ทำงานนี้",
    "current": "กำลังใช้งาน",
    "delete": "ลบโปรไฟล์",
    "cancel": "ยกเลิก",
    "back": "กลับ",
    "save": "บันทึกชื่อ",
    "confirm": "ยืนยัน",
    "backup": "ส่งออกข้อมูลสำรองก่อน",
    "backupDone": "ส่งออกข้อมูลสำรองแล้ว โปรดเก็บไฟล์ที่ดาวน์โหลดก่อนดำเนินการต่อ",
    "backupPartial": "ส่งออกข้อมูลสำรองของโปรไฟล์ที่อ่านได้แล้ว โปรไฟล์ที่อ่านไม่ได้ไม่ได้รวมอยู่ในไฟล์ ให้บันทึกสำเนาของแต่ละโปรไฟล์จากรายการโปรไฟล์",
    "unreadableName": "โปรไฟล์ที่อ่านไม่ได้",
    "rowUnreadable": "แอปรุ่นนี้อ่านโปรไฟล์นี้ไม่ได้ ข้อมูลที่เก็บไว้ยังอยู่ในอุปกรณ์นี้โดยไม่ถูกแก้ไข บันทึกสำเนาไว้ หรือลบออกถ้าไม่ต้องการแล้ว",
    "rowNewer": "โปรไฟล์นี้สร้างโดยแอปรุ่นใหม่กว่า ข้อมูลที่เก็บไว้ยังอยู่ในอุปกรณ์นี้โดยไม่ถูกแก้ไข เปิดด้วยแอปรุ่นใหม่กว่า บันทึกสำเนาไว้ หรือลบออกถ้าไม่ต้องการแล้ว",
    "rowMissing": "ข้อมูลที่เก็บไว้ของโปรไฟล์นี้ไม่อยู่ในอุปกรณ์นี้แล้ว เหลือเพียงชื่อในรายการ ลบรายการนี้ได้",
    "backupNoneReadable": "ไม่มีโปรไฟล์ที่อ่านได้ จึงไม่ได้สร้างไฟล์สำรอง ให้บันทึกสำเนาของแต่ละโปรไฟล์จากรายการโปรไฟล์",
    "rowAction": "{action}: {name}",
    "mediaUnavailable": "ส่งออกเสียงได้หลังโหลดหน้าใหม่ในโหมดที่บันทึกข้อมูลได้",
    "exportRaw": "บันทึกสำเนาข้อมูลที่เก็บไว้",
    "deleteUnreadableTitle": "ลบโปรไฟล์ที่อ่านไม่ได้ “{name}” ใช่ไหม?",
    "deleteUnreadableLead": "การลบจะเอาข้อมูลที่เก็บไว้และเสียงที่อัปโหลดของโปรไฟล์นี้ออกจากอุปกรณ์อย่างถาวร แอปนี้แสดงเนื้อหาข้างในไม่ได้ ให้บันทึกสำเนาไว้ก่อนถ้าอาจต้องใช้ เช่น กับแอปรุ่นใหม่กว่า",
    "deleteUnreadableConfirm": "ลบข้อมูลที่เก็บไว้ของโปรไฟล์นี้",
    "createLead": "ผู้เรียนแต่ละคนมีบทเรียน ผลสอบ แบบยาน ภารกิจ และบันทึกแยกจากกัน",
    "transition": "หน้าเว็บจะโหลดใหม่เพื่อเปิดพื้นที่ทำงานที่เลือก งานที่บันทึกแล้วยังคงอยู่กับผู้เรียนเดิม เที่ยวบินที่กำลังจำลองและหน้าข้อสอบจะปิด ข้อสอบที่บันทึกไว้กลับมาทำต่อได้ การสลับโปรไฟล์ไม่คืนเที่ยวบินที่กำลังจำลอง",
    "switchTitle": "เปิดพื้นที่ทำงานของ {name} ใช่ไหม?",
    "createTitle": "สร้างพื้นที่ทำงานให้ {name} ใช่ไหม?",
    "deleteTitle": "ลบโปรไฟล์ “{name}” ใช่ไหม?",
    "deleteLead": "ลบงานที่บันทึก การตั้งค่าส่วนตัว และเสียงที่อัปโหลดของผู้เรียนคนนี้ออกจากอุปกรณ์ โดยเก็บข้อมูลผู้เรียนคนอื่นไว้ ส่งออกข้อมูลสำรองหากต้องการเก็บสำเนา",
    "deleteActive": "นี่คือผู้เรียนที่กำลังใช้งาน หลังลบจะต้องเลือกหรือสร้างผู้เรียนใหม่ด้วยตนเอง",
    "deleteConfirm": "ลบผู้เรียนและงานของคนนี้",
    "resetTitle": "รีเซ็ตประวัติของ {name}",
    "resetLead": "เลือกข้อมูลที่จะลบ โดยเก็บแบบยาน ภารกิจ สมุดทดลอง และบทเรียนหรือคำถามที่คุณนำเข้าหรือสร้างเองไว้",
    "scope": "ข้อมูลที่จะลบ",
    "learning": "ประวัติการเรียนทั้งหมด",
    "exams": "ผลสอบทั้งหมดรวมข้อสอบที่ยังไม่จบ",
    "all": "ประวัติการเรียนและผลสอบ",
    "lesson": "ประวัติการเรียนรายบท",
    "chooseLesson": "บทเรียน",
    "noLessons": "ยังไม่มีประวัติรายบทที่จะรีเซ็ต",
    "resetConfirm": "ลบประวัติที่เลือก",
    "resetEffects": "ลบประวัติ จำนวนครั้งที่ทำ คะแนน คำใบ้ และคำตอบที่เคยเปิดดูตามขอบเขตที่เลือก จากนั้นหน้าเว็บจะโหลดใหม่เพื่อป้องกันงานที่เปิดค้างบันทึกประวัติที่ลบกลับมา",
    "countsTitle": "จำนวนข้อมูลที่บันทึกในขอบเขตนี้",
    "lessons": "บทเรียนที่มีประวัติ",
    "assessments": "ข้อสอบ",
    "designs": "แบบยานที่บันทึก",
    "experiments": "บันทึกการทดลอง",
    "drafts": "งานร่าง",
    "customLessons": "บทเรียนส่วนตัว",
    "customQuestions": "คำถามส่วนตัว",
    "audio": "เสียงที่อัปโหลด",
    "busy": "กำลังบันทึกการเปลี่ยนแปลง…",
    "error": "ทำรายการไม่สำเร็จ: {reason}",
    "invalidName": "กรุณาระบุชื่อผู้เรียนไม่เกิน 80 ตัวอักษร",
    "reload": "โหลดหน้าเว็บใหม่",
    "status": "สถานะการจัดเก็บ",
    "backups": "ข้อมูลสำรองโปรไฟล์",
    "exportProfile": "ส่งออกพื้นที่ทำงานของผู้เรียนนี้",
    "exportAll": "ส่งออกโปรไฟล์ผู้เรียนทั้งหมด",
    "jsonMedia": "ไฟล์ JSON ของพื้นที่ทำงานไม่รวมเสียงที่อัปโหลด หากต้องการสำรองเสียง โปรดส่งออกเสียงแยกอีกไฟล์",
    "exportMedia": "ส่งออกเสียงที่ผู้เรียนนี้อัปโหลด",
    "importMedia": "คืนเสียงที่อัปโหลดให้ผู้เรียนนี้",
    "importBackup": "นำเข้าข้อมูลสำรองพื้นที่ทำงาน",
    "importLead": "ตรวจข้อมูลในไฟล์และเลือกปลายทางก่อนเปลี่ยนแปลงประวัติใด ๆ",
    "sourceProfiles": "โปรไฟล์ในไฟล์นี้",
    "legacy": "ไฟล์โปรเจกต์รุ่นเดิม: คืนได้เฉพาะส่วนที่มีบันทึกในไฟล์นั้น",
    "destination": "ปลายทางการนำเข้า",
    "newProfile": "สร้างผู้เรียนใหม่",
    "importName": "ชื่อผู้เรียนใหม่",
    "merge": "ข้อมูลเดิม",
    "keep": "เก็บข้อมูลเดิมไว้",
    "replace": "แทนที่ข้อมูลส่วนที่มีในไฟล์",
    "replaceWarning": "ข้อมูลส่วนที่มีในไฟล์นี้จะแทนที่ข้อมูลของผู้เรียนที่เลือก โปรดส่งออกข้อมูลสำรองก่อนดำเนินการ",
    "multiImport": "โปรไฟล์แต่ละคนในไฟล์นี้จะนำเข้าเป็นผู้เรียนใหม่ โดยเก็บผู้เรียนเดิมไว้",
    "importConfirm": "นำเข้าไฟล์ที่ตรวจแล้ว",
    "reading": "กำลังอ่านข้อมูลสำรอง…",
    "mediaDone": "คืนเสียงที่อัปโหลดให้ผู้เรียนนี้แล้ว",
    "mediaWarning": "เสียงที่คืนจะเป็นของผู้เรียนที่เลือก ค่าเริ่มต้นเก็บเสียงเดิมไว้ หากเลือกแทนที่จะเขียนทับเสียงที่ชื่อภารกิจตรงกัน โปรดส่งออกเสียงเดิมก่อนแทนที่",
    "mediaSource": "เสียงของ {name}: {count} รายการ",
    "errorStorage": "เบราว์เซอร์บันทึกข้อมูลไม่ได้ โปรดเก็บข้อมูลสำรองและตรวจพื้นที่ว่างของอุปกรณ์",
    "errorInvalid": "ไฟล์ ชื่อ หรือข้อมูลที่บันทึกไม่ถูกต้อง โดยยังเก็บงานเดิมไว้",
    "errorNewer": "ข้อมูลนี้เป็นรูปแบบรุ่นใหม่กว่าที่แอปอ่านได้ โปรดอัปเดตแอปก่อนนำเข้า",
    "errorStale": "พื้นที่ทำงานนี้มีการเปลี่ยนแปลงหรือถูกปิดแล้ว โปรดโหลดใหม่ก่อนแก้ข้อมูลต่อ",
    "errorMissing": "ไม่พบผู้เรียนหรือข้อมูลสำรองนี้แล้ว โปรดโหลดใหม่และเลือกผู้เรียน",
    "errorLimit": "จำนวนโปรไฟล์ถึงขีดจำกัดแล้ว โปรดสำรองข้อมูลและลบโปรไฟล์ที่ไม่ได้ใช้ก่อน",
    "errorOversize": "ไฟล์สำรองใหญ่เกินขีดจำกัดที่รองรับ จึงยังไม่นำเข้าข้อมูลใด ๆ",
    "errorPending": "มีงานจัดเก็บก่อนหน้าที่ต้องกู้คืน โปรดโหลดใหม่ก่อนเปลี่ยนแปลงข้อมูลนี้",
    "quarantine": "ข้อมูล {count} รายการจะเก็บไว้เพื่อกู้คืน โดยยังไม่เปิดใช้งานเนื้อหาที่รูปแบบไม่รองรับหรือไม่ถูกต้อง",
  },
  ru: { ...PROFILE_CONTEXT_TEXT.ru,
    "local": "Профили хранятся на этом устройстве и разделяют работы учащихся. Это не сетевые учётные записи и не вход в систему.",
    "empty": "Профилей учащихся пока нет.",
    "name": "Имя учащегося",
    "create": "Создать профиль",
    "rename": "Переименовать",
    "switch": "Открыть эту рабочую область",
    "current": "Текущий",
    "delete": "Удалить профиль",
    "cancel": "Отмена",
    "back": "Назад",
    "save": "Сохранить имя",
    "confirm": "Подтвердить",
    "backup": "Сначала экспортировать копию",
    "backupDone": "Резервная копия экспортирована. Сохраните загруженный файл перед продолжением.",
    "backupPartial": "Резервная копия читаемых профилей экспортирована. Нечитаемые профили в неё не вошли; сохраните копию каждого из списка профилей.",
    "unreadableName": "Нечитаемый профиль",
    "rowUnreadable": "Эта версия приложения не может прочитать профиль. Сохранённые данные остаются на устройстве без изменений. Сохраните копию или удалите профиль, если он больше не нужен.",
    "rowNewer": "Профиль создан более новой версией приложения. Сохранённые данные остаются на устройстве без изменений. Откройте его в новой версии, сохраните копию или удалите профиль, если он больше не нужен.",
    "rowMissing": "Сохранённых данных этого профиля на устройстве больше нет. Осталась только запись в списке; её можно удалить.",
    "backupNoneReadable": "Ни один профиль не удалось прочитать, поэтому файл резервной копии не создан. Сохраните копию каждого профиля из списка профилей.",
    "rowAction": "{action}: {name}",
    "mediaUnavailable": "Аудио можно экспортировать после перезагрузки страницы в режиме с сохранением данных.",
    "exportRaw": "Сохранить копию данных",
    "deleteUnreadableTitle": "Удалить нечитаемый профиль «{name}»?",
    "deleteUnreadableLead": "Сохранённые данные и загруженное аудио этого профиля будут безвозвратно удалены с устройства. Приложение не может показать их содержимое. Сначала сохраните копию, если она может понадобиться, например для более новой версии приложения.",
    "deleteUnreadableConfirm": "Удалить данные этого профиля",
    "createLead": "У каждого учащегося свои уроки, тесты, конструкции, миссии и записи.",
    "transition": "Страница перезагрузится и откроет выбранную рабочую область. Сохранённые работы остаются у их владельца. Текущий полёт и экран теста закроются; сохранённый тест можно продолжить позже. Переключение профиля не восстанавливает текущий полёт.",
    "switchTitle": "Открыть рабочую область {name}?",
    "createTitle": "Создать рабочую область для {name}?",
    "deleteTitle": "Удалить профиль «{name}»?",
    "deleteLead": "С этого устройства будут удалены сохранённые работы, личные настройки и загруженное аудио этого учащегося. Другие профили сохраняются. Экспортируйте резервную копию, если она нужна.",
    "deleteActive": "Это текущий учащийся. После удаления явно выберите или создайте другой профиль.",
    "deleteConfirm": "Удалить учащегося и его работы",
    "resetTitle": "Сбросить записи: {name}",
    "resetLead": "Выберите записи для удаления. Конструкции, миссии, заметки и созданные или импортированные уроки и вопросы сохраняются.",
    "scope": "Записи для удаления",
    "learning": "Вся история уроков",
    "exams": "Все тесты, включая незавершённые",
    "all": "История уроков и тесты",
    "lesson": "История одного урока",
    "chooseLesson": "Урок",
    "noLessons": "Нет записанной истории уроков для сброса.",
    "resetConfirm": "Удалить выбранные записи",
    "resetEffects": "Выбранная история, попытки, оценки, подсказки и раскрытые ответы будут удалены. Страница перезагрузится, чтобы открытая старая сессия не восстановила удалённые записи.",
    "countsTitle": "Сохранённые записи в выбранном объёме",
    "lessons": "Уроки с историей",
    "assessments": "Тесты",
    "designs": "Сохранённые конструкции",
    "experiments": "Записи экспериментов",
    "drafts": "Черновики",
    "customLessons": "Личные уроки",
    "customQuestions": "Личные вопросы",
    "audio": "Загруженное аудио",
    "busy": "Сохранение изменений…",
    "error": "Не удалось выполнить действие: {reason}",
    "invalidName": "Введите имя учащегося длиной не более 80 символов.",
    "reload": "Перезагрузить страницу",
    "status": "Состояние хранилища",
    "backups": "Резервные копии профилей",
    "exportProfile": "Экспортировать рабочую область учащегося",
    "exportAll": "Экспортировать все профили",
    "jsonMedia": "JSON рабочей области не содержит загруженное аудио. Для его резервной копии экспортируйте аудио отдельным файлом.",
    "exportMedia": "Экспортировать загруженное аудио учащегося",
    "importMedia": "Восстановить аудио для учащегося",
    "importBackup": "Импортировать резервную копию",
    "importLead": "Проверьте файл и выберите назначение до изменения записей.",
    "sourceProfiles": "Профили в файле",
    "legacy": "Старый файл проекта: восстановить можно только разделы, записанные в нём.",
    "destination": "Назначение импорта",
    "newProfile": "Создать нового учащегося",
    "importName": "Имя нового учащегося",
    "merge": "Существующие записи",
    "keep": "Сохранить существующие записи",
    "replace": "Заменить записи, присутствующие в файле",
    "replaceWarning": "Записи выбранного учащегося, присутствующие в файле, будут заменены. Сначала экспортируйте резервную копию.",
    "multiImport": "Каждый профиль из файла будет импортирован как новый учащийся. Существующие профили сохраняются.",
    "importConfirm": "Импортировать проверенный файл",
    "reading": "Чтение резервной копии…",
    "mediaDone": "Загруженное аудио восстановлено для учащегося.",
    "mediaWarning": "Аудио восстанавливается для выбранного учащегося. По умолчанию прежние записи сохраняются; замена перезаписывает аудио с совпадающими именами миссий. Сначала экспортируйте текущее аудио.",
    "mediaSource": "Аудио: {name}, записей: {count}",
    "errorStorage": "Браузер не смог сохранить изменение. Сделайте резервную копию и проверьте свободное место.",
    "errorInvalid": "Файл, имя или записи некорректны. Существующие работы сохранены.",
    "errorNewer": "Формат записей новее, чем поддерживает приложение. Обновите приложение перед импортом.",
    "errorStale": "Рабочая область изменилась или была закрыта. Перезагрузите страницу перед дальнейшими изменениями.",
    "errorMissing": "Учащийся или запись резервной копии больше недоступны. Перезагрузите страницу и выберите учащегося.",
    "errorLimit": "Достигнут предел числа профилей. Сначала сделайте копию и удалите неиспользуемый профиль.",
    "errorOversize": "Размер резервной копии превышает поддерживаемый предел. Записи не импортированы.",
    "errorPending": "Предыдущая операция хранения требует восстановления. Перезагрузите страницу перед изменениями.",
    "quarantine": "Записей для восстановления: {count}. Неподдерживаемое или некорректное содержимое не будет активировано.",
  },
} as const;

export type ProfileTextKey = keyof typeof PROFILE_TEXT.en;
export function profileText(key: ProfileTextKey, params?: Record<string, string | number>, lang: Lang = getLang()): string {
  return PROFILE_TEXT[lang][key].replace(/\{([a-zA-Z]+)\}/g, (placeholder, name: string) =>
    params && Object.hasOwn(params, name) ? String(params[name]) : placeholder);
}
