/**
 * Area 1, the basics of spaceflight (roadmap E03): what a launch vehicle looks
 * like, what keeps a satellite up, the numbers every student of the subject
 * carries in their head.
 */
import { K, O, T, U, choice, diagram, letters, multi, numeric, order, vehicle } from './helpers';

const WHICH = T('Which launch vehicle is this?', 'Какая это ракета-носитель?', 'จรวดนำส่งลำนี้คือจรวดอะไร');

export const BASICS: readonly unknown[] = [
  vehicle('b-vehicle-distinct', 1, 1, 'vehicles', WHICH,
    ['soyuz21a', 'falconheavy', 'starship', 'electron', 'protonm', 'longmarch5'],
    T('Each has a shape of its own: Soyuz its four tapered strap-ons (the Korolev cross when they separate), Falcon Heavy three cores side by side, Starship a stainless-steel ship on a 71 m booster, Electron a slender black 18 m carbon-fibre rocket, Proton-M a core ringed by six fuel tanks with their engines, Long March 5 a wide white 5 m core with four 3.35 m boosters.',
      'У каждой свой облик: у «Союза» четыре конических боковых блока («крест Королёва» при разделении), у Falcon Heavy три блока рядом, у Starship корабль из нержавеющей стали на 71-метровом ускорителе, у Electron тонкий чёрный 18-метровый корпус из углепластика, у «Протона-М» центральный блок в кольце из шести баков с двигателями, у «Чанчжэн-5» широкий белый центральный блок диаметром 5 м с четырьмя ускорителями по 3,35 м.',
      'แต่ละลำมีรูปทรงเฉพาะ: โซยุซมีบูสเตอร์ด้านข้างทรงเรียวสี่ท่อน (กางเป็น «กางเขนของโคโรเลฟ» ตอนแยกตัว) Falcon Heavy มีแกนสามแกนเรียงกัน Starship เป็นยานเหล็กกล้าไร้สนิมบนบูสเตอร์สูง 71 ม. Electron เป็นจรวดคาร์บอนไฟเบอร์สีดำเรียวสูง 18 ม. Proton-M มีลำตัวหลักล้อมด้วยถังเชื้อเพลิงหกถังพร้อมเครื่องยนต์ และ Long March 5 มีลำตัวหลักสีขาวกว้าง 5 ม. กับบูสเตอร์ 3.35 ม. สี่ท่อน')),
  vehicle('b-vehicle-similar', 1, 2, 'vehicles', WHICH,
    ['falcon9', 'atlasv551', 'vulcan', 'angaraa5', 'longmarch2d', 'protonm'],
    T('Look at the details: the strap-ons (none on Falcon 9 or Long March 2D, five slim white solids on Atlas V 551, four liquid modules as wide as the core on Angara-A5, six outboard tanks on Proton-M), the colour of the core (white Falcon 9, orange-brown Atlas V and Vulcan — Vulcan\'s wider and shorter), and the fairing\'s width against the core.',
      'Смотрите на детали: боковые блоки (у Falcon 9 и «Чанчжэн-2D» их нет, у Atlas V 551 пять тонких белых твердотопливных, у «Ангары-А5» четыре жидкостных модуля того же диаметра, что центральный, у «Протона-М» шесть боковых баков), цвет центрального блока (белый у Falcon 9, оранжево-коричневый у Atlas V и Vulcan — у Vulcan он шире и короче) и ширину обтекателя относительно корпуса.',
      'ให้สังเกตรายละเอียด: บูสเตอร์ด้านข้าง (Falcon 9 และ Long March 2D ไม่มี, Atlas V 551 มีบูสเตอร์เชื้อเพลิงแข็งสีขาวเรียวห้าท่อน, Angara-A5 มีโมดูลเชื้อเพลิงเหลวสี่ท่อนขนาดเท่าลำตัวหลัก, Proton-M มีถังรอบลำตัวหกถัง) สีของลำตัวหลัก (Falcon 9 สีขาว, Atlas V และ Vulcan สีส้มน้ำตาล — Vulcan อ้วนและสั้นกว่า) และความกว้างของฝาครอบส่วนหัวเทียบกับลำตัว')),
  choice('b-karman', 1, 1, K, 'space.boundary',
    T('Where does space conventionally begin?', 'Где условно начинается космос?', 'โดยทั่วไปถือว่าอวกาศเริ่มต้นที่ความสูงเท่าใด'),
    [O(T('At 100 km (the Kármán line)', 'На высоте 100 км (линия Кармана)', 'ที่ 100 กม. (เส้นคาร์มาน)'), true),
      O(T('At 10 km, where airliners fly', 'На высоте 10 км, где летают авиалайнеры', 'ที่ 10 กม. ซึ่งเป็นระดับที่เครื่องบินโดยสารบิน')),
      O(T('At 400 km, where the ISS flies', 'На высоте 400 км, где летает МКС', 'ที่ 400 กม. ซึ่งเป็นระดับของ ISS')),
      O(T('At 36 000 km, the geostationary orbit', 'На высоте 36 000 км, на геостационарной орбите', 'ที่ 36 000 กม. วงโคจรค้างฟ้า'))],
    T('The FAI takes 100 km, the Kármán line, as the boundary: above it the air is too thin for wings to carry an aircraft at any speed short of orbital speed.',
      'ФАИ принимает за границу 100 км — линию Кармана: выше воздух так разрежен, что крыло не держит аппарат ни на какой скорости, меньшей орбитальной.',
      'FAI ใช้ 100 กม. (เส้นคาร์มาน) เป็นขอบเขต เหนือระดับนี้อากาศเบาบางจนปีกไม่สามารถพยุงอากาศยานได้เลยหากความเร็วต่ำกว่าความเร็ววงโคจร')),
  choice('b-float', 1, 1, U, 'orbit.freefall',
    T('Why do astronauts float inside the space station?', 'Почему космонавты парят внутри космической станции?', 'ทำไมนักบินอวกาศจึงลอยตัวอยู่ภายในสถานีอวกาศ'),
    [O(T('They and the station are falling round the Earth together (free fall)', 'Они и станция вместе падают вокруг Земли (свободное падение)', 'ทั้งนักบินและสถานีกำลังตกรอบโลกไปพร้อมกัน (การตกอิสระ)'), true),
      O(T('There is no gravity at that altitude', 'На этой высоте нет силы тяжести', 'ที่ความสูงนั้นไม่มีแรงโน้มถ่วง'), false,
        T('gravity vanishes in orbit — at 400 km it is still about 90 % of its surface value', 'в космосе тяжесть исчезает — на 400 км она составляет около 90 % земной', 'แรงโน้มถ่วงหายไปในวงโคจร ทั้งที่ที่ 400 กม. ยังเหลือราว 90 % ของที่ผิวโลก')),
      O(T('The station spins and throws them outward', 'Станция вращается и отбрасывает их наружу', 'สถานีหมุนและเหวี่ยงพวกเขาออกไป')),
      O(T('The air inside the station holds them up', 'Их удерживает воздух внутри станции', 'อากาศภายในสถานีพยุงพวกเขาไว้'))],
    T('Gravity at 400 km is about 8.7 m/s². Everything in the station falls with the same acceleration, so nothing presses on anything: that is weightlessness. The station never hits the ground because it moves sideways at 7.7 km/s.',
      'Ускорение силы тяжести на 400 км около 8,7 м/с². Всё в станции падает с одним ускорением, и ничто ни на что не давит — это невесомость. Станция не падает на Землю, потому что летит вбок со скоростью 7,7 км/с.',
      'ความเร่งโน้มถ่วงที่ 400 กม. ประมาณ 8.7 ม./วินาที² ทุกสิ่งในสถานีตกด้วยความเร่งเท่ากัน จึงไม่มีอะไรกดทับกัน นั่นคือภาวะไร้น้ำหนัก สถานีไม่ตกถึงพื้นเพราะเคลื่อนที่ในแนวข้างด้วยความเร็ว 7.7 กม./วินาที'),
    { lessons: ['orbit-first'] }),
  choice('b-what-holds', 1, 1, U, 'orbit.gravity',
    T('What keeps a satellite on its orbit?', 'Что удерживает спутник на орбите?', 'อะไรทำให้ดาวเทียมยังอยู่ในวงโคจร'),
    [O(T('The Earth\'s gravity, bending its path round the planet', 'Притяжение Земли, искривляющее его путь вокруг планеты', 'แรงโน้มถ่วงของโลกซึ่งดัดทางเดินของมันให้โค้งรอบโลก'), true),
      O(T('Its engines, firing all the time', 'Его двигатели, работающие непрерывно', 'เครื่องยนต์ของมันซึ่งทำงานตลอดเวลา'), false,
        T('a satellite needs thrust to stay up — in orbit it coasts', 'спутнику нужна тяга, чтобы держаться, — на орбите он летит по инерции', 'ดาวเทียมต้องใช้แรงขับเพื่ออยู่ในวงโคจร ทั้งที่ในวงโคจรมันเคลื่อนที่ด้วยความเฉื่อย')),
      O(T('Nothing: there is no gravity in space', 'Ничего: в космосе нет притяжения', 'ไม่มีอะไร เพราะในอวกาศไม่มีแรงโน้มถ่วง'), false,
        T('space has no gravity', 'в космосе нет гравитации', 'ในอวกาศไม่มีแรงโน้มถ่วง')),
      O(T('The thin air at that height', 'Разреженный воздух на этой высоте', 'อากาศเบาบางที่ระดับนั้น'))],
    T('Gravity is the only force needed: it supplies exactly the centripetal acceleration v²/r of the circular path. Without it the satellite would fly off in a straight line.',
      'Нужна только сила тяжести: она даёт ровно то центростремительное ускорение v²/r, которое требуется круговой траектории. Без неё спутник улетел бы по прямой.',
      'ต้องการเพียงแรงโน้มถ่วง ซึ่งให้ความเร่งสู่ศูนย์กลาง v²/r พอดีกับที่ทางโคจรวงกลมต้องการ ถ้าไม่มีแรงนี้ ดาวเทียมจะพุ่งออกไปเป็นเส้นตรง')),
  choice('b-launch-east', 1, 1, U, 'launch.rotation',
    T('Why do most rockets launch towards the east?', 'Почему большинство ракет стартует в восточном направлении?', 'ทำไมจรวดส่วนใหญ่จึงปล่อยไปทางทิศตะวันออก'),
    [O(T('The Earth\'s rotation gives them several hundred m/s for free', 'Вращение Земли даёт им несколько сотен м/с даром', 'การหมุนของโลกให้ความเร็วเพิ่มหลายร้อยเมตรต่อวินาทีโดยไม่ต้องใช้เชื้อเพลิง'), true),
      O(T('The prevailing winds blow from the west', 'Преобладающие ветры дуют с запада', 'ลมประจำพัดมาจากทิศตะวันตก'), false,
        T('the launch direction is chosen for the wind', 'направление пуска выбирают по ветру', 'ทิศการปล่อยเลือกตามลม')),
      O(T('The Sun rises in the east and powers the solar panels', 'Солнце восходит на востоке и питает солнечные батареи', 'ดวงอาทิตย์ขึ้นทางตะวันออกและให้พลังงานกับแผงเซลล์แสงอาทิตย์')),
      O(T('It is a convention with no physical reason', 'Это условность без физической причины', 'เป็นเพียงธรรมเนียม ไม่มีเหตุผลทางฟิสิกส์'))],
    T('The ground itself moves east at 465 m/s at the equator (409 m/s at Cape Canaveral, 324 m/s at Baikonur). A rocket that launches east keeps that speed; one that launches west has to cancel it first.',
      'Сама поверхность Земли движется на восток со скоростью 465 м/с на экваторе (409 м/с на мысе Канаверал, 324 м/с на Байконуре). Ракета, стартующая на восток, сохраняет эту скорость, а стартующая на запад должна сначала её погасить.',
      'พื้นผิวโลกเคลื่อนไปทางตะวันออกด้วยความเร็ว 465 ม./วินาทีที่เส้นศูนย์สูตร (409 ม./วินาทีที่แหลมคะแนเวอรัล และ 324 ม./วินาทีที่ไบโคนูร์) จรวดที่ปล่อยไปทางตะวันออกได้ความเร็วนี้ติดไปด้วย ส่วนจรวดที่ปล่อยไปทางตะวันตกต้องหักล้างความเร็วนี้ก่อน'),
    { lessons: ['orbit-range-safety'] }),
  choice('b-vacuum-thrust', 1, 1, U, 'rocket.reaction',
    T('In the vacuum of space there is no air. What does a rocket engine push against?', 'В космическом вакууме нет воздуха. От чего отталкивается ракетный двигатель?', 'ในสุญญากาศไม่มีอากาศ เครื่องยนต์จรวดดันตัวเองกับอะไร'),
    [O(T('Against its own exhaust: it throws mass backwards and is pushed forwards', 'От собственных продуктов сгорания: выбрасывает массу назад и получает импульс вперёд', 'ดันกับไอเสียของตัวเอง โดยพ่นมวลไปข้างหลังจึงถูกผลักไปข้างหน้า'), true),
      O(T('It cannot work in a vacuum; rockets coast in space', 'В вакууме он работать не может; в космосе ракеты летят по инерции', 'ทำงานในสุญญากาศไม่ได้ ในอวกาศจรวดจึงเคลื่อนที่ด้วยความเฉื่อยเท่านั้น'), false,
        T('a rocket needs air to push against', 'ракете нужен воздух, чтобы от него отталкиваться', 'จรวดต้องมีอากาศไว้ดันตัว')),
      O(T('Against the Earth\'s magnetic field', 'От магнитного поля Земли', 'ดันกับสนามแม่เหล็กโลก')),
      O(T('Against the solar wind', 'От солнечного ветра', 'ดันกับลมสุริยะ'))],
    T('Momentum is conserved: the gas leaving the nozzle carries momentum backwards, so the rocket gains the same momentum forwards. A rocket works better in vacuum than in air, because nothing pushes back on its nozzle exit.',
      'Импульс сохраняется: газ, покидающий сопло, уносит импульс назад, и ракета получает такой же импульс вперёд. В вакууме двигатель работает даже лучше, чем в воздухе, — на срез сопла ничто не давит.',
      'โมเมนตัมถูกอนุรักษ์ แก๊สที่ออกจากหัวฉีดพาโมเมนตัมไปข้างหลัง จรวดจึงได้โมเมนตัมเท่ากันไปข้างหน้า เครื่องยนต์จรวดทำงานในสุญญากาศได้ดีกว่าในอากาศด้วย เพราะไม่มีความดันบรรยากาศต้านที่ปากหัวฉีด')),
  choice('b-sputnik', 1, 1, K, 'history.first',
    T('The first artificial satellite was launched…', 'Первый искусственный спутник Земли был запущен…', 'ดาวเทียมดวงแรกของมนุษย์ถูกส่งขึ้นเมื่อ…'),
    [O(T('Sputnik-1, by the USSR, on 4 October 1957', '«Спутник-1», СССР, 4 октября 1957 года', 'สปุตนิก-1 โดยสหภาพโซเวียต เมื่อ 4 ตุลาคม 1957'), true),
      O(T('Explorer 1, by the USA, in 1958', 'Explorer 1, США, в 1958 году', 'เอกซ์พลอเรอร์ 1 โดยสหรัฐอเมริกา ปี 1958')),
      O(T('Vostok-1, by the USSR, in 1961', '«Восток-1», СССР, в 1961 году', 'วอสตอค-1 โดยสหภาพโซเวียต ปี 1961')),
      O(T('Apollo 11, by the USA, in 1969', 'Apollo 11, США, в 1969 году', 'อะพอลโล 11 โดยสหรัฐอเมริกา ปี 1969'))],
    T('Sputnik-1 went up on an R-7 from Baikonur on 4 October 1957. Vostok-1 carried Yuri Gagarin, the first person in space, on 12 April 1961; the Soyuz that flies today descends from the same R-7.',
      '«Спутник-1» был выведен ракетой Р-7 с Байконура 4 октября 1957 года. «Восток-1» 12 апреля 1961 года доставил в космос первого человека — Юрия Гагарина; нынешний «Союз» — потомок той же Р-7.',
      'สปุตนิก-1 ขึ้นสู่อวกาศด้วยจรวด R-7 จากไบโคนูร์เมื่อ 4 ตุลาคม 1957 ส่วนวอสตอค-1 พายูริ กาการิน มนุษย์คนแรกขึ้นสู่อวกาศเมื่อ 12 เมษายน 1961 และจรวดโซยุซในปัจจุบันก็สืบทอดมาจาก R-7 ลำเดียวกันนี้'),
    { lessons: ['adv-history', 'adv-vostok'] }),
  choice('b-leo-speed', 1, 2, K, 'orbit.speed',
    T('About how fast must a satellite move to stay in a low orbit, 200–400 km up?', 'С какой примерно скоростью должен двигаться спутник на низкой орбите высотой 200–400 км?', 'ดาวเทียมในวงโคจรต่ำที่ความสูง 200–400 กม. ต้องเคลื่อนที่เร็วประมาณเท่าใด'),
    [O(T('About 7.7 km/s', 'Около 7,7 км/с', 'ประมาณ 7.7 กม./วินาที'), true),
      O(T('About 1 km/s', 'Около 1 км/с', 'ประมาณ 1 กม./วินาที')),
      O(T('About 11.2 km/s', 'Около 11,2 км/с', 'ประมาณ 11.2 กม./วินาที')),
      O(T('About 340 m/s, the speed of sound', 'Около 340 м/с, скорость звука', 'ประมาณ 340 ม./วินาที เท่าความเร็วเสียง'))],
    T('v = √(μ/r): with μ = 398 600 km³/s² and r ≈ 6 700 km this is 7.7 km/s, the first cosmic velocity near the surface being 7.9 km/s. 11.2 km/s is the escape velocity.',
      'v = √(μ/r): при μ = 398 600 км³/с² и r ≈ 6 700 км это 7,7 км/с; первая космическая скорость у поверхности — 7,9 км/с. 11,2 км/с — вторая космическая (скорость убегания).',
      'v = √(μ/r) เมื่อ μ = 398 600 กม.³/วินาที² และ r ≈ 6 700 กม. จะได้ 7.7 กม./วินาที ความเร็วหลุดพ้นแรกใกล้ผิวโลกคือ 7.9 กม./วินาที ส่วน 11.2 กม./วินาทีคือความเร็วหลุดพ้น'),
    { lessons: ['orbit-first'] }),
  choice('b-iss-period', 1, 2, K, 'orbit.period',
    T('How long does the International Space Station take to go once round the Earth?', 'За какое время МКС совершает один виток вокруг Земли?', 'สถานีอวกาศนานาชาติใช้เวลาโคจรรอบโลกหนึ่งรอบนานเท่าใด'),
    [O(T('About 92 minutes', 'Около 92 минут', 'ประมาณ 92 นาที'), true),
      O(T('About 24 hours', 'Около 24 часов', 'ประมาณ 24 ชั่วโมง')),
      O(T('About 12 hours', 'Около 12 часов', 'ประมาณ 12 ชั่วโมง')),
      O(T('About 27 days, like the Moon', 'Около 27 суток, как Луна', 'ประมาณ 27 วัน เท่ากับดวงจันทร์'))],
    T('At about 420 km the period is 2π√(a³/μ) ≈ 92.7 min: sixteen sunrises a day. Twenty-four hours is the period of an orbit 35 786 km up.',
      'На высоте около 420 км период 2π√(a³/μ) ≈ 92,7 мин — шестнадцать восходов в сутки. Двадцать четыре часа — период орбиты на высоте 35 786 км.',
      'ที่ความสูงประมาณ 420 กม. คาบคือ 2π√(a³/μ) ≈ 92.7 นาที เห็นพระอาทิตย์ขึ้นวันละสิบหกครั้ง ส่วน 24 ชั่วโมงคือคาบของวงโคจรที่สูง 35 786 กม.'),
    { lessons: ['orbit-first'] }),
  choice('b-geo', 1, 2, K, 'orbit.geo',
    T('A geostationary satellite hangs over one point of the equator. How high is it?', 'Геостационарный спутник висит над одной точкой экватора. На какой он высоте?', 'ดาวเทียมค้างฟ้าอยู่เหนือจุดหนึ่งบนเส้นศูนย์สูตรตลอดเวลา มันอยู่สูงเท่าใด'),
    [O(T('About 35 800 km', 'Около 35 800 км', 'ประมาณ 35 800 กม.'), true),
      O(T('About 400 km', 'Около 400 км', 'ประมาณ 400 กม.')),
      O(T('About 20 200 km', 'Около 20 200 км', 'ประมาณ 20 200 กม.')),
      O(T('About 384 000 km', 'Около 384 000 км', 'ประมาณ 384 000 กม.'))],
    T('It must go round once per sidereal day (23 h 56 min); Kepler\'s third law puts that orbit 35 786 km above the equator. 20 200 km is the GPS orbit, 384 000 km the Moon\'s distance.',
      'Он должен совершать виток за звёздные сутки (23 ч 56 мин); по третьему закону Кеплера такая орбита лежит на высоте 35 786 км над экватором. 20 200 км — орбита GPS, 384 000 км — расстояние до Луны.',
      'มันต้องโคจรครบรอบในหนึ่งวันดาราคติ (23 ชม. 56 นาที) ตามกฎข้อที่สามของเคปเลอร์วงโคจรนี้อยู่สูง 35 786 กม. เหนือเส้นศูนย์สูตร ส่วน 20 200 กม. คือวงโคจร GPS และ 384 000 กม. คือระยะถึงดวงจันทร์')),
  choice('b-stages', 1, 2, U, 'rocket.staging',
    T('Why are launch vehicles built in stages?', 'Зачем ракеты-носители делают многоступенчатыми?', 'ทำไมจรวดนำส่งจึงสร้างเป็นหลายขั้น'),
    [O(T('To drop empty tanks and engines, so the rest has less dead mass to accelerate', 'Чтобы сбрасывать пустые баки и двигатели и не разгонять лишнюю массу', 'เพื่อทิ้งถังและเครื่องยนต์ที่หมดประโยชน์ ส่วนที่เหลือจึงไม่ต้องเร่งมวลที่ไม่จำเป็น'), true),
      O(T('Because one stage could never lift the payload off the pad', 'Потому что одна ступень не смогла бы оторвать груз от стола', 'เพราะขั้นเดียวยกน้ำหนักบรรทุกให้พ้นแท่นไม่ได้'), false,
        T('staging is about lift-off thrust, not about the mass ratio', 'ступени нужны для тяги на старте, а не для отношения масс', 'การแบ่งขั้นมีไว้เพื่อแรงขับตอนออกตัว ไม่ใช่เพื่ออัตราส่วนมวล')),
      O(T('To make the rocket easier to transport', 'Чтобы ракету было легче перевозить', 'เพื่อให้ขนส่งจรวดได้ง่ายขึ้น')),
      O(T('So that each stage can burn a different propellant for safety', 'Чтобы каждая ступень ради безопасности работала на своём топливе', 'เพื่อให้แต่ละขั้นใช้เชื้อเพลิงต่างกันเพื่อความปลอดภัย'))],
    T('Δv = Isp·g0·ln(m0/mf) depends on the mass ratio. A single stage carries its empty structure all the way to orbit; dropping it on the way raises the mass ratio of what flies on.',
      'Δv = Iуд·g0·ln(m0/mк) зависит от отношения масс. Одноступенчатая ракета несёт пустую конструкцию до самой орбиты; сброс её по пути повышает отношение масс оставшейся части.',
      'Δv = Isp·g0·ln(m0/mf) ขึ้นกับอัตราส่วนมวล จรวดขั้นเดียวต้องแบกโครงสร้างเปล่าไปจนถึงวงโคจร การทิ้งมันระหว่างทางจึงเพิ่มอัตราส่วนมวลของส่วนที่บินต่อ'),
    { lessons: ['orbit-payload'] }),
  choice('b-kepler2', 1, 2, U, 'orbit.kepler2',
    T('On an elliptical orbit, where does a satellite move fastest?', 'Где спутник на эллиптической орбите движется быстрее всего?', 'บนวงโคจรวงรี ดาวเทียมเคลื่อนที่เร็วที่สุดที่ตำแหน่งใด'),
    [O(T('At perigee, the point nearest the Earth', 'В перигее, ближайшей к Земле точке', 'ที่จุดใกล้โลกที่สุด (perigee)'), true),
      O(T('At apogee, the point farthest from the Earth', 'В апогее, наиболее удалённой точке', 'ที่จุดไกลโลกที่สุด (apogee)'), false,
        T('it gathers speed as it climbs away from the Earth', 'удаляясь от Земли, он разгоняется', 'มันเร่งความเร็วขึ้นเมื่อเคลื่อนห่างจากโลก')),
      O(T('Everywhere at the same speed', 'Везде с одинаковой скоростью', 'เร็วเท่ากันทุกตำแหน่ง'), false,
        T('an orbit has one speed, like a circle', 'у орбиты одна скорость, как у круговой', 'วงโคจรมีอัตราเร็วเดียว เหมือนวงกลม')),
      O(T('Where it crosses the equator', 'Там, где пересекает экватор', 'ที่ตำแหน่งที่ตัดเส้นศูนย์สูตร'))],
    T('Kepler\'s second law: the line to the Earth sweeps equal areas in equal times, so the satellite moves fastest where it is closest. Energy says the same: falling towards the Earth it trades height for speed.',
      'Второй закон Кеплера: радиус-вектор заметает равные площади за равные времена, поэтому быстрее всего спутник движется там, где он ближе всего. То же следует из энергии: приближаясь к Земле, он обменивает высоту на скорость.',
      'กฎข้อที่สองของเคปเลอร์: เส้นที่ลากจากโลกกวาดพื้นที่เท่ากันในเวลาเท่ากัน ดาวเทียมจึงเร็วที่สุดเมื่ออยู่ใกล้ที่สุด พลังงานก็บอกเช่นเดียวกัน ขณะตกเข้าหาโลกมันแลกความสูงเป็นความเร็ว')),
  choice('b-black-sky', 1, 2, K, 'space.sky',
    T('Why is the sky black above about 100 km, even in daylight?', 'Почему выше 100 км небо чёрное даже днём?', 'ทำไมท้องฟ้าเหนือระดับประมาณ 100 กม. จึงมืดดำแม้ในเวลากลางวัน'),
    [O(T('There is almost no air left to scatter sunlight', 'Там почти не осталось воздуха, рассеивающего солнечный свет', 'แทบไม่มีอากาศเหลือที่จะกระเจิงแสงอาทิตย์'), true),
      O(T('The Sun is too far away up there', 'Солнце там слишком далеко', 'ที่ระดับนั้นดวงอาทิตย์อยู่ไกลเกินไป')),
      O(T('The ozone layer blocks the light', 'Озоновый слой задерживает свет', 'ชั้นโอโซนกั้นแสงไว้')),
      O(T('It is always night in orbit', 'На орбите всегда ночь', 'ในวงโคจรเป็นกลางคืนตลอดเวลา'))],
    T('The blue of the sky is sunlight scattered by air molecules (Rayleigh scattering). With no air to scatter it, only the Sun\'s disc and the stars are left against black.',
      'Голубой цвет неба — это солнечный свет, рассеянный молекулами воздуха (рэлеевское рассеяние). Без воздуха на чёрном фоне остаются только диск Солнца и звёзды.',
      'สีฟ้าของท้องฟ้าคือแสงอาทิตย์ที่ถูกโมเลกุลอากาศกระเจิง (การกระเจิงแบบเรย์ลี) เมื่อไม่มีอากาศกระเจิงแสง จึงเหลือเพียงดวงอาทิตย์และดวงดาวบนพื้นหลังสีดำ')),
  choice('b-escape', 1, 2, K, 'orbit.escape',
    T('What speed does a body at the Earth\'s surface need to leave the Earth for good, ignoring the air?', 'Какая скорость нужна телу у поверхности Земли, чтобы навсегда покинуть Землю (без учёта атмосферы)?', 'วัตถุที่ผิวโลกต้องมีความเร็วเท่าใดจึงจะหลุดพ้นจากโลกได้อย่างถาวร (ไม่คิดอากาศ)'),
    [O(T('11.2 km/s', '11,2 км/с', '11.2 กม./วินาที'), true),
      O(T('7.9 km/s', '7,9 км/с', '7.9 กม./วินาที')),
      O(T('3.1 km/s', '3,1 км/с', '3.1 กม./วินาที')),
      O(T('30 km/s', '30 км/с', '30 กม./วินาที'))],
    T('Escape velocity √(2μ/R) = √2 × the circular velocity: 11.2 km/s against 7.9 km/s at the surface. 30 km/s is the Earth\'s own speed round the Sun.',
      'Вторая космическая скорость √(2μ/R) = √2 × круговая: 11,2 км/с против 7,9 км/с у поверхности. 30 км/с — скорость самой Земли вокруг Солнца.',
      'ความเร็วหลุดพ้น √(2μ/R) = √2 × ความเร็ววงโคจรวงกลม คือ 11.2 กม./วินาที เทียบกับ 7.9 กม./วินาทีที่ผิวโลก ส่วน 30 กม./วินาทีคือความเร็วที่โลกโคจรรอบดวงอาทิตย์')),
  choice('b-higher-slower', 1, 3, U, 'orbit.speed',
    T('The space station is raised from 400 km to 420 km, still on a circular orbit. Its orbital speed…', 'Орбиту станции подняли с 400 до 420 км, орбита по-прежнему круговая. Её орбитальная скорость…', 'สถานีอวกาศถูกยกวงโคจรจาก 400 กม. เป็น 420 กม. ยังคงเป็นวงกลม อัตราเร็วในวงโคจรของมัน…'),
    [O(T('…goes down slightly', '…немного уменьшится', '…ลดลงเล็กน้อย'), true),
      O(T('…goes up, because it took thrust to get there', '…увеличится, ведь для подъёма работали двигатели', '…เพิ่มขึ้น เพราะต้องใช้แรงขับเพื่อขึ้นไป'), false,
        T('a higher orbit is a faster orbit', 'более высокая орбита — более быстрая', 'วงโคจรที่สูงกว่าคือวงโคจรที่เร็วกว่า')),
      O(T('…does not change: speed does not depend on height', '…не изменится: скорость не зависит от высоты', '…ไม่เปลี่ยน เพราะอัตราเร็วไม่ขึ้นกับความสูง')),
      O(T('…drops to zero at the top of the climb', '…упадёт до нуля в верхней точке подъёма', '…ลดลงเป็นศูนย์ที่จุดสูงสุดของการไต่'))],
    T('v = √(μ/r) falls as r grows: 7.67 → 7.66 km/s. The engines add speed at each burn, but climbing trades more speed for height than they added: a higher orbit is slower.',
      'v = √(μ/r) убывает с ростом r: 7,67 → 7,66 км/с. Двигатели при каждом включении добавляют скорость, но подъём отнимает её больше, чем было добавлено: более высокая орбита медленнее.',
      'v = √(μ/r) ลดลงเมื่อ r เพิ่ม: 7.67 → 7.66 กม./วินาที เครื่องยนต์เพิ่มความเร็วทุกครั้งที่จุด แต่การไต่ระดับแลกความเร็วเป็นความสูงมากกว่าที่เพิ่มไป วงโคจรที่สูงกว่าจึงช้ากว่า'),
    { lessons: ['orbit-hohmann'] }),
  choice('b-opposite-side', 1, 3, U, 'orbit.burn',
    T('A satellite on a circular orbit fires its engine forwards along its motion for a short burn. Where does its orbit rise the most?', 'Спутник на круговой орбите кратковременно включает двигатель по направлению движения. Где орбита поднимется сильнее всего?', 'ดาวเทียมบนวงโคจรวงกลมจุดเครื่องยนต์สั้น ๆ ไปในทิศการเคลื่อนที่ วงโคจรจะสูงขึ้นมากที่สุดที่ใด'),
    [O(T('On the opposite side of the orbit, half a revolution later', 'На противоположной стороне орбиты, через пол-витка', 'ที่ด้านตรงข้ามของวงโคจร อีกครึ่งรอบถัดไป'), true),
      O(T('Right where the burn was made', 'Прямо в точке включения', 'ตรงจุดที่จุดเครื่องนั้นเอง'), false,
        T('a burn raises the orbit where it is made', 'импульс поднимает орбиту в точке приложения', 'การจุดเครื่องยกวงโคจรขึ้นที่ตำแหน่งที่จุด')),
      O(T('A quarter of a revolution later', 'Через четверть витка', 'อีกหนึ่งในสี่รอบถัดไป')),
      O(T('Everywhere by the same amount', 'Везде одинаково', 'สูงขึ้นเท่ากันทุกตำแหน่ง'))],
    T('The burn point becomes the new perigee; the extra energy raises the apogee, 180° away. That is why a Hohmann transfer takes two burns half an orbit apart.',
      'Точка включения становится новым перигеем, а добавленная энергия поднимает апогей — на 180° дальше. Поэтому гомановский перелёт состоит из двух импульсов через пол-витка.',
      'จุดที่จุดเครื่องกลายเป็นจุดใกล้โลกใหม่ พลังงานที่เพิ่มไปยกจุดไกลโลกซึ่งอยู่ห่างไป 180° การถ่ายโอนแบบโฮมันน์จึงต้องจุดเครื่องสองครั้งห่างกันครึ่งรอบ'),
    { lessons: ['orbit-hohmann'] }),
  numeric('b-gravity-altitude', 1, 3, K, 'orbit.gravity',
    T('Work out the acceleration of gravity at an altitude of {h} km (m/s²). Take g0 = 9.81 m/s² at the surface and R = 6 378 km.',
      'Рассчитайте ускорение силы тяжести на высоте {h} км (м/с²). Примите g0 = 9,81 м/с² у поверхности и R = 6 378 км.',
      'คำนวณความเร่งโน้มถ่วงที่ความสูง {h} กม. (ม./วินาที²) ให้ g0 = 9.81 ม./วินาที² ที่ผิวโลก และ R = 6 378 กม.'),
    [{ name: 'h', min: 200, max: 1200, step: 50 }], '9.81 * (6378 / (6378 + h))^2', 'm/s²', 2,
    T('Gravity falls with the square of the distance from the centre: g = g0·(R/(R+h))². At 400 km it is still 8.7 m/s², about 89 % of the surface value.',
      'Сила тяжести убывает обратно пропорционально квадрату расстояния от центра: g = g0·(R/(R+h))². На 400 км это ещё 8,7 м/с², около 89 % от значения у поверхности.',
      'แรงโน้มถ่วงลดลงตามกำลังสองของระยะจากศูนย์กลาง: g = g0·(R/(R+h))² ที่ 400 กม. ยังเหลือ 8.7 ม./วินาที² หรือประมาณ 89 % ของค่าที่ผิวโลก')),
  choice('b-gravity-iss', 1, 3, U, 'orbit.gravity',
    T('How strong is the Earth\'s gravity at the height of the ISS, compared with the ground?', 'Какова сила тяжести на высоте МКС по сравнению с поверхностью?', 'แรงโน้มถ่วงของโลกที่ระดับความสูงของ ISS แรงเท่าใดเมื่อเทียบกับที่พื้นดิน'),
    [O(T('About 90 %', 'Около 90 %', 'ประมาณ 90 %'), true),
      O(T('Zero', 'Нулевая', 'เป็นศูนย์'), false,
        T('weightlessness means there is no gravity', 'невесомость означает отсутствие тяготения', 'ภาวะไร้น้ำหนักหมายถึงไม่มีแรงโน้มถ่วง')),
      O(T('About 10 %', 'Около 10 %', 'ประมาณ 10 %')),
      O(T('About 50 %', 'Около 50 %', 'ประมาณ 50 %'))],
    T('(6 378 / 6 798)² ≈ 0.88. The crew feels nothing because they are in free fall with the station, not because gravity has gone.',
      '(6 378 / 6 798)² ≈ 0,88. Экипаж ничего не ощущает, потому что свободно падает вместе со станцией, а не потому, что тяготение исчезло.',
      '(6 378 / 6 798)² ≈ 0.88 ลูกเรือไม่รู้สึกถึงแรงนี้เพราะกำลังตกอิสระไปพร้อมกับสถานี ไม่ใช่เพราะแรงโน้มถ่วงหายไป'),
    { fixedOrder: true }),
  order('b-order-altitude', 1, 1, K, 'space.altitudes',
    T('Put these in order of height above the Earth, lowest first.', 'Расположите по высоте над Землёй, начиная с наименьшей.', 'เรียงตามความสูงเหนือพื้นโลก จากต่ำที่สุดไปสูงที่สุด'),
    [T('An airliner at cruise, about 10 km', 'Авиалайнер на эшелоне, около 10 км', 'เครื่องบินโดยสารที่ระดับบินเดินทาง ประมาณ 10 กม.'),
      T('The Kármán line, 100 km', 'Линия Кармана, 100 км', 'เส้นคาร์มาน 100 กม.'),
      T('The International Space Station, about 420 km', 'Международная космическая станция, около 420 км', 'สถานีอวกาศนานาชาติ ประมาณ 420 กม.'),
      T('GPS and GLONASS navigation satellites, about 20 000 km', 'Навигационные спутники GPS и ГЛОНАСС, около 20 000 км', 'ดาวเทียมนำทาง GPS และ GLONASS ประมาณ 20 000 กม.'),
      T('Geostationary satellites, 35 786 km', 'Геостационарные спутники, 35 786 км', 'ดาวเทียมค้างฟ้า 35 786 กม.')],
    T('Low orbits (the ISS, Earth observation) lie a few hundred kilometres up, just above most of the atmosphere; the navigation constellations fly at about 20 000 km (medium orbits) and the geostationary ring at 35 786 km, where one turn takes a sidereal day.',
      'Низкие орбиты (МКС, спутники наблюдения) лежат на высоте нескольких сотен километров, чуть выше основной толщи атмосферы; навигационные группировки летают на высоте около 20 000 км (средние орбиты), геостационарное кольцо — на 35 786 км, где один оборот занимает звёздные сутки.',
      'วงโคจรต่ำ (ISS ดาวเทียมสำรวจโลก) อยู่สูงไม่กี่ร้อยกิโลเมตร เหนือชั้นบรรยากาศส่วนใหญ่เพียงเล็กน้อย กลุ่มดาวเทียมนำทางโคจรที่ประมาณ 20 000 กม. (วงโคจรระดับกลาง) ส่วนวงแหวนค้างฟ้าอยู่ที่ 35 786 กม. ซึ่งโคจรหนึ่งรอบใช้เวลาหนึ่งวันดาราคติ')),
  order('b-order-history', 1, 2, K, 'history.order',
    T('Put these events of spaceflight in the order they happened.', 'Расположите события космонавтики в хронологическом порядке.', 'เรียงเหตุการณ์ด้านการบินอวกาศต่อไปนี้ตามลำดับเวลาที่เกิดขึ้น'),
    [T('Sputnik 1, the first artificial satellite', 'Спутник-1, первый искусственный спутник Земли', 'สปุตนิก 1 ดาวเทียมดวงแรกที่มนุษย์สร้าง'),
      T('Yuri Gagarin\'s flight on Vostok', 'Полёт Юрия Гагарина на «Востоке»', 'การบินของยูรี กาการินด้วยยานวอสตอค'),
      T('Apollo 11 lands on the Moon', 'Посадка «Аполлона-11» на Луну', 'อะพอลโล 11 ลงจอดบนดวงจันทร์'),
      T('Zarya, the first module of the ISS, reaches orbit', 'Выведение «Зари», первого модуля МКС', 'โมดูลซาร์ยา โมดูลแรกของ ISS ขึ้นสู่วงโคจร'),
      T('THEOS, Thailand\'s first Earth-observation satellite, is launched', 'Запуск THEOS, первого тайского спутника наблюдения Земли', 'การส่งดาวเทียม THEOS ดาวเทียมสำรวจโลกดวงแรกของไทย')],
    T('Sputnik 1: 4 October 1957; Gagarin: 12 April 1961; Apollo 11: 20 July 1969; Zarya: 20 November 1998; THEOS (Thaichote): 1 October 2008.',
      '«Спутник-1» — 4 октября 1957 г.; Гагарин — 12 апреля 1961 г.; «Аполлон-11» — 20 июля 1969 г.; «Заря» — 20 ноября 1998 г.; THEOS («Тайчот») — 1 октября 2008 г.',
      'สปุตนิก 1: 4 ตุลาคม 1957; กาการิน: 12 เมษายน 1961; อะพอลโล 11: 20 กรกฎาคม 1969; ซาร์ยา: 20 พฤศจิกายน 1998; THEOS (ไทยโชต): 1 ตุลาคม 2008'),
    { lessons: ['adv-history', 'adv-vostok', 'adv-apollo'] }),
  multi('b-multi-leo', 1, 2, K, 'orbit.regimes',
    T('Which of these fly in low Earth orbit (below about 2 000 km)? Choose every one.', 'Какие из них летают на низкой околоземной орбите (ниже примерно 2 000 км)? Выберите все.', 'ข้อใดโคจรอยู่ในวงโคจรต่ำของโลก (ต่ำกว่าประมาณ 2 000 กม.) เลือกทุกข้อที่ถูก'),
    [O(T('The International Space Station', 'Международная космическая станция', 'สถานีอวกาศนานาชาติ'), true),
      O(T('The Hubble Space Telescope', 'Космический телескоп «Хаббл»', 'กล้องโทรทรรศน์อวกาศฮับเบิล'), true),
      O(T('Starlink communication satellites', 'Спутники связи Starlink', 'ดาวเทียมสื่อสาร Starlink'), true),
      O(T('GPS navigation satellites', 'Навигационные спутники GPS', 'ดาวเทียมนำทาง GPS')),
      O(T('A geostationary weather satellite such as Himawari', 'Геостационарный метеоспутник, например Himawari', 'ดาวเทียมอุตุนิยมวิทยาค้างฟ้า เช่น Himawari'))],
    T('The ISS (about 420 km), Hubble (about 530 km) and Starlink (about 550 km) are in low orbit. GPS flies at about 20 200 km, a medium orbit; Himawari at 35 786 km, geostationary.',
      'МКС (около 420 км), «Хаббл» (около 530 км) и Starlink (около 550 км) — на низкой орбите. GPS летает на высоте около 20 200 км (средняя орбита), Himawari — на 35 786 км (геостационарная).',
      'ISS (ประมาณ 420 กม.) ฮับเบิล (ประมาณ 530 กม.) และ Starlink (ประมาณ 550 กม.) อยู่ในวงโคจรต่ำ GPS โคจรที่ประมาณ 20 200 กม. ซึ่งเป็นวงโคจรระดับกลาง ส่วน Himawari อยู่ที่ 35 786 กม. ในวงโคจรค้างฟ้า')),
  choice('b-forces-drag', 1, 1, K, 'rocket.forces',
    T('The diagram shows a rocket climbing through the air, and four forces on it. Which arrow is the aerodynamic drag? (The dashed line is the direction of flight, v.)', 'На схеме — ракета, набирающая высоту в атмосфере, и четыре силы, действующие на неё. Какая стрелка — сила лобового сопротивления? (Штриховая линия — направление скорости v.)', 'แผนภาพแสดงจรวดที่กำลังไต่ระดับผ่านอากาศและแรงสี่แรงที่กระทำต่อจรวด ลูกศรใดคือแรงต้านอากาศ (เส้นประคือทิศทางการเคลื่อนที่ v)'),
    letters('B'),
    T('Drag acts against the motion through the air, opposite v: arrow B. A is the thrust, along the rocket\'s axis; C the weight, straight down; D the aerodynamic normal force (lift), across the axis.',
      'Сила лобового сопротивления направлена против движения относительно воздуха, противоположно v: стрелка B. A — тяга вдоль оси ракеты, C — сила тяжести, вертикально вниз, D — нормальная аэродинамическая сила (подъёмная), поперёк оси.',
      'แรงต้านอากาศกระทำสวนทางกับการเคลื่อนที่ผ่านอากาศ ตรงข้ามกับ v คือลูกศร B ส่วน A คือแรงขับตามแนวแกนจรวด C คือน้ำหนักซึ่งชี้ลงตรง และ D คือแรงยกหรือแรงตั้งฉากทางอากาศพลศาสตร์ที่ตั้งฉากกับแกน'),
    { figure: diagram('forces'), fixedOrder: true }),
  choice('b-ellipse-slow', 1, 2, U, 'orbit.apsides',
    T('A satellite goes round the Earth on the orbit in the diagram. At which marked point does it move slowest?', 'Спутник движется вокруг Земли по орбите на схеме. В какой из отмеченных точек его скорость наименьшая?', 'ดาวเทียมโคจรรอบโลกตามวงโคจรในแผนภาพ ที่จุดใดซึ่งทำเครื่องหมายไว้ดาวเทียมเคลื่อนที่ช้าที่สุด'),
    letters('B', {
      A: T('Nearest the Earth gravity pulls hardest, so it must slow the satellite most there.', 'Ближе всего к Земле тяготение сильнее всего, значит, там оно сильнее всего тормозит спутник.', 'ใกล้โลกที่สุดแรงโน้มถ่วงแรงที่สุด จึงน่าจะทำให้ดาวเทียมช้าที่สุดตรงนั้น'),
      C: T('The orbit is flattest across its sides, so the satellite coasts slowest there.', 'По бокам орбита наиболее пологая, поэтому там спутник движется медленнее всего.', 'ด้านข้างของวงโคจรโค้งน้อยที่สุด ดาวเทียมจึงน่าจะเคลื่อนที่ช้าที่สุดตรงนั้น'),
    }),
    T('B is the apogee, the farthest point: climbing away from the Earth the satellite trades speed for height, so it is slowest at the top of its orbit and fastest at the perigee A (Kepler\'s second law: equal areas in equal times).',
      'B — апогей, наиболее удалённая точка: удаляясь от Земли, спутник расходует скорость на подъём, поэтому в верхней точке орбиты он медленнее всего, а в перигее A — быстрее всего (второй закон Кеплера: за равные времена — равные площади).',
      'B คือจุดไกลโลก ขณะเคลื่อนห่างจากโลก ดาวเทียมแลกความเร็วกับความสูง จึงช้าที่สุดที่จุดสูงสุดของวงโคจร และเร็วที่สุดที่จุดใกล้โลก A (กฎข้อที่สองของเคปเลอร์: กวาดพื้นที่เท่ากันในเวลาเท่ากัน)'),
    { figure: diagram('orbit-ellipse'), fixedOrder: true, lessons: ['orbit-hohmann'] }),
  choice('b-theos', 1, 1, K, 'history.thailand',
    T('THEOS (Thaichote), Thailand\'s first Earth-observation satellite, was launched in 2008 on which rocket?', 'На какой ракете в 2008 году был запущен THEOS («Тайчот»), первый тайский спутник наблюдения Земли?', 'THEOS (ไทยโชต) ดาวเทียมสำรวจโลกดวงแรกของไทย ถูกส่งขึ้นในปี 2008 ด้วยจรวดอะไร'),
    [O(T('Dnepr, a converted R-36M missile, from Yasny in Russia', '«Днепр», переоборудованная ракета Р-36М, с космодрома Ясный (Россия)', 'Dnepr ซึ่งดัดแปลงจากขีปนาวุธ R-36M ปล่อยจากฐานยัสนืยในรัสเซีย'), true),
      O(T('Ariane 5 from Kourou', 'Ariane 5 с космодрома Куру', 'Ariane 5 จากฐานคูรู')),
      O(T('Long March 2D from Jiuquan', '«Чанчжэн-2D» с космодрома Цзюцюань', 'Long March 2D จากฐานจิ่วเฉวียน')),
      O(T('Falcon 9 from Vandenberg', 'Falcon 9 с базы Ванденберг', 'Falcon 9 จากฐานแวนเดนเบิร์ก'))],
    T('THEOS flew on a Dnepr from Yasny (Dombarovsky) on 1 October 2008 into a sun-synchronous orbit about 820 km up. Its successor THEOS-2 was launched on a Vega from Kourou in October 2023.',
      'THEOS выведен ракетой «Днепр» с космодрома Ясный (Домбаровский) 1 октября 2008 г. на солнечно-синхронную орбиту высотой около 820 км. Его преемник THEOS-2 запущен ракетой Vega из Куру в октябре 2023 г.',
      'THEOS ขึ้นสู่อวกาศด้วยจรวด Dnepr จากฐานยัสนืย (ดอมบารอฟสกี) เมื่อ 1 ตุลาคม 2008 สู่วงโคจรสัมพันธ์กับดวงอาทิตย์สูงประมาณ 820 กม. ส่วนดาวเทียมรุ่นต่อมา THEOS-2 ถูกส่งด้วยจรวด Vega จากฐานคูรูเมื่อเดือนตุลาคม 2023')),
  choice('b-cosmodromes', 1, 2, K, 'launch.sites',
    T('Which of these launch sites lies farthest north?', 'Какой из этих космодромов расположен севернее всех?', 'ฐานปล่อยจรวดใดต่อไปนี้อยู่เหนือสุด'),
    [O(T('Plesetsk, 62.9° N', 'Плесецк, 62,9° с. ш.', 'เพลเซตสค์ 62.9° เหนือ'), true),
      O(T('Vostochny, 51.9° N', 'Восточный, 51,9° с. ш.', 'วอสตอชนืย 51.9° เหนือ')),
      O(T('Baikonur, 45.9° N', 'Байконур, 45,9° с. ш.', 'ไบโคนูร์ 45.9° เหนือ')),
      O(T('Kapustin Yar, 48.6° N', 'Капустин Яр, 48,6° с. ш.', 'คาปุสติน ยาร์ 48.6° เหนือ'))],
    T('Plesetsk, near Arkhangelsk, is the northernmost; a site\'s latitude is the lowest inclination it can reach directly, so Plesetsk launches to high-inclination, polar, sun-synchronous and Molniya orbits.',
      'Плесецк под Архангельском — самый северный; широта космодрома — наименьшее наклонение, достижимое прямым выведением, поэтому из Плесецка запускают на орбиты с большим наклонением: полярные, солнечно-синхронные, «Молния».',
      'เพลเซตสค์ใกล้เมืองอาร์คันเกลสค์อยู่เหนือสุด ละติจูดของฐานปล่อยคือความเอียงต่ำสุดที่ส่งขึ้นไปได้โดยตรง เพลเซตสค์จึงใช้ส่งดาวเทียมสู่วงโคจรความเอียงสูง วงโคจรขั้วโลก วงโคจรสัมพันธ์กับดวงอาทิตย์ และวงโคจรโมลนิยา'),
    { fixedOrder: true }),
  multi('b-multi-freefall', 1, 3, U, 'orbit.freefallWho',
    T('Which of these are in free fall, and so feel weightless? Choose every one.', 'Кто из них находится в свободном падении и потому испытывает невесомость? Выберите все.', 'ข้อใดอยู่ในสภาพตกอิสระ จึงรู้สึกไร้น้ำหนัก เลือกทุกข้อที่ถูก'),
    [O(T('The crew of the ISS', 'Экипаж МКС', 'ลูกเรือบน ISS'), true),
      O(T('A geostationary satellite', 'Геостационарный спутник', 'ดาวเทียมค้างฟ้า'), true),
      O(T('A spacecraft coasting to the Moon with its engines off', 'Космический корабль, летящий к Луне с выключенными двигателями', 'ยานอวกาศที่ปิดเครื่องยนต์และเคลื่อนที่ไปยังดวงจันทร์'), true),
      O(T('An astronaut standing on the Moon', 'Космонавт, стоящий на Луне', 'นักบินอวกาศที่ยืนอยู่บนดวงจันทร์'), false,
        T('Far from the Earth, on the Moon, there is no weight to feel.', 'Вдали от Земли, на Луне, веса нет.', 'บนดวงจันทร์ซึ่งอยู่ไกลจากโลกไม่มีน้ำหนักให้รู้สึก')),
      O(T('The crew of a rocket in powered flight above 100 km', 'Экипаж ракеты на активном участке выше 100 км', 'ลูกเรือในจรวดที่ยังจุดเครื่องยนต์อยู่ที่ความสูงเกิน 100 กม.'), false,
        T('Above the Kármán line everything is weightless.', 'Выше линии Кармана всё находится в невесомости.', 'เหนือเส้นคาร์มานทุกอย่างอยู่ในสภาพไร้น้ำหนัก'))],
    T('Weightlessness is free fall: nothing but gravity acts. The ISS crew, a GEO satellite and a coasting spacecraft all fall freely. On the Moon the ground pushes up (a sixth of the Earth\'s weight); in powered flight the thrust presses the crew into their seats, whatever the height.',
      'Невесомость — это свободное падение, когда действует только тяготение. Экипаж МКС, геостационарный спутник и корабль на пассивном участке падают свободно. На Луне опора давит вверх (вес — шестая часть земного), на активном участке тяга прижимает экипаж к креслам на любой высоте.',
      'สภาพไร้น้ำหนักคือการตกอิสระที่มีเพียงแรงโน้มถ่วงกระทำ ลูกเรือ ISS ดาวเทียมค้างฟ้า และยานที่ปิดเครื่องยนต์ล้วนตกอิสระ บนดวงจันทร์พื้นดันขึ้น (น้ำหนักหนึ่งในหกของบนโลก) ส่วนระหว่างจุดเครื่องยนต์ แรงขับกดลูกเรือแนบกับเบาะไม่ว่าจะสูงเท่าใด')),
];
