/** Area 5, attitude control (roadmap E03). */
import { K, O, T, U, choice, diagram, letters, multi, numeric, order } from './helpers';

export const CONTROL: readonly unknown[] = [
  choice('c-feedback', 5, 1, K, 'control.feedback',
    T('What makes a control system a feedback (closed-loop) system?', 'Что делает систему управления системой с обратной связью (замкнутой)?', 'อะไรทำให้ระบบควบคุมเป็นระบบป้อนกลับ (วงปิด)'),
    [O(T('It measures the output, compares it with the command, and acts on the difference', 'Она измеряет выходную величину, сравнивает её с заданной и действует по рассогласованию', 'วัดค่าเอาต์พุต เปรียบเทียบกับคำสั่ง แล้วสั่งการตามผลต่าง'), true),
      O(T('It follows a programme written before the flight, whatever happens', 'Она выполняет заранее записанную программу, что бы ни происходило', 'ทำตามโปรแกรมที่เขียนไว้ก่อนบินไม่ว่าจะเกิดอะไรขึ้น')),
      O(T('It has more than one computer', 'В ней больше одного вычислителя', 'มีคอมพิวเตอร์มากกว่าหนึ่งเครื่อง')),
      O(T('It uses hydraulic actuators', 'В ней используются гидравлические приводы', 'ใช้ตัวขับเร้าไฮดรอลิก'))],
    T('The loop: sensor → comparison with the command → controller → actuator → vehicle → sensor. It corrects disturbances the programme never foresaw — and can go unstable if tuned badly.',
      'Контур: датчик → сравнение с заданием → регулятор → привод → объект → датчик. Он парирует возмущения, которых программа не предусматривала, но при плохой настройке может потерять устойчивость.',
      'วงควบคุม: เซนเซอร์ → เปรียบเทียบกับคำสั่ง → ตัวควบคุม → ตัวขับเร้า → ยาน → เซนเซอร์ วงนี้แก้สิ่งรบกวนที่โปรแกรมไม่ได้คาดไว้ แต่ถ้าปรับไม่ดีก็อาจไม่เสถียร'),
    { lessons: ['ctl-inspector'] }),
  choice('c-tvc', 5, 1, K, 'control.actuators',
    T('How does a liquid-propellant launcher steer during powered flight?', 'Как управляется жидкостная ракета-носитель на активном участке?', 'จรวดนำส่งเชื้อเพลิงเหลวบังคับทิศทางอย่างไรขณะเครื่องยนต์ทำงาน'),
    [O(T('By swivelling (gimballing) its engines or steering chambers', 'Качанием двигателей или рулевых камер', 'ด้วยการหมุนปรับมุม (gimbal) เครื่องยนต์หรือห้องเผาไหม้บังคับทิศ'), true),
      O(T('With large tail fins only', 'Только большими хвостовыми рулями', 'ด้วยครีบหางขนาดใหญ่เท่านั้น')),
      O(T('By shifting its propellant from tank to tank', 'Перекачивая топливо между баками', 'ด้วยการสูบเชื้อเพลิงย้ายระหว่างถัง')),
      O(T('It cannot steer; it flies ballistically', 'Никак: он летит баллистически', 'บังคับไม่ได้ บินแบบขีปนวิถี'))],
    T('Tilting the thrust a few degrees off the axis makes a turning moment about the centre of mass. Soyuz steers with its vernier chambers, Falcon 9 and most modern rockets by gimballing their main engines.',
      'Отклонение вектора тяги на несколько градусов от оси создаёт управляющий момент относительно центра масс. «Союз» управляется рулевыми камерами, Falcon 9 и большинство современных ракет — качанием маршевых двигателей.',
      'การเอียงแรงขับออกจากแกนไม่กี่องศาทำให้เกิดโมเมนต์หมุนรอบศูนย์กลางมวล โซยุซบังคับด้วยห้องเผาไหม้บังคับทิศ ส่วน Falcon 9 และจรวดสมัยใหม่ส่วนใหญ่ใช้การปรับมุมเครื่องยนต์หลัก'),
    { lessons: ['ctl-margins'] }),
  choice('c-pid-d', 5, 1, K, 'control.pid',
    T('In a PID controller, what does the D (derivative) term act on?', 'На что реагирует дифференциальная (D) составляющая ПИД-регулятора?', 'ในตัวควบคุม PID พจน์ D (อนุพันธ์) ตอบสนองต่ออะไร'),
    [O(T('The rate of change of the error — it damps the motion', 'На скорость изменения рассогласования — демпфирует движение', 'อัตราการเปลี่ยนแปลงของความคลาด ทำหน้าที่หน่วงการเคลื่อนที่'), true),
      O(T('The error itself', 'На само рассогласование', 'ความคลาดโดยตรง')),
      O(T('The error summed over time', 'На накопленное рассогласование', 'ผลรวมของความคลาดตามเวลา')),
      O(T('The engine temperature', 'На температуру двигателя', 'อุณหภูมิของเครื่องยนต์'))],
    T('P pushes back in proportion to the error, I removes a steady offset by accumulating it, D resists motion. On a rocket the D term uses the gyros\' rate directly.',
      'P противодействует пропорционально рассогласованию, I устраняет статическую ошибку, накапливая её, D препятствует движению. На ракете D-составляющая берётся прямо от ДУС.',
      'P ดันกลับตามขนาดความคลาด I กำจัดความคลาดค้างด้วยการสะสม และ D ต้านการเคลื่อนที่ บนจรวดพจน์ D ใช้อัตราจากไจโรโดยตรง'),
    { lessons: ['ctl-margins'] }),
  choice('c-rcs', 5, 1, K, 'control.actuators',
    T('When does a spacecraft need reaction control thrusters (RCS) to control its attitude?', 'Когда аппарату для управления ориентацией нужны реактивные двигатели ориентации?', 'ยานอวกาศต้องใช้ไอพ่นควบคุมท่าทาง (RCS) เมื่อใด'),
    [O(T('When the main engine is off, or cannot give a moment about some axis', 'Когда маршевый двигатель выключен или не может дать момент по какой-либо оси', 'เมื่อเครื่องยนต์หลักดับ หรือไม่สามารถให้โมเมนต์รอบแกนใดแกนหนึ่งได้'), true),
      O(T('Only while it is in the atmosphere', 'Только в атмосфере', 'เฉพาะเมื่ออยู่ในบรรยากาศ')),
      O(T('Only at lift-off', 'Только на старте', 'เฉพาะตอนออกตัว')),
      O(T('Never: the gyroscopes hold the attitude by themselves', 'Никогда: гироскопы сами держат ориентацию', 'ไม่ต้องใช้ ไจโรสโคปรักษาท่าทางไว้เอง'))],
    T('During coasts there is no thrust to tilt, so small thrusters fire in pairs to turn the vehicle. A single gimballed engine also cannot roll the vehicle; its roll needs thrusters or a second chamber.',
      'На пассивных участках отклонять нечего, и аппарат разворачивают малые двигатели, работающие парами. Один качающийся двигатель к тому же не создаёт момента по крену — для крена нужны двигатели ориентации или вторая камера.',
      'ระหว่างช่วงไร้แรงขับไม่มีแรงขับให้เอียง จึงต้องใช้ไอพ่นเล็กจุดเป็นคู่เพื่อหมุนยาน เครื่องยนต์ปรับมุมเครื่องเดียวยังหมุนยานรอบแกนโรลไม่ได้ ต้องใช้ไอพ่นหรือห้องเผาไหม้ที่สอง')),
  choice('c-unstable-simple', 5, 1, U, 'control.stability',
    T('A launcher\'s centre of pressure lies ahead of its centre of mass. Without active control, what happens?', 'Центр давления ракеты расположен впереди центра масс. Что произойдёт без активного управления?', 'ศูนย์กลางความดันของจรวดอยู่หน้าศูนย์กลางมวล หากไม่มีการควบคุม จะเกิดอะไรขึ้น'),
    [O(T('Any small angle of attack grows: the rocket turns sideways and breaks up', 'Любой малый угол атаки растёт: ракета разворачивается боком и разрушается', 'มุมปะทะเล็ก ๆ ใด ๆ จะโตขึ้น จรวดหันข้างและแตกหัก'), true),
      O(T('Nothing: the air keeps it pointing forward, like an arrow', 'Ничего: воздух держит её носом вперёд, как стрелу', 'ไม่มีอะไร อากาศทำให้หัวชี้ไปข้างหน้าเหมือนลูกศร'), false,
        T('a rocket is stable like an arrow whatever its shape', 'ракета устойчива, как стрела, при любой форме', 'จรวดเสถียรเหมือนลูกศรเสมอไม่ว่าจะมีรูปทรงใด')),
      O(T('It spins about its long axis', 'Она закрутится вокруг продольной оси', 'จรวดหมุนรอบแกนยาว')),
      O(T('It slows down', 'Она замедлится', 'จรวดช้าลง'))],
    T('An arrow is stable because its feathers put the centre of pressure behind the centre of mass. Most launchers have no fins, so the aerodynamic moment amplifies any angle: they are statically unstable and the autopilot keeps them straight.',
      'Стрела устойчива, потому что оперение смещает центр давления за центр масс. У большинства носителей нет стабилизаторов, аэродинамический момент увеличивает любой угол: ракета статически неустойчива, и её удерживает автомат стабилизации.',
      'ลูกศรเสถียรเพราะขนนกทำให้ศูนย์กลางความดันอยู่หลังศูนย์กลางมวล จรวดนำส่งส่วนใหญ่ไม่มีครีบ โมเมนต์ทางอากาศพลศาสตร์จึงขยายมุมใด ๆ ให้โตขึ้น จรวดจึงไม่เสถียรเชิงสถิตและต้องให้ระบบนำร่องอัตโนมัติรักษาไว้'),
    { lessons: ['ctl-inspector'] }),
  choice('c-phase-margin', 5, 2, U, 'control.margins',
    T('An attitude loop has a phase margin of only 10°. What will a step command look like?', 'Запас устойчивости контура по фазе всего 10°. Как будет выглядеть реакция на ступенчатое воздействие?', 'วงควบคุมท่าทางมีค่าเผื่อเฟสเพียง 10° การตอบสนองต่อคำสั่งแบบขั้นจะเป็นอย่างไร'),
    [O(T('Badly oscillatory, with a large overshoot, close to instability', 'Сильно колебательная, с большим перерегулированием, на грани неустойчивости', 'แกว่งมาก พุ่งเกินสูง ใกล้ความไม่เสถียร'), true),
      O(T('Slow and smooth, with no overshoot', 'Медленная и плавная, без перерегулирования', 'ช้าและราบเรียบ ไม่มีการพุ่งเกิน'), false,
        T('a small phase margin makes a loop sluggish', 'малый запас по фазе делает контур вялым', 'ค่าเผื่อเฟสน้อยทำให้วงอืด')),
      O(T('Exactly like one with a 60° margin', 'Точно такая же, как при запасе 60°', 'เหมือนกับที่ค่าเผื่อ 60° ทุกประการ')),
      O(T('It will not respond at all', 'Реакции не будет вовсе', 'ไม่ตอบสนองเลย'))],
    T('Phase margin is how far the loop\'s phase is from −180° where its gain is one. A small margin means a lightly damped closed loop (ζ ≈ PM/100 as a rule of thumb). 30–60° is a usual design target.',
      'Запас по фазе — насколько фаза разомкнутого контура отстоит от −180° на частоте среза. Малый запас означает слабое демпфирование замкнутого контура (по грубому правилу ζ ≈ ЗФ/100). Обычно проектируют на 30–60°.',
      'ค่าเผื่อเฟสคือเฟสของวงห่างจาก −180° เท่าใด ณ ความถี่ที่อัตราขยายเท่ากับหนึ่ง ค่าเผื่อน้อยหมายถึงวงปิดที่หน่วงน้อย (โดยประมาณ ζ ≈ PM/100) โดยทั่วไปออกแบบไว้ 30–60°'),
    { lessons: ['ctl-margins', 'ctl-step'] }),
  choice('c-gain-margin', 5, 2, K, 'control.margins',
    T('A gain margin of 6 dB means that…', 'Запас устойчивости по амплитуде 6 дБ означает, что…', 'ค่าเผื่อเกน 6 dB หมายความว่า…'),
    [O(T('…the loop gain could double before the loop goes unstable', '…коэффициент усиления контура можно удвоить, прежде чем он потеряет устойчивость', '…อัตราขยายของวงเพิ่มได้สองเท่าก่อนวงจะไม่เสถียร'), true),
      O(T('…the gain could rise six times', '…усиление можно увеличить в шесть раз', '…อัตราขยายเพิ่มได้หกเท่า')),
      O(T('…the output is 6 % above the command', '…выход на 6 % превышает задание', '…เอาต์พุตสูงกว่าคำสั่ง 6 %')),
      O(T('…the phase can lag 6° more', '…фаза может запаздывать ещё на 6°', '…เฟสล้าหลังเพิ่มได้อีก 6°'))],
    T('20·log10(2) = 6.02 dB. Gain margin is measured where the phase crosses −180°; on an aerodynamically unstable rocket there is also a lower margin — how far the gain may fall.',
      '20·lg 2 = 6,02 дБ. Запас по амплитуде измеряют там, где фаза проходит −180°; у аэродинамически неустойчивой ракеты есть ещё нижний запас — насколько можно уменьшить усиление.',
      '20·log10(2) = 6.02 dB ค่าเผื่อเกนวัดที่เฟสตัด −180° สำหรับจรวดที่ไม่เสถียรทางอากาศพลศาสตร์ยังมีค่าเผื่อด้านล่างด้วย คืออัตราขยายลดลงได้เท่าใด'),
    { lessons: ['ctl-margins'] }),
  choice('c-more-gain', 5, 2, U, 'control.tuning',
    T('You raise the proportional (attitude) gain of an autopilot a lot. What usually happens?', 'Вы сильно увеличили коэффициент по углу в автомате стабилизации. Что обычно происходит?', 'คุณเพิ่มเกนสัดส่วน (มุม) ของระบบนำร่องอัตโนมัติขึ้นมาก โดยทั่วไปจะเกิดอะไรขึ้น'),
    [O(T('It responds faster but with more overshoot and less margin', 'Реакция становится быстрее, но перерегулирование больше, а запасы меньше', 'ตอบสนองเร็วขึ้น แต่พุ่งเกินมากขึ้นและค่าเผื่อลดลง'), true),
      O(T('It becomes both faster and better damped', 'Она становится и быстрее, и лучше задемпфирована', 'ทั้งเร็วขึ้นและหน่วงดีขึ้น'), false,
        T('more gain is better in every way', 'большее усиление лучше во всём', 'เกนที่มากขึ้นดีกว่าในทุกด้าน')),
      O(T('It becomes slower', 'Она становится медленнее', 'ตอบสนองช้าลง')),
      O(T('Nothing changes: the gain only scales the display', 'Ничего: коэффициент лишь масштабирует индикацию', 'ไม่มีอะไรเปลี่ยน เกนแค่ปรับสเกลการแสดงผล'))],
    T('More gain pushes the crossover up in frequency, where the actuator and the sensor lags eat phase: the loop gets quicker and less damped. The rate (D) gain buys the damping back, up to the bending and noise limits.',
      'Большее усиление сдвигает частоту среза вверх, где запаздывания привода и датчиков «съедают» фазу: контур становится быстрее, но хуже задемпфирован. Демпфирование возвращают коэффициентом по угловой скорости — до ограничений по упругим колебаниям и шуму.',
      'เกนที่มากขึ้นดันความถี่ครอสโอเวอร์ขึ้นไปในย่านที่ความหน่วงของตัวขับเร้าและเซนเซอร์กินเฟส วงจึงเร็วขึ้นแต่หน่วงน้อยลง เกนอัตรา (D) ช่วยซื้อการหน่วงคืน จนถึงขีดจำกัดของการโค้งงอและสัญญาณรบกวน'),
    { lessons: ['ctl-margins'] }),
  choice('c-crossover', 5, 2, K, 'control.bode',
    T('On a Bode plot of an open loop, the crossover frequency is where…', 'На ЛАЧХ разомкнутого контура частота среза — это частота, где…', 'บนแผนภาพโบดของวงเปิด ความถี่ครอสโอเวอร์คือความถี่ที่…'),
    [O(T('…the loop\'s gain equals 1 (0 dB)', '…усиление контура равно 1 (0 дБ)', '…อัตราขยายของวงเท่ากับ 1 (0 dB)'), true),
      O(T('…the phase equals −180°', '…фаза равна −180°', '…เฟสเท่ากับ −180°')),
      O(T('…the gain is greatest', '…усиление максимально', '…อัตราขยายสูงสุด')),
      O(T('…the bending mode rings', '…звучит упругий тон', '…โหมดการโค้งงอสั่นก้อง'))],
    T('ω_c sets roughly how fast the closed loop responds; the phase margin is read there, the gain margin where the phase is −180°.',
      'ω_ср примерно определяет быстродействие замкнутого контура; на ней отсчитывают запас по фазе, а запас по амплитуде — там, где фаза равна −180°.',
      'ω_c กำหนดความเร็วในการตอบสนองของวงปิดโดยประมาณ ค่าเผื่อเฟสอ่านที่ความถี่นี้ ส่วนค่าเผื่อเกนอ่านที่เฟสเท่ากับ −180°'),
    { lessons: ['ctl-inspector'] }),
  choice('c-notch', 5, 2, U, 'control.flex',
    T('Why does the autopilot of a long, flexible launcher carry a notch filter?', 'Зачем автомату стабилизации длинной упругой ракеты режекторный фильтр?', 'ทำไมระบบนำร่องอัตโนมัติของจรวดที่ยาวและยืดหยุ่นจึงต้องมีตัวกรองน็อตช์'),
    [O(T('To keep the gyros\' reading of the bending vibration out of the loop, so it is not fed back and amplified', 'Чтобы показания ДУС, вызванные упругими колебаниями, не попадали в контур и не раскачивали их', 'เพื่อกันค่าจากไจโรที่เกิดจากการสั่นแบบโค้งงอไม่ให้เข้าวงควบคุม ไม่ให้ถูกป้อนกลับและขยาย'), true),
      O(T('To remove the engines\' noise from the telemetry', 'Чтобы убрать шум двигателей из телеметрии', 'เพื่อตัดเสียงรบกวนจากเครื่องยนต์ออกจากโทรมาตร')),
      O(T('To make the rocket stiffer', 'Чтобы сделать ракету жёстче', 'เพื่อทำให้จรวดแข็งขึ้น'), false,
        T('a filter in the software changes the structure itself', 'программный фильтр меняет саму конструкцию', 'ตัวกรองในซอฟต์แวร์เปลี่ยนตัวโครงสร้างได้')),
      O(T('To filter the radio link to the ground', 'Чтобы фильтровать радиолинию с Землёй', 'เพื่อกรองสัญญาณวิทยุกับภาคพื้น'))],
    T('A gyro on a bending body measures the local rotation of the structure as well as the rigid body\'s. If the loop reacts to it at the mode\'s frequency with the wrong phase, it pumps energy in. A notch cuts the gain there.',
      'ДУС на упругом корпусе измеряет, кроме вращения твёрдого тела, местный поворот конструкции. Если контур отрабатывает его на частоте тона с неблагоприятной фазой, он раскачивает колебания. Режекторный фильтр снижает усиление на этой частоте.',
      'ไจโรที่ติดบนตัวยานที่โค้งงอวัดการหมุนเฉพาะที่ของโครงสร้างด้วย นอกเหนือจากการหมุนของวัตถุแข็งเกร็ง ถ้าวงควบคุมตอบสนองต่อสัญญาณนี้ที่ความถี่ของโหมดด้วยเฟสที่ผิด จะเป็นการอัดพลังงานเข้าไป ตัวกรองน็อตช์ตัดอัตราขยายที่ความถี่นั้น'),
    { lessons: ['ctl-notch'] }),
  choice('c-step-terms', 5, 2, K, 'control.step',
    T('In a step response, what is the overshoot?', 'Что такое перерегулирование в переходной характеристике?', 'ในการตอบสนองแบบขั้น ค่าพุ่งเกิน (overshoot) คืออะไร'),
    [O(T('How far the response goes past its final value, as a percentage of the step', 'На сколько процентов от величины ступени реакция превышает установившееся значение', 'ระยะที่การตอบสนองเลยค่าสุดท้ายไป คิดเป็นร้อยละของขนาดขั้น'), true),
      O(T('The time to reach the final value', 'Время выхода на установившееся значение', 'เวลาที่ใช้ไปถึงค่าสุดท้าย')),
      O(T('The final error left after the response settles', 'Установившаяся ошибка', 'ความคลาดที่เหลือหลังการตอบสนองเข้าที่')),
      O(T('The delay before the response starts', 'Задержка до начала реакции', 'ความหน่วงก่อนเริ่มตอบสนอง'))],
    T('Overshoot is the peak above the final value, in % of the step; the settling time is when the response stays within a band (often 2 or 5 %) of it.',
      'Перерегулирование — превышение пика над установившимся значением в процентах от ступени; время регулирования — момент, после которого реакция остаётся в пределах заданной зоны (обычно 2 или 5 %).',
      'ค่าพุ่งเกินคือส่วนที่ยอดสูงกว่าค่าสุดท้าย เป็นร้อยละของขนาดขั้น เวลาเข้าที่ (settling time) คือเวลาที่การตอบสนองอยู่ในแถบรอบค่าสุดท้าย (มักเป็น 2 หรือ 5 %) ตลอดไป'),
    { lessons: ['ctl-step'] }),
  choice('c-tvc-sign', 5, 2, U, 'control.actuators',
    T('The nozzle of a launcher is swivelled so that its thrust points slightly to the left of the axis. Which way does the nose turn?', 'Сопло ракеты отклонено так, что тяга направлена немного влево от оси. Куда повернётся нос?', 'หัวฉีดของจรวดถูกปรับจนแรงขับชี้ไปทางซ้ายของแกนเล็กน้อย หัวจรวดจะหันไปทางใด'),
    [O(T('To the right: the tail is pushed left, and the vehicle turns about its centre of mass', 'Вправо: хвост уводится влево, и ракета поворачивается вокруг центра масс', 'ไปทางขวา เพราะหางถูกดันไปทางซ้าย และจรวดหมุนรอบศูนย์กลางมวล'), true),
      O(T('To the left, the way the thrust points', 'Влево, куда направлена тяга', 'ไปทางซ้าย ตามทิศที่แรงขับชี้'), false,
        T('the nose follows the direction of the thrust', 'нос следует за направлением тяги', 'หัวจรวดหันตามทิศของแรงขับ')),
      O(T('It does not turn; it slides sideways', 'Не поворачивается, а смещается вбок', 'ไม่หัน แต่เลื่อนไปด้านข้าง')),
      O(T('It rolls about its long axis', 'Поворачивается вокруг продольной оси', 'หมุนรอบแกนยาว'))],
    T('The thrust acts at the tail, far behind the centre of mass: pushing the tail to the left turns the nose to the right — the same way a car\'s rear wheels would steer it.',
      'Тяга приложена к хвосту, далеко за центром масс: хвост уходит влево, и нос поворачивается вправо — как если бы автомобиль рулил задними колёсами.',
      'แรงขับกระทำที่ท้ายซึ่งอยู่หลังศูนย์กลางมวลมาก การดันท้ายไปทางซ้ายจึงทำให้หัวหันไปทางขวา เหมือนรถที่เลี้ยวด้วยล้อหลัง')),
  numeric('c-overshoot', 5, 3, K, 'control.step',
    T('A second-order loop has a damping ratio ζ = {z}. Work out the overshoot of its step response (%).', 'Контур второго порядка имеет относительный коэффициент демпфирования ζ = {z}. Рассчитайте перерегулирование переходной характеристики (%).', 'วงควบคุมอันดับสองมีอัตราส่วนการหน่วง ζ = {z} คำนวณค่าพุ่งเกินของการตอบสนองแบบขั้น (%)'),
    [{ name: 'z', min: 0.15, max: 0.8, step: 0.05 }], '100 * exp(-pi * z / sqrt(1 - z^2))', '%', 3,
    T('Mp = exp(−πζ/√(1−ζ²)): 0.2 gives 53 %, 0.5 gives 16 %, 0.7 gives 4.6 %.', 'σ = exp(−πζ/√(1−ζ²)): при 0,2 — 53 %, при 0,5 — 16 %, при 0,7 — 4,6 %.', 'Mp = exp(−πζ/√(1−ζ²)) ที่ 0.2 ได้ 53 %, 0.5 ได้ 16 %, 0.7 ได้ 4.6 %'),
    { lessons: ['ctl-step'] }),
  numeric('c-gain-db', 5, 3, K, 'control.margins',
    T('The loop gain can be raised {k} times before the loop goes unstable. Express the gain margin in decibels (dB).', 'Усиление контура можно увеличить в {k} раза, прежде чем он потеряет устойчивость. Выразите запас по амплитуде в децибелах (дБ).', 'อัตราขยายของวงเพิ่มได้ {k} เท่าก่อนที่วงจะไม่เสถียร จงแสดงค่าเผื่อเกนเป็นเดซิเบล (dB)'),
    [{ name: 'k', min: 1.2, max: 5, step: 0.1 }], '20 * log10(k)', 'dB', 2,
    T('GM = 20·log10(k): ×2 is 6.0 dB, ×3 is 9.5 dB.', 'ЗА = 20·lg k: ×2 — 6,0 дБ, ×3 — 9,5 дБ.', 'GM = 20·log10(k) ×2 เท่ากับ 6.0 dB ×3 เท่ากับ 9.5 dB'),
    { lessons: ['ctl-margins'] }),
  numeric('c-delay-phase', 5, 3, K, 'control.margins',
    T('A pure time delay of {tau} ms sits in an attitude loop whose crossover is {w} rad/s. How much phase margin does the delay cost (°)?', 'В контуре угловой стабилизации с частотой среза {w} рад/с есть чистое запаздывание {tau} мс. Сколько запаса по фазе оно отнимает (°)?', 'วงควบคุมท่าทางที่มีความถี่ครอสโอเวอร์ {w} rad/s มีความหน่วงเวลาบริสุทธิ์ {tau} ms ความหน่วงนี้ทำให้เสียค่าเผื่อเฟสเท่าใด (°)'),
    [{ name: 'tau', min: 10, max: 100, step: 5 }, { name: 'w', min: 1, max: 6, step: 0.5 }], 'w * tau / 1000 * 180 / pi', '°', 2,
    T('A delay τ lags the phase by ω·τ radians at every frequency and leaves the gain alone: at the crossover it comes straight off the phase margin.',
      'Запаздывание τ на любой частоте даёт отставание фазы ω·τ радиан, не меняя усиления, — на частоте среза оно целиком вычитается из запаса по фазе.',
      'ความหน่วง τ ทำให้เฟสล้าหลัง ω·τ เรเดียนที่ทุกความถี่โดยไม่เปลี่ยนอัตราขยาย ที่ความถี่ครอสโอเวอร์จึงหักออกจากค่าเผื่อเฟสทั้งหมด'),
    { lessons: ['ctl-margins'] }),
  choice('c-maxq-margins', 5, 3, U, 'control.stability',
    T('Why are an autopilot\'s stability margins usually tightest near max-Q?', 'Почему запасы устойчивости автомата стабилизации обычно наименьшие в районе максимального напора?', 'ทำไมค่าเผื่อเสถียรภาพของระบบนำร่องอัตโนมัติจึงมักแคบที่สุดช่วง max-Q'),
    [O(T('The destabilising aerodynamic moment is largest there, so the loop has the most to hold', 'Там максимален дестабилизирующий аэродинамический момент, и контуру труднее всего', 'ที่นั่นโมเมนต์ทางอากาศพลศาสตร์ที่ทำให้ไม่เสถียรมีค่ามากที่สุด วงจึงต้องรับมือมากที่สุด'), true),
      O(T('The engines are throttled down, so there is less control authority', 'Двигатели задросселированы, и управляющих усилий меньше', 'เครื่องยนต์ลดแรงขับ อำนาจควบคุมจึงน้อยลง'), false,
        T('the margins shrink only because the thrust falls', 'запасы уменьшаются лишь из-за снижения тяги', 'ค่าเผื่อลดลงเพียงเพราะแรงขับลดลง')),
      O(T('The gyros are least accurate at that speed', 'На этой скорости ДУС наименее точны', 'ไจโรแม่นยำน้อยที่สุดที่ความเร็วนั้น')),
      O(T('Because the propellant is sloshing most', 'Потому что сильнее всего колеблется топливо', 'เพราะเชื้อเพลิงกระฉอกมากที่สุด'))],
    T('The aerodynamic instability grows with q: the moment coefficient μα ∝ q·S·(x_cp − x_cm)/I. At its peak the loop must be fastest just to hold the vehicle, and the margins it has left are at their least.',
      'Аэродинамическая неустойчивость растёт с q: коэффициент момента пропорционален q·S·(xд − xт)/I. На пике контур должен быть наиболее быстрым только для того, чтобы удержать ракету, и оставшиеся запасы наименьшие.',
      'ความไม่เสถียรทางอากาศพลศาสตร์เพิ่มตาม q โดยสัมประสิทธิ์โมเมนต์แปรตาม q·S·(x_cp − x_cm)/I ที่ค่าสูงสุด วงควบคุมต้องเร็วที่สุดเพียงเพื่อประคองยาน ค่าเผื่อที่เหลือจึงน้อยที่สุด'),
    { lessons: ['ctl-inspector', 'ctl-margins'] }),
  choice('c-slosh', 5, 3, K, 'control.flex',
    T('Propellant slosh in a partly empty tank matters to the attitude loop because…', 'Колебания жидкого топлива в частично опорожнённом баке важны для контура стабилизации, потому что…', 'การกระฉอกของเชื้อเพลิงในถังที่ว่างบางส่วนมีผลต่อวงควบคุมท่าทาง เพราะ…'),
    [O(T('…the moving liquid acts like a pendulum coupled to the vehicle, adding a low-frequency mode', '…движущаяся жидкость действует как маятник, связанный с корпусом, и добавляет низкочастотный тон', '…ของเหลวที่เคลื่อนไหวทำตัวเหมือนลูกตุ้มที่ต่ออยู่กับยาน เพิ่มโหมดความถี่ต่ำเข้ามา'), true),
      O(T('…it changes the engine\'s specific impulse', '…оно меняет удельный импульс двигателя', '…เปลี่ยนแรงดลจำเพาะของเครื่องยนต์')),
      O(T('…it heats the tank walls', '…оно нагревает стенки бака', '…ทำให้ผนังถังร้อน')),
      O(T('…it only matters on the pad', '…оно важно только на старте', '…มีผลเฉพาะบนแท่นปล่อย'))],
    T('Slosh modes sit near the rigid-body crossover, where a notch cannot simply cut them out; tanks carry baffles to damp them, and the autopilot is tuned to stay phase-stable with them.',
      'Тоны колебаний топлива лежат вблизи частоты среза твёрдого тела, где их нельзя просто вырезать фильтром; в баках ставят демпфирующие перегородки, а автомат настраивают на фазовую устойчивость с учётом этих тонов.',
      'โหมดการกระฉอกอยู่ใกล้ความถี่ครอสโอเวอร์ของวัตถุแข็งเกร็ง จึงใช้ตัวกรองตัดออกง่าย ๆ ไม่ได้ ถังจึงมีแผ่นกั้นเพื่อหน่วง และระบบนำร่องถูกปรับให้เสถียรเชิงเฟสกับโหมดเหล่านี้'),
    { lessons: ['ctl-notch'] }),
  numeric('c-read-overshoot', 5, 2, K, 'control.stepRead',
    T('The chart is an attitude loop\'s response to a step command (y / y∞: the output over its final value). Read its overshoot (%).', 'На графике — переходная характеристика контура управления ориентацией (y / y∞ — выход, отнесённый к установившемуся значению). Определите перерегулирование (%).', 'กราฟคือผลตอบสนองต่อคำสั่งแบบขั้นบันไดของลูปควบคุมท่าทาง (y / y∞ คือเอาต์พุตหารด้วยค่าสุดท้าย) อ่านค่าโอเวอร์ชูต (%)'),
    [{ name: 'z', min: 0.2, max: 0.5, step: 0.05 }], '100 * exp(-pi * z / sqrt(1 - z^2))', '%', 12,
    T('The overshoot is how far the first peak goes past the final value, as a share of it: a peak at 1.25 is 25%. For a second-order loop it depends only on the damping ratio, e^(−πζ/√(1−ζ²)).',
      'Перерегулирование — насколько первый максимум превышает установившееся значение, в долях от него: максимум 1,25 — это 25 %. Для звена второго порядка оно зависит только от коэффициента демпфирования: e^(−πζ/√(1−ζ²)).',
      'โอเวอร์ชูตคือยอดแรกเกินค่าสุดท้ายไปเท่าใด คิดเป็นสัดส่วนของค่าสุดท้าย ยอดที่ 1.25 คือ 25% สำหรับระบบอันดับสอง ค่านี้ขึ้นกับอัตราส่วนความหน่วงเท่านั้น e^(−πζ/√(1−ζ²))'),
    { figure: diagram('step-response'), lessons: ['ctl-step'] }),
  numeric('c-read-pm', 5, 3, K, 'control.bodeRead',
    T('The Bode plot of an attitude loop\'s open loop: L its magnitude, φ its phase. Read its phase margin (°).', 'ЛАЧХ (L) и ЛФЧХ (φ) разомкнутого контура управления ориентацией. Определите запас по фазе (°).', 'Bode plot ของลูปเปิดของระบบควบคุมท่าทาง L คือขนาด φ คือเฟส อ่านค่าเฟสมาร์จิน (°)'),
    [{ name: 'K', min: 1, max: 8, step: 0.5 }], '90 - atan(0.5 * sqrt(2 * (sqrt(1 + K^2) - 1)))', '°', 12,
    T('Find the crossover, where the magnitude crosses 0 dB; read the phase there; the phase margin is how far it is above −180°. A loop needs about 30–60° of it.',
      'Найдите частоту среза, где ЛАЧХ пересекает 0 дБ; определите фазу на этой частоте; запас по фазе — на сколько она выше −180°. Контуру нужно около 30–60°.',
      'หาความถี่ครอสโอเวอร์ที่ขนาดตัด 0 dB แล้วอ่านเฟสที่ความถี่นั้น เฟสมาร์จินคือเฟสสูงกว่า −180° เท่าใด ลูปควรมีประมาณ 30–60°'),
    { figure: diagram('bode'), lessons: ['ctl-margins'] }),
  choice('c-step-compare', 5, 2, U, 'control.dampingCompare',
    T('Three attitude loops answer the same step command (A, B, C). Which has the smallest phase margin?', 'Три контура управления ориентацией отрабатывают одну и ту же ступенчатую команду (A, B, C). У какого наименьший запас по фазе?', 'ลูปควบคุมท่าทางสามลูปตอบสนองต่อคำสั่งขั้นบันไดเดียวกัน (A, B, C) ลูปใดมีเฟสมาร์จินน้อยที่สุด'),
    letters('B', {
      A: T('The slowest response is the least stable one.', 'Самая медленная реакция — самая неустойчивая.', 'ผลตอบสนองที่ช้าที่สุดคือเสถียรน้อยที่สุด'),
    }, ['A', 'B', 'C']),
    T('Small phase margin shows as a large, slowly dying oscillation: B rings most. A is well damped (slow, but not unstable); C is in between. For a second-order loop, a phase margin of about 100·ζ degrees (up to ζ ≈ 0.7) is a handy rule.',
      'Малый запас по фазе проявляется как большие, медленно затухающие колебания: сильнее всех колеблется B. A хорошо задемпфирован (медленный, но не неустойчивый); C — промежуточный. Для звена второго порядка удобное правило: запас по фазе около 100·ζ градусов (до ζ ≈ 0,7).',
      'เฟสมาร์จินน้อยแสดงออกเป็นการแกว่งใหญ่ที่ลดลงช้า B แกว่งมากที่สุด A หน่วงดี (ช้าแต่ไม่ได้ไม่เสถียร) C อยู่ระหว่างกลาง สำหรับระบบอันดับสอง มีกฎง่าย ๆ ว่าเฟสมาร์จินประมาณ 100·ζ องศา (จนถึง ζ ≈ 0.7)'),
    { figure: diagram('step-compare'), fixedOrder: true, lessons: ['ctl-step'] }),
  multi('c-multi-actuators', 5, 1, K, 'control.actuatorKinds',
    T('Which of these are actuators a vehicle can turn itself with? Choose every one.', 'Какие из них — исполнительные органы, которыми аппарат может поворачивать себя? Выберите все.', 'ข้อใดเป็นอุปกรณ์ขับเร้า (actuator) ที่ยานใช้หมุนตัวเองได้ เลือกทุกข้อที่ถูก'),
    [O(T('A gimballed engine nozzle (thrust vector control)', 'Качающееся сопло двигателя (управление вектором тяги)', 'หัวฉีดเครื่องยนต์ที่หมุนได้ (การควบคุมทิศแรงขับ)'), true),
      O(T('Reaction control thrusters', 'Двигатели ориентации', 'ทรัสเตอร์ควบคุมท่าทาง'), true),
      O(T('Reaction wheels', 'Маховики (двигатели-маховики)', 'วงล้อปฏิกิริยา'), true),
      O(T('Rate gyros', 'Датчики угловой скорости', 'ไจโรวัดอัตรา')),
      O(T('A star tracker', 'Звёздный датчик', 'ตัวติดตามดาว'))],
    T('Actuators make torques: a swivelled nozzle, thrusters, wheels (and grid fins or control surfaces in the air). Gyros and star trackers are sensors: they tell the loop where the vehicle points, they cannot turn it.',
      'Исполнительные органы создают моменты: качающееся сопло, двигатели ориентации, маховики (и решётчатые рули или аэродинамические поверхности в атмосфере). Гироскопы и звёздные датчики — измерители: они сообщают контуру ориентацию, но повернуть аппарат не могут.',
      'อุปกรณ์ขับเร้าสร้างแรงบิด ได้แก่ หัวฉีดที่หมุนได้ ทรัสเตอร์ วงล้อ (และครีบกริดหรือพื้นบังคับในอากาศ) ไจโรและตัวติดตามดาวเป็นเซนเซอร์ บอกลูปว่ายานชี้ไปทางใด แต่หมุนยานไม่ได้')),
  order('c-order-loop', 5, 1, K, 'control.loopOrder',
    T('Follow a signal once round a launcher\'s attitude loop. Put the steps in order, from the guidance\'s command.', 'Проследите сигнал по контуру управления ориентацией ракеты. Расположите шаги по порядку, начиная с команды системы наведения.', 'ติดตามสัญญาณหนึ่งรอบของลูปควบคุมท่าทางของจรวด เรียงลำดับขั้นตอนโดยเริ่มจากคำสั่งของระบบนำวิถี'),
    [T('The guidance commands an attitude', 'Система наведения задаёт ориентацию', 'ระบบนำวิถีสั่งท่าทาง'),
      T('The error is formed: command minus measured attitude', 'Формируется рассогласование: команда минус измеренная ориентация', 'สร้างค่าความคลาดเคลื่อน: คำสั่งลบท่าทางที่วัดได้'),
      T('The autopilot\'s control law works out a nozzle angle', 'Закон управления автомата стабилизации вычисляет угол сопла', 'กฎควบคุมของออโตไพลอตคำนวณมุมหัวฉีด'),
      T('The actuator swivels the nozzle', 'Рулевой привод поворачивает сопло', 'ตัวขับเร้าหมุนหัวฉีด'),
      T('The vehicle turns, and the IMU measures its new attitude', 'Аппарат поворачивается, ИИБ измеряет новую ориентацию', 'ยานหมุน และ IMU วัดท่าทางใหม่')],
    T('That last measurement closes the loop: it feeds the next error. Every block on the way adds a delay or a lag, and the sum of them is what the phase margin must cover.',
      'Последнее измерение замыкает контур: оно входит в следующее рассогласование. Каждое звено на этом пути добавляет запаздывание, и их сумму должен покрывать запас по фазе.',
      'การวัดสุดท้ายนี้ปิดลูป เพราะป้อนเข้าไปเป็นค่าความคลาดเคลื่อนถัดไป ทุกบล็อกระหว่างทางเพิ่มความหน่วงหรือความล่าช้า และผลรวมของสิ่งเหล่านี้คือสิ่งที่เฟสมาร์จินต้องครอบคลุม'),
    { lessons: ['ctl-inspector'] }),
  multi('c-multi-phase', 5, 3, U, 'control.phaseEaters',
    T('Which of these eat into an attitude loop\'s phase margin? Choose every one.', 'Что из перечисленного уменьшает запас по фазе контура управления ориентацией? Выберите всё.', 'ข้อใดทำให้เฟสมาร์จินของลูปควบคุมท่าทางลดลง เลือกทุกข้อที่ถูก'),
    [O(T('A time delay in the flight computer', 'Запаздывание в бортовом компьютере', 'ความหน่วงเวลาในคอมพิวเตอร์การบิน'), true),
      O(T('A slow nozzle actuator', 'Медленный рулевой привод сопла', 'ตัวขับเร้าหัวฉีดที่ช้า'), true),
      O(T('A low-pass filter against the structure\'s bending', 'Фильтр нижних частот против изгибных колебаний корпуса', 'ตัวกรองความถี่ต่ำเพื่อกันการโค้งงอของโครงสร้าง'), true),
      O(T('Sampling the gyros faster', 'Более частый опрос гироскопов', 'สุ่มค่าไจโรถี่ขึ้น'), false,
        T('Every change to the loop\'s hardware costs margin.', 'Любое изменение аппаратуры контура уменьшает запас.', 'การเปลี่ยนฮาร์ดแวร์ของลูปทุกอย่างทำให้มาร์จินลดลง')),
      O(T('Adding derivative (rate) feedback', 'Добавление обратной связи по угловой скорости (дифференцирующей)', 'เพิ่มการป้อนกลับแบบอนุพันธ์ (อัตรา)'), false,
        T('Any added term slows the loop down.', 'Любой добавленный член замедляет контур.', 'การเพิ่มพจน์ใด ๆ ทำให้ลูปช้าลง'))],
    T('Delays, actuator lag and filters all add phase lag at the crossover. Faster sampling shortens the delay, so it gives margin back; rate feedback adds phase lead, which is why the D term steadies a loop.',
      'Запаздывания, инерционность привода и фильтры добавляют фазовое отставание на частоте среза. Более частый опрос сокращает запаздывание и возвращает запас; обратная связь по скорости даёт опережение по фазе — поэтому D-составляющая успокаивает контур.',
      'ความหน่วง ความล่าช้าของตัวขับเร้า และตัวกรอง ล้วนเพิ่มเฟสล้าหลังที่ความถี่ครอสโอเวอร์ การสุ่มถี่ขึ้นลดความหน่วงจึงคืนมาร์จิน ส่วนการป้อนกลับแบบอัตราเพิ่มเฟสนำ ด้วยเหตุนี้พจน์ D จึงทำให้ลูปนิ่งขึ้น'),
    { lessons: ['ctl-margins'] }),
  numeric('c-pd-damping', 5, 2, K, 'control.pd',
    T('A rigid vehicle (θ̈ = u) is held by the law u = K_p·(θ_c − θ) − K_d·θ̇, with K_p = {kp} s⁻² and K_d = {kd} s⁻¹. Work out the loop\'s damping ratio ζ.', 'Жёсткий аппарат (θ̈ = u) стабилизируется законом u = K_p·(θ_c − θ) − K_d·θ̇, где K_p = {kp} с⁻², K_d = {kd} с⁻¹. Определите коэффициент демпфирования ζ контура.', 'ยานแข็งเกร็ง (θ̈ = u) ถูกควบคุมด้วยกฎ u = K_p·(θ_c − θ) − K_d·θ̇ โดย K_p = {kp} วินาที⁻² และ K_d = {kd} วินาที⁻¹ จงหาอัตราส่วนความหน่วง ζ ของลูป'),
    [{ name: 'kp', min: 1, max: 9, step: 0.5 }, { name: 'kd', min: 1, max: 4, step: 0.1 }], 'kd / (2 * sqrt(kp))', '', 3,
    T('θ̈ + K_d·θ̇ + K_p·θ = K_p·θ_c is a second-order loop with ω_n = √K_p and 2ζω_n = K_d, so ζ = K_d / (2√K_p). Raising K_p alone makes the loop faster and less damped.',
      'θ̈ + K_d·θ̇ + K_p·θ = K_p·θ_c — звено второго порядка с ω_n = √K_p и 2ζω_n = K_d, откуда ζ = K_d / (2√K_p). Увеличение одного K_p ускоряет контур и уменьшает демпфирование.',
      'θ̈ + K_d·θ̇ + K_p·θ = K_p·θ_c เป็นระบบอันดับสองที่มี ω_n = √K_p และ 2ζω_n = K_d ดังนั้น ζ = K_d / (2√K_p) การเพิ่ม K_p เพียงอย่างเดียวทำให้ลูปเร็วขึ้นแต่หน่วงน้อยลง'),
    { lessons: ['ctl-step'] }),
  numeric('c-tvc-moment', 5, 3, K, 'control.tvcMoment',
    T('An engine of {F} kN thrust, {l} m behind the centre of mass, is swivelled {d}°. Work out the turning moment it makes (kN·m).', 'Двигатель с тягой {F} кН, расположенный на {l} м позади центра масс, отклонён на {d}°. Определите создаваемый им управляющий момент (кН·м).', 'เครื่องยนต์แรงขับ {F} kN อยู่ห่างหลังจุดศูนย์กลางมวล {l} ม. ถูกหมุนไป {d}° จงหาแรงบิดที่เกิดขึ้น (kN·m)'),
    [{ name: 'F', min: 1000, max: 8000, step: 500 }, { name: 'l', min: 10, max: 25, step: 1 }, { name: 'd', min: 1, max: 6, step: 0.5 }], 'F * l * sin(d)', 'kN·m', 3,
    T('Only the side component of the thrust, F·sin δ, turns the vehicle, with the arm l: M = F·l·sin δ. A few degrees of nozzle give a large moment, which is why a launcher needs so little swivel.',
      'Поворачивает аппарат только поперечная составляющая тяги F·sin δ на плече l: M = F·l·sin δ. Несколько градусов отклонения сопла дают большой момент — поэтому ракете достаточно небольших углов качания.',
      'มีเพียงองค์ประกอบด้านข้างของแรงขับ F·sin δ ที่หมุนยาน โดยมีแขนโมเมนต์ l: M = F·l·sin δ การหมุนหัวฉีดไม่กี่องศาให้แรงบิดมาก จรวดจึงต้องการมุมหมุนหัวฉีดเพียงเล็กน้อย')),
  choice('c-integral', 5, 2, U, 'control.integral',
    T('In a steady crosswind a launcher held by a PD autopilot keeps a small, constant attitude error. What removes it?', 'При постоянном боковом ветре ракета с ПД-автоматом стабилизации держит небольшую постоянную ошибку по углу. Что её устранит?', 'ขณะมีลมพัดด้านข้างคงที่ จรวดที่ใช้ออโตไพลอตแบบ PD มีความคลาดเคลื่อนท่าทางเล็ก ๆ คงที่ อะไรจะกำจัดความคลาดเคลื่อนนี้'),
    [O(T('An integral term, which builds up while the error lasts', 'Интегральная составляющая, накапливающаяся, пока есть ошибка', 'พจน์อินทิกรัล ซึ่งสะสมตราบที่ยังมีความคลาดเคลื่อน'), true),
      O(T('A higher derivative gain', 'Больший коэффициент по производной', 'อัตราขยายอนุพันธ์ที่สูงขึ้น'), false,
        T('The derivative term acts on any error, steady or not.', 'Дифференцирующая составляющая действует на любую ошибку, постоянную или нет.', 'พจน์อนุพันธ์ทำงานกับความคลาดเคลื่อนทุกแบบ ไม่ว่าจะคงที่หรือไม่')),
      O(T('A notch filter', 'Режекторный фильтр', 'ตัวกรองแบบนอตช์')),
      O(T('Nothing: a steady error can never be removed', 'Ничего: постоянную ошибку устранить нельзя', 'ไม่มีอะไร ความคลาดเคลื่อนคงที่กำจัดไม่ได้'))],
    T('A PD law needs an error to make the steady moment that balances the wind. An integral term keeps growing while any error is left, so it can hold that moment with none. The D term acts only on the rate, zero in a steady state.',
      'ПД-закону нужна ошибка, чтобы создать постоянный момент, уравновешивающий ветер. Интегральная составляющая растёт, пока остаётся хоть какая-то ошибка, и может держать этот момент без ошибки. D-составляющая реагирует только на скорость, которая в установившемся режиме равна нулю.',
      'กฎ PD ต้องมีความคลาดเคลื่อนเพื่อสร้างแรงบิดคงที่ที่ถ่วงดุลลม พจน์อินทิกรัลเพิ่มขึ้นเรื่อย ๆ ตราบที่ยังมีความคลาดเคลื่อนเหลืออยู่ จึงรักษาแรงบิดนั้นได้โดยไม่มีความคลาดเคลื่อน พจน์ D ตอบสนองต่ออัตราเท่านั้น ซึ่งเป็นศูนย์ในสภาวะคงตัว')),
];
