/** Area 6, failures and safety (roadmap E03). */
import { O, T, U, K, chart, choice, numeric } from './helpers';

export const FAILURES: readonly unknown[] = [
  choice('f-fts', 6, 1, K, 'safety.range',
    T('What is a launcher\'s flight termination system for?', 'Для чего на ракете система аварийного подрыва?', 'ระบบยุติการบิน (flight termination system) ของจรวดนำส่งมีไว้เพื่ออะไร'),
    [O(T('To destroy a rocket that strays from its corridor before it can endanger people', 'Чтобы уничтожить ракету, ушедшую из коридора, прежде чем она станет опасной для людей', 'เพื่อทำลายจรวดที่หลุดออกนอกระเบียงก่อนที่จะเป็นอันตรายต่อผู้คน'), true),
      O(T('To shut the engines down at the end of a normal flight', 'Чтобы выключить двигатели в конце нормального полёта', 'เพื่อดับเครื่องยนต์เมื่อจบการบินตามปกติ')),
      O(T('To separate the stages', 'Чтобы разделять ступени', 'เพื่อแยกขั้นจรวด')),
      O(T('To save the payload in an emergency', 'Чтобы спасти полезную нагрузку при аварии', 'เพื่อช่วยน้ำหนักบรรทุกในกรณีฉุกเฉิน'))],
    T('The range watches the trajectory against its safety lines; a vehicle that crosses them is destroyed while its debris still falls where nobody lives. Crewed vehicles first fire the escape system.',
      'Полигон сравнивает траекторию с границами безопасности; ракету, пересёкшую их, подрывают, пока её обломки ещё падают в безлюдный район. На пилотируемых ракетах сначала срабатывает система аварийного спасения.',
      'สนามทดสอบเฝ้าดูเส้นทางบินเทียบกับเส้นความปลอดภัย จรวดที่ข้ามเส้นจะถูกทำลายขณะที่ชิ้นส่วนยังตกลงในบริเวณที่ไม่มีคนอยู่ สำหรับจรวดที่มีมนุษย์ ระบบหนีภัยจะทำงานก่อน'),
    { lessons: ['orbit-range-safety'] }),
  choice('f-les', 6, 1, K, 'safety.escape',
    T('What does the tower on top of a crewed Soyuz do?', 'Что делает башня на вершине пилотируемого «Союза»?', 'หอบนยอดจรวดโซยุซที่มีมนุษย์ทำหน้าที่อะไร'),
    [O(T('In an emergency it pulls the crew\'s section away from the rocket', 'При аварии уводит отсек с экипажем от ракеты', 'ในกรณีฉุกเฉินจะดึงส่วนที่มีลูกเรือให้ห่างจากจรวด'), true),
      O(T('It is a lightning conductor', 'Это громоотвод', 'เป็นสายล่อฟ้า')),
      O(T('It carries the radio antennas', 'На ней установлены антенны', 'ใช้ติดเสาอากาศวิทยุ')),
      O(T('It gives extra thrust at lift-off', 'Даёт дополнительную тягу на старте', 'ให้แรงขับเพิ่มตอนออกตัว'))],
    T('The launch escape system\'s solid motors can pull the head section clear in under a second; the descent module then lands on its parachute. It saved the crew of Soyuz T-10-1 from a pad fire in 1983.',
      'Твердотопливные двигатели САС менее чем за секунду уводят головной блок; затем спускаемый аппарат приземляется на парашюте. В 1983 году САС спасла экипаж «Союза Т-10-1» при пожаре на старте.',
      'มอเตอร์เชื้อเพลิงแข็งของระบบหนีภัยดึงส่วนหัวออกไปได้ในเวลาไม่ถึงหนึ่งวินาที แล้วแคปซูลกลับสู่โลกก็ลงด้วยร่มชูชีพ ระบบนี้ช่วยลูกเรือของ Soyuz T-10-1 จากไฟไหม้บนแท่นปล่อยเมื่อปี 1983'),
    { lessons: ['fail-abort'] }),
  choice('f-three-imus', 6, 1, U, 'fdir.voting',
    T('Why do launchers carry three inertial units rather than two?', 'Почему на ракетах ставят три инерциальных блока, а не два?', 'ทำไมจรวดนำส่งจึงติดหน่วยเฉื่อยสามหน่วย ไม่ใช่สองหน่วย'),
    [O(T('With two you can see that they disagree, but not which one is wrong; three can vote', 'По двум можно увидеть расхождение, но не понять, какой неисправен; три могут голосовать', 'ถ้ามีสองหน่วยจะรู้ว่าค่าไม่ตรงกัน แต่ไม่รู้ว่าหน่วยไหนเสีย สามหน่วยจึงลงคะแนนกันได้'), true),
      O(T('Two would be enough; the third is only a spare', 'Двух хватило бы; третий — просто запасной', 'สองหน่วยก็พอ หน่วยที่สามเป็นแค่อะไหล่'), false,
        T('redundancy is only about spares', 'резервирование — это лишь запасные части', 'การสำรองเป็นเพียงเรื่องอะไหล่')),
      O(T('To average away the noise', 'Чтобы усреднить шум', 'เพื่อเฉลี่ยสัญญาณรบกวน')),
      O(T('Each stage needs its own', 'Каждой ступени нужен свой', 'แต่ละขั้นต้องมีหน่วยของตัวเอง'))],
    T('Two-out-of-three voting finds the odd one out and isolates it. It cannot catch a failure all three share — a common-mode fault such as the same software error in each.',
      'Голосование «два из трёх» выявляет выпадающий блок и отключает его. Отказ, общий для всех трёх, — например одна и та же программная ошибка — так не обнаружить.',
      'การลงคะแนนแบบสองในสามหาหน่วยที่ค่าแตกต่างแล้วแยกออก แต่จับความล้มเหลวที่ทั้งสามหน่วยมีร่วมกันไม่ได้ เช่น ข้อผิดพลาดของซอฟต์แวร์เดียวกันในทุกหน่วย'),
    { lessons: ['fail-gyro-fdir'] }),
  choice('f-engine-out-cap', 6, 1, K, 'failure.engineOut',
    T('A launcher with "engine-out capability"…', 'Носитель, обладающий «живучестью при отказе двигателя»…', 'จรวดนำส่งที่มี «ความสามารถรับมือเครื่องยนต์ดับ»…'),
    [O(T('…can still reach orbit if one of its engines fails', '…может выйти на орбиту даже при отказе одного из двигателей', '…ยังเข้าวงโคจรได้แม้เครื่องยนต์หนึ่งเครื่องจะดับ'), true),
      O(T('…can restart its engines in orbit', '…может повторно включать двигатели на орбите', '…จุดเครื่องยนต์ซ้ำในวงโคจรได้')),
      O(T('…has an escape system', '…имеет систему аварийного спасения', '…มีระบบหนีภัย')),
      O(T('…never has engine failures', '…никогда не имеет отказов двигателей', '…ไม่เคยมีเครื่องยนต์ดับ'))],
    T('It takes several engines and margin: the rest burn longer and the guidance re-plans. Falcon 9 lost an engine on flight CRS-1 in 2012 and still put its main payload in orbit.',
      'Для этого нужны несколько двигателей и запас: оставшиеся работают дольше, а наведение перестраивает траекторию. Falcon 9 в полёте CRS-1 в 2012 году потерял двигатель и всё же вывел основную нагрузку на орбиту.',
      'ต้องมีเครื่องยนต์หลายเครื่องและส่วนเผื่อ เครื่องที่เหลือจะเผาไหม้นานขึ้นและระบบนำวิถีวางแผนใหม่ Falcon 9 เคยเสียเครื่องยนต์ในเที่ยวบิน CRS-1 ปี 2012 แต่ยังนำน้ำหนักบรรทุกหลักเข้าวงโคจรได้'),
    { lessons: ['fail-engine-out'] }),
  choice('f-ms10', 6, 1, K, 'history.aborts',
    T('What happened to the crew of Soyuz MS-10 in October 2018, when a strap-on booster struck the core at separation?', 'Что стало с экипажем «Союза МС-10» в октябре 2018 года, когда боковой блок при отделении ударил центральный?', 'เกิดอะไรขึ้นกับลูกเรือของ Soyuz MS-10 ในเดือนตุลาคม 2018 เมื่อบูสเตอร์ด้านข้างกระแทกลำตัวหลักตอนแยกตัว'),
    [O(T('The escape system separated the spacecraft and both crew landed safely', 'Система аварийного спасения отделила корабль, и оба члена экипажа благополучно приземлились', 'ระบบหนีภัยแยกยานออก และลูกเรือทั้งสองลงถึงพื้นอย่างปลอดภัย'), true),
      O(T('They reached orbit on a lower trajectory', 'Они вышли на орбиту по более низкой траектории', 'ขึ้นถึงวงโคจรได้ด้วยเส้นทางที่ต่ำกว่า')),
      O(T('They were lost', 'Они погибли', 'เสียชีวิต')),
      O(T('The launch was stopped on the pad', 'Пуск был прерван на стартовом столе', 'การปล่อยถูกยกเลิกบนแท่น'))],
    T('The tower had already gone, so the fairing\'s motors pulled the spacecraft away at about 50 km; Aleksey Ovchinin and Nick Hague came down on a ballistic path at up to about 7 g.',
      'Башня САС к тому времени уже была сброшена, поэтому корабль увели двигатели головного обтекателя на высоте около 50 км; Алексей Овчинин и Ник Хейг спустились по баллистической траектории с перегрузкой до 7 единиц.',
      'ขณะนั้นหอหนีภัยถูกทิ้งไปแล้ว มอเตอร์ของฝาครอบจึงดึงยานออกที่ความสูงประมาณ 50 กม. อเล็กเซย์ ออฟชีนินและนิก เฮก ลงสู่พื้นด้วยเส้นทางขีปนวิถีที่ภาระสูงสุดราว 7 g'),
    { lessons: ['fail-abort'] }),
  choice('f-fdir', 6, 2, K, 'fdir.voting',
    T('What does an FDIR system do?', 'Что делает система FDIR?', 'ระบบ FDIR ทำหน้าที่อะไร'),
    [O(T('Detects a failure, isolates the failed unit, and reconfigures the system to fly on', 'Обнаруживает отказ, локализует неисправный блок и перестраивает систему для продолжения полёта', 'ตรวจจับความล้มเหลว แยกหน่วยที่เสียออก และปรับระบบให้บินต่อได้'), true),
      O(T('Records the flight data for the investigation', 'Записывает данные полёта для расследования', 'บันทึกข้อมูลการบินไว้สำหรับการสอบสวน')),
      O(T('Destroys the rocket after a failure', 'Подрывает ракету после отказа', 'ทำลายจรวดหลังเกิดความล้มเหลว')),
      O(T('Refuels the rocket in flight', 'Дозаправляет ракету в полёте', 'เติมเชื้อเพลิงให้จรวดขณะบิน'))],
    T('Fault Detection, Isolation and Recovery: IMU voting, a monitor that shuts down an engine whose nozzle goes hard over, jets excluded when they fire unasked, a backup computer that takes over.',
      'Fault Detection, Isolation and Recovery — обнаружение, локализация и парирование отказов: голосование ИИБ, контроль, отключающий двигатель с уведённым до упора соплом, исключение самопроизвольно работающих двигателей ориентации, резервный вычислитель.',
      'Fault Detection, Isolation and Recovery ได้แก่ การลงคะแนน IMU ตัวเฝ้าระวังที่ดับเครื่องยนต์ที่หัวฉีดค้างสุดทาง การตัดไอพ่นที่จุดเองโดยไม่ได้สั่ง และคอมพิวเตอร์สำรองที่รับช่วงต่อ'),
    { lessons: ['fail-gyro-fdir'] }),
  choice('f-stuck-gyro', 6, 2, U, 'fdir.gyro',
    T('The rate gyro of a launcher\'s only working inertial unit sticks at a constant reading. What does the autopilot do?', 'ДУС единственного работающего инерциального блока ракеты заклинило на постоянном значении. Что делает автомат стабилизации?', 'ไจโรวัดอัตราของหน่วยเฉื่อยหน่วยเดียวที่ใช้งานอยู่ค้างที่ค่าคงที่ ระบบนำร่องอัตโนมัติจะทำอะไร'),
    [O(T('It "corrects" a rotation that is not there and turns the vehicle away, often until it breaks up', 'Он «исправляет» несуществующее вращение и уводит ракету, часто до разрушения', 'มัน «แก้» การหมุนที่ไม่มีอยู่จริงและพายานเบนออกไป มักจนแตกหัก'), true),
      O(T('Nothing: a stuck reading means zero error', 'Ничего: постоянное показание означает нулевую ошибку', 'ไม่ทำอะไร ค่าคงที่หมายถึงไม่มีความคลาด'), false,
        T('a sensor that stops changing is harmless', 'датчик, показание которого не меняется, безвреден', 'เซนเซอร์ที่ค่าไม่เปลี่ยนไม่เป็นอันตราย')),
      O(T('It switches to GNSS automatically', 'Автоматически переходит на ГНСС', 'สลับไปใช้ GNSS โดยอัตโนมัติ')),
      O(T('It holds the last attitude perfectly', 'Идеально удерживает последнюю ориентацию', 'รักษาท่าทางล่าสุดไว้ได้สมบูรณ์'))],
    T('A stuck rate reads as a steady rotation; the loop commands the opposite rate and the attitude runs away while the sensor says all is well. In lesson 3.2 Falcon 9 breaks up eleven seconds later unless the FDIR votes the unit out.',
      'Заклинивший ДУС показывает постоянное вращение; контур задаёт встречную угловую скорость, и ориентация уходит, хотя датчик «говорит», что всё в порядке. В уроке 3.2 Falcon 9 разрушается через одиннадцать секунд, если FDIR не исключит блок голосованием.',
      'อัตราที่ค้างถูกอ่านเป็นการหมุนคงที่ วงควบคุมจึงสั่งอัตราตรงข้าม ท่าทางจึงเบนออกไปเรื่อย ๆ ทั้งที่เซนเซอร์บอกว่าปกติ ในบทเรียน 3.2 Falcon 9 แตกหักภายในสิบเอ็ดวินาทีหาก FDIR ไม่ลงคะแนนตัดหน่วยนั้นออก'),
    { lessons: ['fail-gyro-fdir'] }),
  choice('f-ariane501', 6, 2, K, 'history.failures',
    T('Why was the first Ariane 5 (flight 501, 1996) lost?', 'Почему была потеряна первая Ariane 5 (полёт 501, 1996 год)?', 'ทำไมจรวด Ariane 5 ลำแรก (เที่ยวบิน 501 ปี 1996) จึงสูญเสีย'),
    [O(T('Both inertial reference systems failed on the same software error, and their diagnostic data were flown as attitude', 'Обе инерциальные системы отказали из-за одной и той же программной ошибки, и их диагностические данные были восприняты как ориентация', 'ระบบอ้างอิงเฉื่อยทั้งสองชุดล้มเหลวจากข้อผิดพลาดซอฟต์แวร์เดียวกัน และข้อมูลวินิจฉัยของมันถูกใช้เป็นข้อมูลท่าทาง'), true),
      O(T('A strap-on booster exploded', 'Взорвался стартовый ускоритель', 'บูสเตอร์ด้านข้างระเบิด')),
      O(T('Lightning struck it', 'В неё ударила молния', 'ฟ้าผ่า')),
      O(T('The fairing did not separate', 'Не отделился головной обтекатель', 'ฝาครอบไม่แยกตัว'))],
    T('A 64-bit horizontal velocity overflowed a 16-bit integer in code carried over from Ariane 4 at H0+36.7 s. Both units ran the same code and failed together — a common-mode failure no voting can catch.',
      'На H0+36,7 с 64-разрядное значение горизонтальной скорости переполнило 16-разрядное целое в программе, унаследованной от Ariane 4. Оба блока работали по одной программе и отказали одновременно — общий отказ, который не выявит никакое голосование.',
      'ที่ H0+36.7 วินาที ค่าความเร็วแนวราบแบบ 64 บิตล้นตัวแปรจำนวนเต็ม 16 บิตในโค้ดที่ยกมาจาก Ariane 4 ทั้งสองหน่วยใช้โค้ดเดียวกันจึงล้มเหลวพร้อมกัน เป็นความล้มเหลวร่วม (common-mode) ที่การลงคะแนนใด ๆ จับไม่ได้'),
    { lessons: ['fail-gyro-fdir'] }),
  choice('f-proton2013', 6, 2, K, 'history.failures',
    T('Why did a Proton-M crash seconds after lift-off at Baikonur on 2 July 2013?', 'Почему «Протон-М» 2 июля 2013 года упал через несколько секунд после старта с Байконура?', 'ทำไมจรวด Proton-M จึงตกหลังออกตัวไม่กี่วินาทีที่ไบโคนูร์เมื่อ 2 กรกฎาคม 2013'),
    [O(T('Angular-rate sensors had been installed upside down, so the control system fought the wrong way', 'Датчики угловой скорости были установлены перевёрнутыми, и система управления действовала в противоположную сторону', 'เซนเซอร์อัตราเชิงมุมถูกติดตั้งกลับหัว ระบบควบคุมจึงสั่งการในทิศตรงข้าม'), true),
      O(T('An engine exploded at lift-off', 'На старте взорвался двигатель', 'เครื่องยนต์ระเบิดตอนออกตัว')),
      O(T('A strong gust of wind', 'Сильный порыв ветра', 'ลมกระโชกแรง')),
      O(T('The range destroyed it by mistake', 'Полигон подорвал её по ошибке', 'สนามทดสอบสั่งทำลายโดยผิดพลาด'))],
    T('The yaw-rate sensors were mounted reversed, so every correction doubled the error. All units shared the fault, so no voting could see it; the rocket pitched over and broke up within about twenty seconds.',
      'Датчики угловой скорости по рысканию были установлены с обратной полярностью, и каждая «коррекция» удваивала ошибку. Отказ был общим для всех блоков, голосование его не видело; ракета завалилась и разрушилась примерно через двадцать секунд.',
      'เซนเซอร์อัตราการหันเห (yaw) ถูกติดกลับขั้ว ทุกการแก้จึงทำให้ความคลาดเพิ่มเป็นสองเท่า ความผิดพลาดเกิดกับทุกหน่วยพร้อมกัน การลงคะแนนจึงมองไม่เห็น จรวดเอียงล้มและแตกหักภายในราวยี่สิบวินาที')),
  choice('f-engine-out-thrust', 6, 2, U, 'failure.engineOut',
    T('Predict: one of Falcon 9\'s nine first-stage engines fails at T+80 s. What happens to the thrust at that moment? After answering, compare the two flights on the chart.', 'Предскажите: на T+80 с отказывает один из девяти двигателей первой ступени Falcon 9. Что происходит с тягой в этот момент? После ответа сравните два полёта на графике.', 'จงทำนาย: เครื่องยนต์หนึ่งในเก้าเครื่องของขั้นที่ 1 ของ Falcon 9 ดับที่ T+80 วินาที แรงขับจะเป็นอย่างไรในขณะนั้น เมื่อตอบแล้วให้เปรียบเทียบสองเที่ยวบินบนกราฟ'),
    [O(T('It drops by about a ninth and stays down for the rest of the stage', 'Падает примерно на девятую часть и остаётся пониженной до конца работы ступени', 'ลดลงประมาณหนึ่งในเก้าและคงต่ำไปจนจบการทำงานของขั้น'), true),
      O(T('It drops to zero until the other engines take over', 'Падает до нуля, пока не подхватят остальные двигатели', 'ลดลงเป็นศูนย์จนกว่าเครื่องอื่นจะรับช่วง'), false,
        T('the whole stage stops when one engine does', 'при отказе одного двигателя останавливается вся ступень', 'ทั้งขั้นหยุดทำงานเมื่อเครื่องยนต์หนึ่งเครื่องดับ')),
      O(T('It stays the same: the others throttle up at once', 'Не меняется: остальные сразу форсируются', 'คงเดิม เพราะเครื่องอื่นเร่งขึ้นทันที')),
      O(T('It falls by half', 'Падает вдвое', 'ลดลงครึ่งหนึ่ง'))],
    T('Nine engines give nine shares; one lost leaves eight. Falcon 9\'s engines are not uprated to make it up in this model, so the stage just burns about 8 s longer.',
      'Девять двигателей дают девять долей; без одного остаются восемь. Форсирования остальных в этой модели нет, поэтому ступень просто работает примерно на 8 с дольше.',
      'เครื่องยนต์เก้าเครื่องให้แรงขับเก้าส่วน เสียไปหนึ่งเหลือแปด ในแบบจำลองนี้เครื่องที่เหลือไม่ได้เร่งเพิ่มเพื่อชดเชย ขั้นจึงเพียงแต่เผาไหม้นานขึ้นประมาณ 8 วินาที'),
    { observe: chart('f9-leo', 'thrust', ['f9-leo-engine-out'], 180), lessons: ['fail-engine-out'] }),
  choice('f-maxq-danger', 6, 2, U, 'failure.maxq',
    T('Why is a control failure near max-Q more dangerous for the structure than the same failure at T+10 s?', 'Почему отказ системы управления в районе максимального напора опаснее для конструкции, чем такой же отказ на T+10 с?', 'ทำไมความล้มเหลวของระบบควบคุมช่วง max-Q จึงอันตรายต่อโครงสร้างมากกว่าความล้มเหลวเดียวกันที่ T+10 วินาที'),
    [O(T('The same angle of attack gives a far larger bending load, because it scales with q·α', 'Тот же угол атаки даёт гораздо большую изгибающую нагрузку, поскольку она пропорциональна q·α', 'มุมปะทะเท่าเดิมให้ภาระดัดมากกว่ามาก เพราะแปรตาม q·α'), true),
      O(T('The engines are hottest there', 'Там двигатели наиболее горячие', 'ที่ช่วงนั้นเครื่องยนต์ร้อนที่สุด')),
      O(T('The rocket is heaviest there', 'Там ракета тяжелее всего', 'ที่ช่วงนั้นจรวดหนักที่สุด')),
      O(T('It is not more dangerous', 'Это не опаснее', 'ไม่ได้อันตรายกว่า'), false,
        T('a failure is equally dangerous at any point of the ascent', 'отказ одинаково опасен на любом участке выведения', 'ความล้มเหลวอันตรายเท่ากันทุกช่วงของการไต่ระดับ'))],
    T('At T+10 s q is under 1 kPa; at max-Q 20–35 kPa. The same few degrees of α that the vehicle shrugs off at lift-off break it at max-Q — as the stuck gyro in lesson 3.2 shows.',
      'На T+10 с q меньше 1 кПа, на максимальном напоре — 20–35 кПа. Те же несколько градусов угла атаки, которые ракета легко переносит на старте, разрушают её на максимальном напоре, как показывает заклинивший ДУС в уроке 3.2.',
      'ที่ T+10 วินาที q ต่ำกว่า 1 kPa แต่ที่ max-Q สูงถึง 20–35 kPa มุมปะทะไม่กี่องศาที่จรวดรับได้สบายตอนออกตัวจะทำให้มันแตกหักที่ max-Q ดังที่ไจโรค้างในบทเรียน 3.2 แสดงให้เห็น'),
    { lessons: ['fail-gyro-fdir'] }),
  choice('f-fairing-motors', 6, 2, K, 'safety.escape',
    T('About T+115 s into a crewed Soyuz launch the escape tower is jettisoned. What protects the crew after that?', 'Примерно на T+115 с полёта пилотируемого «Союза» башня САС сбрасывается. Что защищает экипаж после этого?', 'ประมาณ T+115 วินาทีหลังปล่อยโซยุซที่มีมนุษย์ หอหนีภัยจะถูกทิ้ง หลังจากนั้นอะไรปกป้องลูกเรือ'),
    [O(T('Solid motors on the fairing, and later the spacecraft\'s own separation', 'Двигатели на головном обтекателе, а позже — штатное отделение корабля', 'มอเตอร์เชื้อเพลิงแข็งบนฝาครอบ และต่อมาคือการแยกตัวของยานอวกาศเอง'), true),
      O(T('Nothing until orbit', 'Ничего до выхода на орбиту', 'ไม่มีอะไรจนกว่าจะถึงวงโคจร')),
      O(T('Parachutes on the third stage', 'Парашюты третьей ступени', 'ร่มชูชีพของขั้นที่ 3')),
      O(T('The escape tower of the next stage', 'Башня следующей ступени', 'หอหนีภัยของขั้นถัดไป'))],
    T('Above about 40 km the air no longer needs the tower\'s power: the fairing\'s own motors can pull the head section clear until the fairing goes at T+157 s; after that the spacecraft separates from the rocket and makes a ballistic entry.',
      'Выше примерно 40 км мощность башни уже не нужна: головной блок до сброса обтекателя на T+157 с уводят двигатели самого обтекателя; позже корабль отделяется от ракеты и совершает баллистический спуск.',
      'เหนือระดับประมาณ 40 กม. ไม่ต้องใช้กำลังของหอหนีภัยอีก มอเตอร์ของฝาครอบเองสามารถดึงส่วนหัวออกไปได้จนกว่าฝาครอบจะถูกทิ้งที่ T+157 วินาที หลังจากนั้นยานจะแยกตัวจากจรวดและกลับเข้าบรรยากาศแบบขีปนวิถี'),
    { lessons: ['fail-abort'] }),
  choice('f-common-mode', 6, 3, U, 'fdir.voting',
    T('Three identical inertial units run identical software. Which failure can two-out-of-three voting NOT catch?', 'Три одинаковых инерциальных блока работают по одинаковой программе. Какой отказ голосование «два из трёх» НЕ обнаружит?', 'หน่วยเฉื่อยสามหน่วยที่เหมือนกันใช้ซอฟต์แวร์เดียวกัน ความล้มเหลวแบบใดที่การลงคะแนนสองในสามจับไม่ได้'),
    [O(T('A software error that makes all three give the same wrong answer', 'Программную ошибку, из-за которой все три выдают одинаковый неверный результат', 'ข้อผิดพลาดของซอฟต์แวร์ที่ทำให้ทั้งสามหน่วยให้คำตอบผิดเหมือนกัน'), true),
      O(T('One gyro sticking', 'Заклинивание одного гироскопа', 'ไจโรตัวหนึ่งค้าง')),
      O(T('One unit losing power', 'Пропадание питания одного блока', 'หน่วยหนึ่งไฟดับ')),
      O(T('Any failure: voting catches everything', 'Никакой: голосование выявляет всё', 'ไม่มี การลงคะแนนจับได้ทุกอย่าง'), false,
        T('redundancy protects against every failure', 'резервирование защищает от любого отказа', 'การสำรองป้องกันความล้มเหลวได้ทุกแบบ'))],
    T('Voting finds the unit that differs; when all agree on the wrong answer there is nothing to find. Protection against common-mode faults needs diversity — different designs, different software — or checks on physical plausibility.',
      'Голосование находит выпадающий блок; когда все согласны в ошибке, выделить нечего. Защита от общих отказов требует разнородности — других конструкций, другой программы — или проверок физической правдоподобности.',
      'การลงคะแนนหาหน่วยที่ต่างออกไป เมื่อทุกหน่วยเห็นตรงกันในคำตอบที่ผิดจึงไม่มีอะไรให้หา การป้องกันความล้มเหลวร่วมต้องอาศัยความหลากหลาย เช่น การออกแบบหรือซอฟต์แวร์ที่ต่างกัน หรือการตรวจความสมเหตุสมผลทางฟิสิกส์'),
    { lessons: ['fail-gyro-fdir'] }),
  choice('f-escape-load', 6, 3, U, 'safety.escape',
    T('Why does an escape near max-Q put a high load on the crew?', 'Почему спасение в районе максимального напора даёт экипажу большую перегрузку?', 'ทำไมการหนีภัยช่วง max-Q จึงทำให้ลูกเรือรับภาระสูง'),
    [O(T('The motor accelerates the head section hard, and the dense fast air then brakes it hard', 'Двигатель сильно разгоняет головной блок, а плотный встречный поток затем резко тормозит его', 'มอเตอร์เร่งส่วนหัวอย่างแรง แล้วอากาศหนาแน่นที่พุ่งเข้ามาก็หน่วงมันอย่างแรง'), true),
      O(T('Because the rocket explodes right next to the crew', 'Потому что ракета взрывается рядом с экипажем', 'เพราะจรวดระเบิดอยู่ข้างลูกเรือ')),
      O(T('Because gravity is strongest there', 'Потому что там сильнее всего тяготение', 'เพราะแรงโน้มถ่วงแรงที่สุดที่นั่น')),
      O(T('It does not: an escape is always gentle', 'Не даёт: спасение всегда мягкое', 'ไม่ได้รับภาระสูง การหนีภัยนุ่มนวลเสมอ'), false,
        T('an escape system is gentle whatever the flight conditions', 'система спасения работает мягко при любых условиях полёта', 'ระบบหนีภัยทำงานนุ่มนวลไม่ว่าสภาพการบินเป็นอย่างไร'))],
    T('The tower must open a gap from a rocket still moving at hundreds of m/s; once free, the blunt head section decelerates in air at 30 kPa. Lesson 3.3 measures the peak.',
      'Башне нужно быстро создать разрыв с ракетой, летящей со скоростью сотни м/с; после отделения тупой головной блок тормозится в потоке с напором 30 кПа. Пик измеряют в уроке 3.3.',
      'หอหนีภัยต้องสร้างระยะห่างจากจรวดที่ยังเคลื่อนที่หลายร้อยเมตรต่อวินาที เมื่อหลุดออกแล้วส่วนหัวที่ทู่จะถูกอากาศที่ความดันพลวัต 30 kPa หน่วงความเร็ว บทเรียน 3.3 วัดค่าสูงสุดนี้'),
    { lessons: ['fail-abort'] }),
  numeric('f-voting-reliability', 6, 3, K, 'fdir.reliability',
    T('Each of three independent units works through the flight with probability {p} %. The system works if at least two do. What is the system\'s probability of working (%)?',
      'Каждый из трёх независимых блоков безотказно работает в полёте с вероятностью {p} %. Система работоспособна, если исправны хотя бы два. Какова вероятность безотказной работы системы (%)?',
      'หน่วยอิสระสามหน่วยแต่ละหน่วยทำงานได้ตลอดเที่ยวบินด้วยความน่าจะเป็น {p} % ระบบทำงานได้ถ้ามีอย่างน้อยสองหน่วยทำงาน ความน่าจะเป็นที่ระบบทำงานได้คือเท่าใด (%)'),
    [{ name: 'p', min: 80, max: 99, step: 1 }], '100 * (3 * (p / 100)^2 - 2 * (p / 100)^3)', '%', 0.2,
    T('P = 3p² − 2p³ (two working and one failed in three ways, or all three working). At p = 0.95 it is 0.993 — better than one unit, but only while the failures are independent.',
      'P = 3p² − 2p³ (два исправных и один отказавший — тремя способами, либо все три исправны). При p = 0,95 это 0,993 — лучше одного блока, но только пока отказы независимы.',
      'P = 3p² − 2p³ (ทำงานสองหน่วยและเสียหนึ่งหน่วยได้สามแบบ หรือทำงานทั้งสาม) ที่ p = 0.95 ได้ 0.993 ดีกว่าหน่วยเดียว แต่เฉพาะเมื่อความล้มเหลวเป็นอิสระต่อกัน'),
    { lessons: ['fail-gyro-fdir'] }),
  choice('f-engine-out-timing', 6, 3, U, 'failure.engineOut',
    T('A first-stage engine fails either at T+10 s or at T+120 s. Which costs the mission more Δv, and why?', 'Двигатель первой ступени отказывает либо на T+10 с, либо на T+120 с. Какой случай обходится миссии дороже по Δv и почему?', 'เครื่องยนต์ขั้นที่ 1 ดับที่ T+10 วินาที หรือที่ T+120 วินาที กรณีใดทำให้ภารกิจเสีย Δv มากกว่า และเพราะอะไร'),
    [O(T('At T+10 s: the rocket then climbs with less thrust through almost the whole stage, and loses more to gravity', 'На T+10 с: ракета почти весь участок первой ступени набирает высоту с меньшей тягой и больше теряет на гравитацию', 'ที่ T+10 วินาที เพราะจรวดต้องไต่ด้วยแรงขับที่น้อยลงเกือบตลอดช่วงของขั้นนี้ จึงเสียให้แรงโน้มถ่วงมากกว่า'), true),
      O(T('At T+120 s: the rocket is going faster then', 'На T+120 с: в это время ракета летит быстрее', 'ที่ T+120 วินาที เพราะตอนนั้นจรวดเร็วกว่า'), false,
        T('a failure costs more the faster the rocket is going', 'отказ тем дороже, чем быстрее летит ракета', 'ความล้มเหลวยิ่งแพงเมื่อจรวดยิ่งเร็ว')),
      O(T('Both the same: the same propellant is burnt either way', 'Одинаково: топливо сгорает то же самое', 'เท่ากัน เพราะเผาเชื้อเพลิงเท่ากันทั้งสองกรณี')),
      O(T('Neither costs anything', 'Ни один ничего не стоит', 'ไม่เสียอะไรทั้งสองกรณี'))],
    T('The same propellant burns in both cases; what differs is how long the rocket flies with less acceleration while still climbing steeply. Early, that is the whole stage; late, a few seconds before cut-off. In this simulator 15 t to LEO keeps 411 m/s after a failure at T+10 s, 528 m/s after one at T+120 s.',
      'Топливо сгорает одно и то же; разница — в том, как долго ракета летит с меньшим ускорением, всё ещё круто набирая высоту. При раннем отказе — всю ступень, при позднем — несколько секунд до выключения. В этом симуляторе при выведении 15 т на НОО после отказа на T+10 с остаётся 411 м/с, после отказа на T+120 с — 528 м/с.',
      'เชื้อเพลิงที่เผาเท่ากัน สิ่งที่ต่างคือระยะเวลาที่จรวดบินด้วยความเร่งที่น้อยลงขณะยังไต่ชันอยู่ ถ้าดับเร็วคือตลอดทั้งขั้น ถ้าดับช้าคือเพียงไม่กี่วินาทีก่อนดับเครื่อง ในโปรแกรมนี้ การนำ 15 ตันเข้า LEO ยังเหลือ 411 ม./วินาทีเมื่อดับที่ T+10 วินาที และ 528 ม./วินาทีเมื่อดับที่ T+120 วินาที'),
    { lessons: ['fail-engine-out'] }),
  choice('f-18a', 6, 3, K, 'history.aborts',
    T('Soyuz 18a (5 April 1975): the second and third stages failed to separate properly at about 145 km. What happened?', '«Союз-18-1» (5 апреля 1975 года): вторая и третья ступени нормально не разделились на высоте около 145 км. Что произошло?', 'Soyuz 18a (5 เมษายน 1975): ขั้นที่ 2 และ 3 แยกตัวไม่สมบูรณ์ที่ความสูงประมาณ 145 กม. เกิดอะไรขึ้น'),
    [O(T('The spacecraft separated for a ballistic entry; the crew survived about 20 g and landed in the Altai mountains', 'Корабль отделился и совершил баллистический спуск; экипаж перенёс около 20 единиц перегрузки и приземлился в горах Алтая', 'ยานแยกตัวและกลับสู่บรรยากาศแบบขีปนวิถี ลูกเรือรอดจากภาระราว 20 g และลงจอดบนเทือกเขาอัลไต'), true),
      O(T('The escape tower pulled the crew away', 'Башня САС увела экипаж', 'หอหนีภัยดึงลูกเรือออกไป'), false,
        T('the tower protects the crew all the way to orbit', 'башня защищает экипаж до самой орбиты', 'หอหนีภัยปกป้องลูกเรือตลอดทางจนถึงวงโคจร')),
      O(T('They reached a low orbit and returned the next day', 'Они вышли на низкую орбиту и вернулись на следующий день', 'ขึ้นถึงวงโคจรต่ำและกลับลงมาในวันถัดมา')),
      O(T('The crew was lost', 'Экипаж погиб', 'ลูกเรือเสียชีวิต'))],
    T('The tower had gone long before. The spacecraft separated from the tumbling rocket and made a steep ballistic entry; Vasily Lazarev and Oleg Makarov came down on a snowy slope near the Chinese border.',
      'Башня к тому времени давно была сброшена. Корабль отделился от кувыркающейся ракеты и совершил крутой баллистический спуск; Василий Лазарев и Олег Макаров приземлились на заснеженном склоне недалеко от китайской границы.',
      'ขณะนั้นหอหนีภัยถูกทิ้งไปนานแล้ว ยานแยกตัวจากจรวดที่กำลังตีลังกาและกลับเข้าบรรยากาศแบบขีปนวิถีที่ชัน วาซีลี ลาซาเรฟและโอเลก มาคารอฟลงจอดบนเนินที่มีหิมะใกล้ชายแดนจีน'),
    { lessons: ['fail-abort'] }),
];
