/** Area 4, guidance and navigation (roadmap E03). */
import { K, O, T, U, choice, diagram, letters, multi, numeric, order } from './helpers';

export const GUIDANCE: readonly unknown[] = [
  choice('g-gravity-turn', 4, 1, K, 'guidance.gravityTurn',
    T('In a gravity turn, what turns the rocket from vertical towards horizontal flight?', 'Что при гравитационном развороте переводит ракету из вертикального полёта в горизонтальный?', 'ในการเลี้ยวด้วยแรงโน้มถ่วง (gravity turn) อะไรทำให้จรวดเปลี่ยนจากการบินแนวดิ่งไปสู่แนวราบ'),
    [O(T('Gravity bending the velocity down, after a small kick at the start', 'Тяготение, искривляющее вектор скорости вниз после небольшого начального отклонения', 'แรงโน้มถ่วงที่ดัดเวกเตอร์ความเร็วลง หลังจากการเอียงเล็กน้อยช่วงเริ่มต้น'), true),
      O(T('Large fins steering against the air', 'Большие аэродинамические рули', 'ครีบขนาดใหญ่ที่บังคับเลี้ยวกับอากาศ')),
      O(T('The Earth\'s rotation', 'Вращение Земли', 'การหมุนของโลก')),
      O(T('Side thrusters firing all the way up', 'Боковые двигатели, работающие весь участок выведения', 'ไอพ่นด้านข้างที่จุดตลอดการไต่ระดับ'))],
    T('After a short pitch-over (the kick), the rocket holds its nose along its velocity — zero angle of attack — and gravity itself bends the path over. It keeps aerodynamic loads low in the dense air.',
      'После короткого начального разворота по тангажу ракета держит продольную ось вдоль скорости — нулевой угол атаки, — и траекторию искривляет само тяготение. Так в плотных слоях атмосферы аэродинамические нагрузки остаются малыми.',
      'หลังการเอียงพิตช์สั้น ๆ ช่วงแรก (kick) จรวดจะรักษาหัวให้ชี้ตามความเร็ว คือมุมปะทะเป็นศูนย์ แล้วแรงโน้มถ่วงก็ดัดเส้นทางให้โค้งลงเอง วิธีนี้ทำให้ภาระทางอากาศพลศาสตร์ต่ำในอากาศหนาแน่น'),
    { lessons: ['guid-maxq'] }),
  choice('g-gnc', 4, 1, K, 'guidance.terms',
    T('In "guidance, navigation and control", what does navigation do?', 'Что в системе «наведение, навигация, управление» делает навигация?', 'ในระบบ «การนำวิถี การนำทาง และการควบคุม» (GNC) การนำทางทำหน้าที่อะไร'),
    [O(T('Works out where the vehicle is, how fast it is going and how it is pointing', 'Определяет положение, скорость и ориентацию аппарата', 'หาว่ายานอยู่ที่ใด เคลื่อนที่เร็วเท่าใด และหันไปทางใด'), true),
      O(T('Decides where to steer to reach the target', 'Решает, куда направлять полёт, чтобы попасть в цель', 'ตัดสินใจว่าจะบังคับไปทางใดเพื่อไปถึงเป้าหมาย')),
      O(T('Moves the engines to follow the commanded attitude', 'Отклоняет двигатели, отрабатывая заданную ориентацию', 'ขยับเครื่องยนต์ให้เป็นไปตามท่าทางที่สั่ง')),
      O(T('Plans the launch window', 'Планирует окно запуска', 'วางแผนหน้าต่างการปล่อย'))],
    T('Navigation: where am I? Guidance: where should I point to reach the target? Control: make the vehicle point there. Each feeds the next.',
      'Навигация: где я? Наведение: куда направить аппарат, чтобы попасть в цель? Управление: развернуть аппарат туда. Каждая часть питает следующую.',
      'การนำทาง: ฉันอยู่ที่ไหน การนำวิถี: ควรชี้ไปทางใดจึงจะถึงเป้าหมาย การควบคุม: ทำให้ยานหันไปทางนั้น แต่ละส่วนป้อนข้อมูลให้ส่วนถัดไป'),
    { lessons: ['guid-nav'] }),
  choice('g-imu', 4, 1, K, 'navigation.imu',
    T('An inertial measurement unit (IMU) contains…', 'Инерциальный измерительный блок содержит…', 'หน่วยวัดแรงเฉื่อย (IMU) ประกอบด้วย…'),
    [O(T('…gyroscopes and accelerometers', '…гироскопы (датчики угловой скорости) и акселерометры', '…ไจโรสโคปและเครื่องวัดความเร่ง'), true),
      O(T('…a GPS receiver and a compass', '…приёмник GPS и компас', '…เครื่องรับ GPS และเข็มทิศ')),
      O(T('…a radar and a camera', '…радиолокатор и камеру', '…เรดาร์และกล้อง')),
      O(T('…a barometer and a thermometer', '…барометр и термометр', '…บารอมิเตอร์และเทอร์โมมิเตอร์'))],
    T('The gyroscopes measure the rotation rates, the accelerometers the specific force; integrated, they give attitude, velocity and position without any outside signal.',
      'Гироскопы измеряют угловые скорости, акселерометры — кажущееся ускорение; интегрируя их, получают ориентацию, скорость и положение без внешних сигналов.',
      'ไจโรสโคปวัดอัตราการหมุน เครื่องวัดความเร่งวัดแรงจำเพาะ เมื่ออินทิเกรตแล้วจะได้ท่าทาง ความเร็ว และตำแหน่งโดยไม่ต้องใช้สัญญาณจากภายนอก'),
    { lessons: ['guid-nav', 'fail-gyro-fdir'] }),
  choice('g-turn-early', 4, 1, U, 'guidance.gravityTurn',
    T('Why does a rocket begin to tilt over only seconds after clearing the tower, instead of climbing straight up out of the atmosphere first?', 'Почему ракета начинает разворот всего через несколько секунд после ухода с пусковой установки, а не поднимается сначала вертикально выше атмосферы?', 'ทำไมจรวดจึงเริ่มเอียงเพียงไม่กี่วินาทีหลังพ้นหอส่ง แทนที่จะไต่ขึ้นตรง ๆ จนพ้นบรรยากาศก่อน'),
    [O(T('Orbit needs horizontal speed; every second spent climbing vertically is lost to gravity', 'Для орбиты нужна горизонтальная скорость, а каждая секунда вертикального подъёма уходит на гравитационные потери', 'วงโคจรต้องการความเร็วแนวราบ ทุกวินาทีที่ไต่ตรงขึ้นไปเสียให้แรงโน้มถ่วง'), true),
      O(T('Only to keep clear of the launch tower', 'Только чтобы отойти от башни обслуживания', 'เพียงเพื่อให้ห่างจากหอส่ง'), false,
        T('the turn is only about clearing the tower', 'разворот нужен лишь для ухода от башни', 'การเลี้ยวมีไว้เพียงเพื่อหลบหอส่ง')),
      O(T('Because the engines cannot point straight down', 'Потому что двигатели не могут работать вертикально вниз', 'เพราะเครื่องยนต์ชี้ลงตรง ๆ ไม่ได้')),
      O(T('To reach space faster', 'Чтобы быстрее попасть в космос', 'เพื่อไปถึงอวกาศให้เร็วขึ้น'))],
    T('Getting above the air takes a few minutes; being in orbit takes 7.8 km/s sideways. A vertical climb pays g every second for nothing sideways, so the turn starts early and is shaped to keep the aerodynamic loads acceptable.',
      'Подняться над атмосферой — дело нескольких минут, а для орбиты нужно 7,8 км/с в горизонтальном направлении. Вертикальный подъём каждую секунду платит g, не давая горизонтальной скорости, поэтому разворот начинают рано и формируют так, чтобы аэродинамические нагрузки оставались допустимыми.',
      'การขึ้นให้พ้นอากาศใช้เวลาเพียงไม่กี่นาที แต่การอยู่ในวงโคจรต้องการความเร็วแนวราบ 7.8 กม./วินาที การไต่ตรงขึ้นเสีย g ทุกวินาทีโดยไม่ได้ความเร็วแนวราบเลย จึงเริ่มเลี้ยวตั้งแต่ต้นและออกแบบให้ภาระทางอากาศพลศาสตร์อยู่ในเกณฑ์'),
    { lessons: ['guid-maxq'] }),
  choice('g-gnss-alone', 4, 1, U, 'navigation.gnss',
    T('Why is GNSS (GPS, GLONASS) alone not enough to steer a launcher?', 'Почему одной ГНСС (GPS, ГЛОНАСС) недостаточно для управления носителем?', 'ทำไม GNSS (GPS, GLONASS) อย่างเดียวจึงไม่พอสำหรับบังคับจรวดนำส่ง'),
    [O(T('It updates slowly and can drop out, and it gives no attitude; the inertial system fills the gaps', 'Она обновляется редко, может пропадать и не даёт ориентации; пробелы заполняет инерциальная система', 'อัปเดตช้าและอาจขาดหาย ทั้งไม่ให้ข้อมูลท่าทาง ระบบเฉื่อยจึงต้องเติมช่องว่าง'), true),
      O(T('Satellites cannot see a rocket in flight', 'Спутники не видят ракету в полёте', 'ดาวเทียมมองไม่เห็นจรวดขณะบิน')),
      O(T('GNSS is forbidden above 10 km', 'ГНСС запрещена выше 10 км', 'ห้ามใช้ GNSS เหนือ 10 กม.')),
      O(T('It is exactly as good; launchers use it alone', 'Она ничем не хуже; носители используют только её', 'ดีพอ ๆ กัน จรวดนำส่งใช้อย่างเดียว'), false,
        T('satellite navigation alone is enough to fly a launcher', 'для полёта носителя достаточно одной спутниковой навигации', 'การนำทางด้วยดาวเทียมอย่างเดียวก็พอสำหรับบินจรวดนำส่ง'))],
    T('The autopilot needs attitude and rates hundreds of times a second, which only gyros give. GNSS bounds the slow drift of the inertial position — the job of the Kalman filter in the Engineer mode\'s navigation.',
      'Автомату стабилизации нужны ориентация и угловые скорости сотни раз в секунду, а их дают только гироскопы. ГНСС ограничивает медленный уход инерциального решения по положению — это задача фильтра Калмана в навигации режима «Инженер».',
      'ระบบนำร่องอัตโนมัติต้องการท่าทางและอัตราการหมุนหลายร้อยครั้งต่อวินาที ซึ่งมีแต่ไจโรให้ได้ GNSS ช่วยจำกัดการคลาดที่ค่อย ๆ สะสมของตำแหน่งจากระบบเฉื่อย ซึ่งเป็นงานของตัวกรองคาลมานในระบบนำทางของโหมดวิศวกร'),
    { lessons: ['guid-nav'] }),
  choice('g-closed-loop', 4, 2, U, 'guidance.closedLoop',
    T('Out of the atmosphere a launcher switches to closed-loop guidance (such as PEG). What does closed-loop add over a fixed pitch programme?', 'Вне атмосферы носитель переходит на замкнутое наведение (например, PEG). Что оно даёт по сравнению с жёсткой программой тангажа?', 'เมื่อพ้นบรรยากาศ จรวดนำส่งเปลี่ยนไปใช้การนำวิถีแบบวงปิด (เช่น PEG) สิ่งนี้เพิ่มอะไรจากโปรแกรมพิตช์แบบตายตัว'),
    [O(T('It measures where the vehicle actually is and re-solves the steering to the target, correcting dispersions', 'Оно учитывает фактическое состояние аппарата и заново решает задачу наведения на цель, парируя разбросы', 'วัดตำแหน่งจริงของยานแล้วคำนวณการบังคับไปยังเป้าหมายใหม่ จึงแก้ความคลาดเคลื่อนได้'), true),
      O(T('It saves weight by removing the IMU', 'Оно экономит массу за счёт отказа от ИИБ', 'ช่วยลดน้ำหนักด้วยการไม่ใช้ IMU')),
      O(T('It keeps the angle of attack at zero', 'Оно удерживает нулевой угол атаки', 'รักษามุมปะทะให้เป็นศูนย์')),
      O(T('Nothing: it flies the same programme', 'Ничего: оно выполняет ту же программу', 'ไม่เพิ่มอะไร บินตามโปรแกรมเดิม'), false,
        T('a pre-computed programme reaches the target whatever the dispersions', 'заранее рассчитанная программа попадает в цель при любых разбросах', 'โปรแกรมที่คำนวณไว้ล่วงหน้าไปถึงเป้าได้ไม่ว่าจะมีความคลาดเคลื่อนเท่าใด'))],
    T('A fixed programme is tuned for the nominal flight; a weaker engine or a heavier payload leaves it off target. Closed-loop guidance aims at the target conditions from the state it is in, every cycle.',
      'Жёсткая программа рассчитана на номинальный полёт; более слабый двигатель или тяжёлая нагрузка уводят её от цели. Замкнутое наведение в каждом цикле нацеливается на заданные условия из текущего состояния.',
      'โปรแกรมตายตัวปรับไว้สำหรับการบินตามค่าปกติ ถ้าเครื่องยนต์อ่อนกว่าหรือน้ำหนักบรรทุกมากกว่าก็จะพลาดเป้า การนำวิถีแบบวงปิดเล็งไปยังเงื่อนไขเป้าหมายจากสถานะปัจจุบันทุกรอบการคำนวณ'),
    { lessons: ['guid-peg'] }),
  choice('g-ins-drift', 4, 2, K, 'navigation.drift',
    T('An accelerometer has a small constant bias. Without any outside fix, how does the position error of an inertial system grow with time?', 'У акселерометра небольшое постоянное смещение нуля. Как растёт ошибка по положению инерциальной системы без внешней коррекции?', 'เครื่องวัดความเร่งมีไบแอสคงที่เล็กน้อย หากไม่มีการแก้จากภายนอก ความคลาดของตำแหน่งในระบบเฉื่อยจะเพิ่มขึ้นตามเวลาอย่างไร'),
    [O(T('With the square of time', 'Пропорционально квадрату времени', 'ตามกำลังสองของเวลา'), true),
      O(T('Linearly with time', 'Линейно по времени', 'เป็นเส้นตรงตามเวลา')),
      O(T('It stays constant', 'Остаётся постоянной', 'คงที่')),
      O(T('It shrinks as the filter learns', 'Уменьшается по мере «обучения» фильтра', 'ลดลงเมื่อตัวกรองเรียนรู้'))],
    T('A bias b is integrated twice: the velocity error grows as b·t, the position error as ½·b·t². A gyro bias is worse still: it tilts the platform, which misdirects gravity, and the position error grows about as t³.',
      'Смещение b интегрируется дважды: ошибка скорости растёт как b·t, ошибка положения — как ½·b·t². Уход гироскопа ещё хуже: он наклоняет базис, неверно учитывается тяготение, и ошибка положения растёт примерно как t³.',
      'ไบแอส b ถูกอินทิเกรตสองครั้ง ความคลาดของความเร็วเพิ่มเป็น b·t และของตำแหน่งเป็น ½·b·t² ไบแอสของไจโรร้ายแรงกว่า เพราะทำให้แกนอ้างอิงเอียง แรงโน้มถ่วงจึงถูกคิดผิดทิศ และความคลาดของตำแหน่งเพิ่มราว t³'),
    { lessons: ['guid-nav'] }),
  choice('g-kalman', 4, 2, U, 'navigation.kalman',
    T('What does a Kalman filter do with an inertial prediction and a GNSS measurement?', 'Что фильтр Калмана делает с инерциальным прогнозом и измерением ГНСС?', 'ตัวกรองคาลมานทำอะไรกับค่าทำนายจากระบบเฉื่อยและค่าวัดจาก GNSS'),
    [O(T('Blends them, weighting each by how uncertain it is, and estimates the sensors\' errors', 'Смешивает их с весами по неопределённости каждого и оценивает ошибки датчиков', 'ผสมทั้งสองค่าโดยถ่วงน้ำหนักตามความไม่แน่นอนของแต่ละค่า และประมาณความคลาดของเซนเซอร์'), true),
      O(T('Takes their average', 'Берёт их среднее', 'หาค่าเฉลี่ย'), false,
        T('the filter simply averages the sources', 'фильтр просто усредняет источники', 'ตัวกรองแค่หาค่าเฉลี่ยของแหล่งข้อมูล')),
      O(T('Always trusts GNSS and ignores the inertial system', 'Всегда доверяет ГНСС и игнорирует инерциальную систему', 'เชื่อ GNSS เสมอและไม่สนใจระบบเฉื่อย')),
      O(T('Removes the noise from the engines', 'Устраняет шум двигателей', 'กำจัดเสียงรบกวนจากเครื่องยนต์'))],
    T('The gain K = P·Hᵀ(H·P·Hᵀ + R)⁻¹ weighs the prediction\'s covariance P against the measurement\'s R. The filter also estimates biases, so the inertial solution is corrected even between fixes.',
      'Коэффициент усиления K = P·Hᵀ(H·P·Hᵀ + R)⁻¹ соизмеряет ковариацию прогноза P с ковариацией измерения R. Фильтр оценивает и смещения датчиков, поэтому инерциальное решение уточняется и между измерениями.',
      'เกน K = P·Hᵀ(H·P·Hᵀ + R)⁻¹ ชั่งความแปรปรวนร่วมของค่าทำนาย P กับของค่าวัด R ตัวกรองยังประมาณไบแอสของเซนเซอร์ด้วย ผลจากระบบเฉื่อยจึงถูกแก้แม้ในช่วงระหว่างการวัด'),
    { lessons: ['guid-nav'] }),
  choice('g-peg-igm', 4, 2, K, 'guidance.explicit',
    T('Powered Explicit Guidance (PEG) and the Iterative Guidance Mode (IGM) were first flown on…', 'Явное наведение PEG и итерационный метод IGM впервые применялись на…', 'Powered Explicit Guidance (PEG) และ Iterative Guidance Mode (IGM) ถูกใช้บินครั้งแรกกับ…'),
    [O(T('…the Space Shuttle (PEG) and the Saturn V (IGM)', '…Спейс шаттле (PEG) и «Сатурне-5» (IGM)', '…กระสวยอวกาศ (PEG) และแซตเทิร์น 5 (IGM)'), true),
      O(T('…Soyuz (PEG) and Proton (IGM)', '…«Союзе» (PEG) и «Протоне» (IGM)', '…โซยุซ (PEG) และโปรตอน (IGM)')),
      O(T('…Falcon 9 (both)', '…Falcon 9 (оба)', '…Falcon 9 (ทั้งสองแบบ)')),
      O(T('…the V-2 (both)', '…Фау-2 (оба)', '…V-2 (ทั้งสองแบบ)'))],
    T('IGM steered Saturn\'s S-II and S-IVB from 1967; PEG, derived from it, flew the Shuttle from 1981. Both solve for the steering that reaches the target in the burn time left.',
      'IGM управлял ступенями S-II и S-IVB «Сатурна» с 1967 года; выросший из него PEG выводил шаттлы с 1981 года. Оба решают задачу наведения, приводящего к цели за оставшееся время работы.',
      'IGM บังคับขั้น S-II และ S-IVB ของแซตเทิร์นตั้งแต่ปี 1967 ส่วน PEG ซึ่งพัฒนาต่อมานำกระสวยอวกาศขึ้นตั้งแต่ปี 1981 ทั้งสองคำนวณการบังคับที่พาไปถึงเป้าหมายภายในเวลาเผาไหม้ที่เหลือ'),
    { lessons: ['guid-peg'] }),
  choice('g-zero-alpha', 4, 2, U, 'guidance.alpha',
    T('Through the dense atmosphere the guidance holds the angle of attack near zero. Why?', 'В плотных слоях атмосферы наведение держит угол атаки около нуля. Зачем?', 'ช่วงที่อากาศหนาแน่น ระบบนำวิถีรักษามุมปะทะไว้ใกล้ศูนย์ เพราะอะไร'),
    [O(T('The bending load on the structure grows with q·α', 'Изгибающая нагрузка на конструкцию растёт пропорционально q·α', 'ภาระดัดต่อโครงสร้างเพิ่มตาม q·α'), true),
      O(T('To reduce drag and save propellant', 'Чтобы уменьшить сопротивление и сэкономить топливо', 'เพื่อลดแรงต้านและประหยัดเชื้อเพลิง'), false,
        T('the angle of attack matters for drag, not for the structure', 'угол атаки важен для сопротивления, а не для прочности', 'มุมปะทะสำคัญต่อแรงต้าน ไม่ใช่ต่อโครงสร้าง')),
      O(T('The engines cannot gimbal at high speed', 'Двигатели не могут качаться на большой скорости', 'เครื่องยนต์ปรับมุมไม่ได้ที่ความเร็วสูง')),
      O(T('To keep the crew comfortable', 'Чтобы экипажу было удобнее', 'เพื่อให้ลูกเรือสบาย'))],
    T('A long, thin rocket at an angle to the air feels a sideways force at its nose that bends it; the product q·α (often limited to a few thousand Pa·rad) is what structures are designed to.',
      'Длинную тонкую ракету под углом к потоку боковая сила на носовой части изгибает; конструкцию рассчитывают именно на произведение q·α (обычно ограничивается несколькими тысячами Па·рад).',
      'จรวดที่ยาวและเรียวเมื่อเอียงทำมุมกับกระแสอากาศจะได้รับแรงด้านข้างที่ส่วนหัวซึ่งดัดตัวมัน โครงสร้างถูกออกแบบตามผลคูณ q·α (มักจำกัดไว้ไม่กี่พัน Pa·rad)'),
    { lessons: ['guid-maxq'] }),
  choice('g-tgo', 4, 2, K, 'guidance.explicit',
    T('In explicit guidance, what is t_go?', 'Что такое t_go в явном наведении?', 'ในการนำวิถีแบบชัดแจ้ง t_go คืออะไร'),
    [O(T('The burn time left until the target is reached and the engine cuts off', 'Оставшееся время работы двигателя до достижения цели и выключения', 'เวลาเผาไหม้ที่เหลือจนถึงเป้าหมายและดับเครื่อง'), true),
      O(T('The time since lift-off', 'Время от старта', 'เวลาตั้งแต่ออกตัว')),
      O(T('The time until the next launch window', 'Время до следующего окна запуска', 'เวลาจนถึงหน้าต่างการปล่อยครั้งถัดไป')),
      O(T('The guidance cycle time', 'Такт работы наведения', 'รอบเวลาการคำนวณของระบบนำวิถี'))],
    T('t_go and the velocity to be gained v_go are re-estimated every cycle; as the cut-off approaches, t_go runs down to zero and the solution is frozen for the last seconds.',
      't_go и потребное приращение скорости v_go пересчитываются в каждом цикле; к выключению t_go уменьшается до нуля, а на последних секундах решение фиксируется.',
      't_go และความเร็วที่ต้องเพิ่ม v_go ถูกประมาณใหม่ทุกรอบ เมื่อใกล้ดับเครื่อง t_go ลดลงจนเป็นศูนย์ และคำตอบจะถูกตรึงไว้ในไม่กี่วินาทีสุดท้าย'),
    { lessons: ['guid-peg'] }),
  choice('g-monte-carlo', 4, 2, U, 'guidance.dispersion',
    T('What is a Monte Carlo analysis of a launch for?', 'Для чего проводят анализ пуска методом Монте-Карло?', 'การวิเคราะห์การปล่อยจรวดด้วยวิธีมอนติคาร์โลมีไว้เพื่ออะไร'),
    [O(T('To see how the uncertainties in thrust, mass, wind and so on spread the result, by flying many randomised flights', 'Чтобы оценить, как неопределённости тяги, масс, ветра и т. п. разбрасывают результат, выполнив множество полётов со случайными параметрами', 'เพื่อดูว่าความไม่แน่นอนของแรงขับ มวล ลม ฯลฯ ทำให้ผลลัพธ์กระจายเท่าใด โดยจำลองการบินหลายครั้งที่สุ่มค่า'), true),
      O(T('To find the single best launch time', 'Чтобы найти одно наилучшее время старта', 'เพื่อหาเวลาปล่อยที่ดีที่สุดเพียงเวลาเดียว'), false,
        T('a simulation predicts one exact outcome, not a spread', 'моделирование даёт один точный исход, а не разброс', 'การจำลองให้ผลลัพธ์แน่นอนเพียงค่าเดียว ไม่ใช่การกระจาย')),
      O(T('To choose the rocket\'s colour scheme', 'Чтобы выбрать окраску ракеты', 'เพื่อเลือกสีของจรวด')),
      O(T('To test the random number generator', 'Чтобы проверить генератор случайных чисел', 'เพื่อทดสอบตัวสร้างเลขสุ่ม'))],
    T('No two rockets are alike. Drawing each uncertain quantity from its distribution and flying thousands of cases gives the spread of the insertion (for example its 3σ) and the probability of meeting the requirement.',
      'Двух одинаковых ракет не бывает. Разыгрывая каждую неопределённую величину по её закону распределения и выполняя тысячи полётов, получают разброс параметров выведения (например, 3σ) и вероятность выполнения требований.',
      'ไม่มีจรวดสองลำที่เหมือนกัน การสุ่มค่าที่ไม่แน่นอนแต่ละค่าตามการแจกแจงของมันแล้วจำลองการบินนับพันครั้ง ทำให้ได้การกระจายของการเข้าวงโคจร (เช่น 3σ) และความน่าจะเป็นที่จะผ่านข้อกำหนด'),
    { lessons: ['guid-monte-carlo'] }),
  numeric('g-ins-error', 4, 3, K, 'navigation.drift',
    T('An accelerometer carries a constant bias of {b} mg (thousandths of g0 = 9.81 m/s²). With no outside fix, how large is the position error after {t} s (km)?',
      'Акселерометр имеет постоянное смещение {b} мg (тысячных долей g0 = 9,81 м/с²). Какова ошибка по положению без внешней коррекции через {t} с (км)?',
      'เครื่องวัดความเร่งมีไบแอสคงที่ {b} mg (หนึ่งในพันของ g0 = 9.81 ม./วินาที²) หากไม่มีการแก้จากภายนอก ความคลาดของตำแหน่งหลัง {t} วินาทีเป็นเท่าใด (กม.)'),
    [{ name: 'b', min: 0.1, max: 2, step: 0.1 }, { name: 't', min: 100, max: 900, step: 50 }], '0.5 * b * 0.001 * 9.81 * t^2 / 1000', 'km', 2,
    T('Δr = ½·b·t². 1 mg for 600 s is already 1.8 km — why navigation grade matters and why GNSS aiding is used.',
      'Δr = ½·b·t². 1 мg за 600 с даёт уже 1,8 км — поэтому так важен класс точности датчиков и коррекция по ГНСС.',
      'Δr = ½·b·t² เพียง 1 mg นาน 600 วินาทีก็คลาดถึง 1.8 กม. ความแม่นยำระดับนำทางของเซนเซอร์และการช่วยด้วย GNSS จึงสำคัญ'),
    { lessons: ['guid-nav'] }),
  choice('g-gyro-bias', 4, 3, U, 'navigation.drift',
    T('A gyro has a constant bias. Without any correction, which grows linearly with time?', 'У гироскопа постоянный уход. Что без коррекции растёт линейно со временем?', 'ไจโรมีไบแอสคงที่ หากไม่มีการแก้ อะไรที่เพิ่มขึ้นเป็นเส้นตรงตามเวลา'),
    [O(T('The attitude error', 'Ошибка ориентации', 'ความคลาดของท่าทาง'), true),
      O(T('The position error', 'Ошибка положения', 'ความคลาดของตำแหน่ง'), false,
        T('a gyro error shows up directly in position', 'ошибка гироскопа прямо переходит в ошибку положения', 'ความคลาดของไจโรปรากฏในตำแหน่งโดยตรง')),
      O(T('The speed error', 'Ошибка скорости', 'ความคลาดของอัตราเร็ว')),
      O(T('Nothing: a constant bias cancels out', 'Ничего: постоянный уход компенсируется сам', 'ไม่มี ไบแอสคงที่หักล้างกันเอง'))],
    T('A rate bias integrates once into attitude: θ = b·t. That tilt then misdirects the accelerometers\' reading of thrust and gravity, and the velocity and position errors grow as t² and t³.',
      'Уход по угловой скорости однократно интегрируется в ошибку ориентации: θ = b·t. Этот наклон затем искажает направление измеренных тяги и тяготения, и ошибки скорости и положения растут как t² и t³.',
      'ไบแอสของอัตราหมุนถูกอินทิเกรตหนึ่งครั้งเป็นความคลาดของท่าทาง θ = b·t การเอียงนั้นทำให้ทิศของแรงขับและแรงโน้มถ่วงที่วัดได้ผิดไป ความคลาดของความเร็วและตำแหน่งจึงเพิ่มตาม t² และ t³'),
    { lessons: ['guid-nav', 'fail-gyro-fdir'] }),
  choice('g-3sigma', 4, 3, K, 'guidance.dispersion',
    T('For a normally distributed error, what share of flights falls within ±3σ?', 'Какая доля полётов при нормальном распределении ошибки попадает в пределы ±3σ?', 'สำหรับความคลาดที่แจกแจงแบบปกติ เที่ยวบินกี่เปอร์เซ็นต์อยู่ภายใน ±3σ'),
    [O(T('99.7 %', '99,7 %', '99.7 %'), true), O(T('68 %', '68 %', '68 %')), O(T('95 %', '95 %', '95 %')), O(T('100 %', '100 %', '100 %'))],
    T('±1σ holds 68.3 %, ±2σ 95.4 %, ±3σ 99.73 %. Requirements written as 3σ accept about three flights in a thousand outside the band.',
      '±1σ — 68,3 %, ±2σ — 95,4 %, ±3σ — 99,73 %. Требования в терминах 3σ допускают около трёх полётов из тысячи за пределами.',
      '±1σ ครอบคลุม 68.3 % ±2σ 95.4 % และ ±3σ 99.73 % ข้อกำหนดแบบ 3σ จึงยอมให้ราวสามเที่ยวบินในพันเที่ยวอยู่นอกขอบเขต'),
    { lessons: ['guid-monte-carlo'] }),
  choice('g-linear-tangent', 4, 3, K, 'guidance.explicit',
    T('The linear tangent law, the basis of IGM and PEG, says that for the least propellant in vacuum over a flat Earth…', 'Закон линейного тангенса, лежащий в основе IGM и PEG, утверждает, что для минимального расхода в пустоте над плоской Землёй…', 'กฎแทนเจนต์เชิงเส้น ซึ่งเป็นพื้นฐานของ IGM และ PEG กล่าวว่า เพื่อใช้เชื้อเพลิงน้อยที่สุดในสุญญากาศเหนือโลกแบน…'),
    [O(T('…the tangent of the pitch angle varies linearly with time', '…тангенс угла тангажа изменяется линейно во времени', '…แทนเจนต์ของมุมพิตช์แปรผันเป็นเส้นตรงตามเวลา'), true),
      O(T('…the pitch angle falls linearly with altitude', '…угол тангажа линейно убывает с высотой', '…มุมพิตช์ลดลงเป็นเส้นตรงตามความสูง')),
      O(T('…the thrust should vary linearly with time', '…тяга должна изменяться линейно во времени', '…แรงขับควรแปรผันเป็นเส้นตรงตามเวลา')),
      O(T('…the vehicle should fly horizontally all the time', '…аппарат должен всё время лететь горизонтально', '…ยานควรบินแนวราบตลอดเวลา'))],
    T('The optimal-control solution for a uniform gravity field is tan ϑ = (a + b·t)/(c + d·t), which in its simple forms is linear in t. The real guidance corrects it for the round Earth each cycle.',
      'Решение задачи оптимального управления в однородном поле тяготения — tg ϑ = (a + b·t)/(c + d·t), в простых формах линейное по t. Реальное наведение в каждом цикле поправляет его на сферичность Земли.',
      'คำตอบของปัญหาการควบคุมเหมาะที่สุดในสนามโน้มถ่วงสม่ำเสมอคือ tan Θ = (a + b·t)/(c + d·t) ซึ่งในรูปอย่างง่ายเป็นเส้นตรงตาม t ระบบนำวิถีจริงจะแก้ค่านี้สำหรับโลกที่กลมทุกรอบการคำนวณ'),
    { lessons: ['guid-peg'] }),
  choice('g-dogleg-cost', 4, 3, U, 'guidance.dogleg',
    T('A dogleg — leaving along the edge of the range corridor and turning into the target plane later — costs Δv. Where does that cost come from?', 'Боковой манёвр по курсу (старт по границе коридора с последующим доворотом в плоскость цели) стоит Δv. Откуда берётся эта цена?', 'การเลี้ยวหักมุม (dogleg) คือขึ้นตามขอบระเบียงแล้วค่อยเลี้ยวเข้าระนาบเป้าหมายภายหลัง ต้องเสีย Δv ราคานี้มาจากไหน'),
    [O(T('Part of the thrust points out of the plane of motion to turn it, and adds nothing to the speed along the path', 'Часть тяги направлена из плоскости движения, чтобы повернуть её, и не добавляет скорости вдоль траектории', 'แรงขับส่วนหนึ่งชี้ออกนอกระนาบการเคลื่อนที่เพื่อหมุนระนาบ จึงไม่ช่วยเพิ่มความเร็วตามเส้นทาง'), true),
      O(T('The rocket flies a longer distance through the air', 'Ракета дольше летит в атмосфере', 'จรวดบินในอากาศเป็นระยะทางยาวขึ้น')),
      O(T('The Earth\'s rotation works against the turn', 'Вращение Земли противодействует развороту', 'การหมุนของโลกต้านการเลี้ยว')),
      O(T('It costs nothing; it only changes the ground track', 'Он ничего не стоит, меняется лишь трасса', 'ไม่เสียอะไร แค่เปลี่ยนแนวทางภาคพื้น'), false,
        T('turning the path is free: only speed costs propellant', 'поворот траектории бесплатен: топливо тратится только на скорость', 'การเลี้ยวเส้นทางไม่เสียอะไร เชื้อเพลิงใช้เพื่อความเร็วเท่านั้น'))],
    T('Thrust at an angle β to the velocity gives only cos β of itself as speed; the rest turns the plane. The simulator counts it as steering loss, and the setup panel shows the dogleg\'s angle.',
      'Тяга под углом β к скорости даёт приращение скорости лишь cos β от себя; остальное идёт на поворот плоскости. Симулятор учитывает это как потери на управление, а панель настройки показывает угол доворота.',
      'แรงขับที่ทำมุม β กับความเร็วให้ความเร็วเพิ่มเพียง cos β ของตัวมัน ส่วนที่เหลือใช้หมุนระนาบ โปรแกรมนับส่วนนี้เป็นการสูญเสียจากการบังคับทิศ และแผงตั้งค่าแสดงมุมการเลี้ยวไว้'),
    { lessons: ['orbit-range-safety'] }),
  choice('g-ellipse-inner', 4, 3, U, 'guidance.ellipse',
    T('300 dispersed flights: where each put the payload (Δh_a the apogee\'s error, Δi the inclination\'s), with ellipses at one, two and three standard deviations (A, B, C). About what share of the flights falls inside A?', '300 полётов с разбросом: куда каждый вывел полезную нагрузку (Δh_a — ошибка апогея, Δi — наклонения), с эллипсами одного, двух и трёх средних квадратических отклонений (A, B, C). Какая доля полётов примерно попадает внутрь A?', 'การบิน 300 ครั้งที่มีการกระจาย: จุดที่แต่ละครั้งส่งสัมภาระไปถึง (Δh_a ความคลาดเคลื่อนของจุดไกลโลก Δi ของความเอียง) พร้อมวงรีที่หนึ่ง สอง และสามส่วนเบี่ยงเบนมาตรฐาน (A, B, C) สัดส่วนการบินที่อยู่ภายใน A ประมาณเท่าใด'),
    [O(T('About 39%', 'Около 39 %', 'ประมาณ 39%'), true),
      O(T('About 68%, as within ±1σ', 'Около 68 %, как в пределах ±1σ', 'ประมาณ 68% เท่ากับภายใน ±1σ'), false,
        T('The one-dimensional 68% holds for an ellipse of two errors too.', 'Одномерные 68 % справедливы и для эллипса из двух ошибок.', 'ค่า 68% ของมิติเดียวใช้กับวงรีของความคลาดเคลื่อนสองตัวได้เหมือนกัน')),
      O(T('About 50%', 'Около 50 %', 'ประมาณ 50%')),
      O(T('About 95%', 'Около 95 %', 'ประมาณ 95%'))],
    T('For two independent normal errors the 1σ ellipse holds 1 − e^(−1/2) ≈ 39% of the points, the 2σ ellipse 86%, the 3σ ellipse 98.9%. Each error alone is within ±1σ 68% of the time, but both at once far less often.',
      'Для двух независимых нормальных ошибок эллипс 1σ содержит 1 − e^(−1/2) ≈ 39 % точек, эллипс 2σ — 86 %, 3σ — 98,9 %. Каждая ошибка в отдельности находится в пределах ±1σ в 68 % случаев, но обе одновременно — гораздо реже.',
      'สำหรับความคลาดเคลื่อนปกติสองตัวที่เป็นอิสระกัน วงรี 1σ มีจุดอยู่ 1 − e^(−1/2) ≈ 39% วงรี 2σ มี 86% และวงรี 3σ มี 98.9% ความคลาดเคลื่อนแต่ละตัวอยู่ภายใน ±1σ ได้ 68% ของเวลา แต่ทั้งสองพร้อมกันเกิดน้อยกว่ามาก'),
    { figure: diagram('dispersion'), fixedOrder: true, lessons: ['guid-monte-carlo'] }),
  choice('g-ellipse-outer', 4, 2, K, 'guidance.ellipse',
    T('300 dispersed flights, with ellipses at one, two and three standard deviations (A, B, C). Which ellipse would a mission designer quote as holding nearly every flight?', '300 полётов с разбросом, эллипсы одного, двух и трёх средних квадратических отклонений (A, B, C). Какой эллипс проектант назовёт содержащим почти все полёты?', 'การบิน 300 ครั้งที่มีการกระจาย พร้อมวงรีที่หนึ่ง สอง และสามส่วนเบี่ยงเบนมาตรฐาน (A, B, C) ผู้ออกแบบภารกิจจะอ้างวงรีใดว่าครอบคลุมการบินเกือบทั้งหมด'),
    letters('C', {}, ['A', 'B', 'C']),
    T('C, the 3σ ellipse: about 99% of the flights. Launch contracts quote the injection accuracy at 3σ, and the payload\'s own propulsion is sized to correct an error that large.',
      'C — эллипс 3σ: около 99 % полётов. В контрактах на запуск точность выведения указывают на уровне 3σ, и двигательная установка полезной нагрузки рассчитана на исправление такой ошибки.',
      'C คือวงรี 3σ ครอบคลุมประมาณ 99% ของการบิน สัญญาการส่งดาวเทียมระบุความแม่นยำการส่งเข้าวงโคจรที่ระดับ 3σ และระบบขับเคลื่อนของสัมภาระถูกออกแบบให้แก้ความคลาดเคลื่อนขนาดนั้นได้'),
    { figure: diagram('dispersion'), fixedOrder: true, lessons: ['guid-monte-carlo'] }),
  order('g-order-ascent', 4, 1, K, 'guidance.phases',
    T('Put the phases of a launcher\'s steering in order, from lift-off.', 'Расположите этапы управления полётом ракеты-носителя по порядку, начиная со старта.', 'เรียงลำดับช่วงการบังคับทิศของจรวดนำส่ง ตั้งแต่ยกตัว'),
    [T('A vertical rise to clear the tower', 'Вертикальный подъём до ухода от башни', 'ไต่ขึ้นตรงจนพ้นหอปล่อย'),
      T('A short pitch-over, the kick', 'Короткий разворот по тангажу', 'เอียงตัวสั้น ๆ ตามพิตช์ (kick)'),
      T('A gravity turn at near-zero angle of attack through max-Q', 'Гравитационный разворот с почти нулевым углом атаки через max-Q', 'การเลี้ยวด้วยแรงโน้มถ่วงที่มุมปะทะเกือบศูนย์ผ่าน max-Q'),
      T('Closed-loop explicit guidance above the atmosphere', 'Замкнутое явное наведение выше атмосферы', 'การนำวิถีแบบชัดแจ้งวงปิดเหนือชั้นบรรยากาศ'),
      T('Cut-off when the target orbit\'s velocity is reached', 'Выключение по достижении скорости целевой орбиты', 'ดับเครื่องเมื่อได้ความเร็วของวงโคจรเป้าหมาย')],
    T('The first minutes fly a pitch programme planned before flight (open loop) that keeps the angle of attack near zero, so that the air loads stay small; once out of the dense air the guidance steers on its own measurements to the orbit (PEG, IGM) and cuts the engine at the target\'s velocity.',
      'Первые минуты ракета летит по программе тангажа, рассчитанной до полёта (разомкнутое управление), удерживая угол атаки около нуля, чтобы аэродинамические нагрузки были малы; выйдя из плотных слоёв, система наведения по собственным измерениям ведёт ракету к орбите (PEG, IGM) и выключает двигатель при скорости цели.',
      'ช่วงไม่กี่นาทีแรกบินตามโปรแกรมพิตช์ที่คำนวณไว้ก่อนบิน (วงเปิด) โดยรักษามุมปะทะให้ใกล้ศูนย์เพื่อให้แรงทางอากาศน้อย เมื่อพ้นอากาศหนาแน่น ระบบนำวิถีบังคับเองจากการวัดของตนไปยังวงโคจร (PEG, IGM) และดับเครื่องที่ความเร็วเป้าหมาย'),
    { lessons: ['guid-peg'] }),
  multi('g-multi-imu', 4, 1, K, 'navigation.imuMeasures',
    T('Which does an inertial measurement unit measure directly? Choose every one.', 'Что инерциальный измерительный блок измеряет непосредственно? Выберите всё.', 'หน่วยวัดเฉื่อยวัดค่าใดได้โดยตรง เลือกทุกข้อที่ถูก'),
    [O(T('The specific force (the acceleration, less gravity) along its axes', 'Кажущееся ускорение (ускорение без учёта тяготения) по своим осям', 'แรงจำเพาะ (ความเร่งที่ไม่รวมแรงโน้มถ่วง) ตามแกนของมัน'), true),
      O(T('The angular rate about its axes', 'Угловую скорость вокруг своих осей', 'อัตราเชิงมุมรอบแกนของมัน'), true),
      O(T('The position', 'Положение', 'ตำแหน่ง')),
      O(T('The height above sea level', 'Высоту над уровнем моря', 'ความสูงเหนือระดับน้ำทะเล')),
      O(T('The direction to the target orbit', 'Направление на целевую орбиту', 'ทิศทางไปยังวงโคจรเป้าหมาย'))],
    T('Accelerometers measure specific force, gyros measure angular rate; the navigation integrates them, with a gravity model, into attitude, velocity and position. That integration is why their small biases grow into large errors.',
      'Акселерометры измеряют кажущееся ускорение, гироскопы — угловую скорость; навигационная система интегрирует их с моделью гравитационного поля и получает ориентацию, скорость и положение. Из-за этого интегрирования их малые смещения нулей вырастают в большие ошибки.',
      'มาตรความเร่งวัดแรงจำเพาะ ไจโรวัดอัตราเชิงมุม ระบบนำทางอินทิเกรตค่าเหล่านี้ร่วมกับแบบจำลองแรงโน้มถ่วงเป็นท่าทาง ความเร็ว และตำแหน่ง การอินทิเกรตนี้เองที่ทำให้ไบแอสเล็ก ๆ กลายเป็นความคลาดเคลื่อนใหญ่'),
    { lessons: ['guid-nav'] }),
  multi('g-multi-peg', 4, 2, U, 'guidance.explicitInputs',
    T('Which does an explicit guidance scheme such as PEG use each cycle to work out where to point? Choose every one.', 'Что использует явная схема наведения, например PEG, на каждом цикле, чтобы определить направление тяги? Выберите всё.', 'การนำวิถีแบบชัดแจ้ง เช่น PEG ใช้อะไรในแต่ละรอบการคำนวณเพื่อหาทิศที่จะชี้ เลือกทุกข้อที่ถูก'),
    [O(T('The present position and velocity, from the navigation', 'Текущие положение и скорость от навигационной системы', 'ตำแหน่งและความเร็วปัจจุบันจากระบบนำทาง'), true),
      O(T('The conditions the target orbit asks for at cut-off', 'Условия целевой орбиты в момент выключения', 'เงื่อนไขของวงโคจรเป้าหมาย ณ เวลาดับเครื่อง'), true),
      O(T('The engine\'s thrust and flow rate: the acceleration still to come', 'Тягу и расход двигателя — предстоящее ускорение', 'แรงขับและอัตราการไหลของเชื้อเพลิง คือความเร่งที่จะได้ต่อจากนี้'), true),
      O(T('A pitch table fixed before flight', 'Заранее заданную таблицу угла тангажа', 'ตารางมุมพิตช์ที่กำหนดไว้ก่อนบิน'), false,
        T('Guidance in space still follows the angles planned on the ground.', 'Наведение в космосе по-прежнему следует углам, рассчитанным на Земле.', 'การนำวิถีในอวกาศยังคงบินตามมุมที่คำนวณไว้บนพื้นดิน')),
      O(T('Wind measurements sent up from the ground', 'Данные о ветре, переданные с Земли', 'ข้อมูลลมที่ส่งขึ้นมาจากพื้นดิน'))],
    T('PEG re-solves the steering to the target from where the vehicle is now, with the acceleration its engines will still give, and updates t_go every cycle; that is why it absorbs an engine out or a heavier payload. Winds matter only in the atmosphere, where the pitch table is flown.',
      'PEG заново решает задачу наведения на цель из текущего положения с учётом ускорения, которое ещё дадут двигатели, и уточняет t_go на каждом цикле; поэтому она парирует отказ двигателя или более тяжёлую нагрузку. Ветер важен лишь в атмосфере, где полёт идёт по программе тангажа.',
      'PEG แก้ปัญหาการบังคับทิศไปยังเป้าหมายใหม่จากตำแหน่งปัจจุบัน โดยคำนึงถึงความเร่งที่เครื่องยนต์จะให้ต่อจากนี้ และปรับ t_go ทุกรอบ จึงรับมือเครื่องยนต์ดับหนึ่งตัวหรือสัมภาระที่หนักขึ้นได้ ลมมีผลเฉพาะในชั้นบรรยากาศซึ่งบินตามตารางพิตช์'),
    { lessons: ['guid-peg'] }),
  choice('g-kick-larger', 4, 2, U, 'guidance.kick',
    T('The pitch-over kick at T+10 s comes out 1° larger than planned, and the lower atmosphere is flown open loop. What happens?', 'Разворот по тангажу на T+10 с оказался на 1° больше расчётного, а в нижних слоях атмосферы полёт идёт по разомкнутой программе. Что произойдёт?', 'การเอียงตัว (kick) ที่ T+10 วินาทีมากกว่าแผน 1° และช่วงบรรยากาศชั้นล่างบินแบบวงเปิด จะเกิดอะไรขึ้น'),
    [O(T('The trajectory is flatter: more drag and a higher max-Q, and the closed loop must make up the difference later', 'Траектория становится более пологой: больше сопротивление и выше max-Q, а замкнутое наведение потом должно компенсировать разницу', 'เส้นทางบินราบลง แรงต้านมากขึ้น max-Q สูงขึ้น และระบบนำวิถีวงปิดต้องชดเชยภายหลัง'), true),
      O(T('Nothing: the guidance corrects it at once', 'Ничего: наведение сразу это исправит', 'ไม่มีอะไร ระบบนำวิถีแก้ทันที'), false,
        T('The guidance steers to the orbit from lift-off.', 'Наведение ведёт ракету к орбите с самого старта.', 'ระบบนำวิถีบังคับไปยังวงโคจรตั้งแต่ยกตัว')),
      O(T('The trajectory is steeper, with less drag', 'Траектория становится круче, сопротивление меньше', 'เส้นทางชันขึ้นและแรงต้านน้อยลง')),
      O(T('The rocket turns back to vertical, since the gravity turn cancels any error', 'Ракета вернётся к вертикали: гравитационный разворот гасит любую ошибку', 'จรวดจะกลับไปตั้งตรง เพราะการเลี้ยวด้วยแรงโน้มถ่วงลบล้างความคลาดเคลื่อนทุกอย่าง'))],
    T('After the kick gravity does the turning, and a larger kick grows into a flatter, depressed trajectory: lower through the dense air, faster, more drag and dynamic pressure. The explicit guidance above the atmosphere starts from wherever the ascent left it and pays the difference in propellant.',
      'После разворота поворот выполняет тяготение, и больший начальный разворот перерастает в более пологую траекторию: ниже в плотных слоях, быстрее, больше сопротивление и скоростной напор. Явное наведение выше атмосферы начинает с того состояния, в котором ракета оказалась, и оплачивает разницу топливом.',
      'หลังจากเอียงตัว แรงโน้มถ่วงทำหน้าที่เลี้ยว การเอียงมากขึ้นจะขยายเป็นเส้นทางที่ราบและต่ำกว่า อยู่ในอากาศหนาแน่นนานกว่า เร็วกว่า มีแรงต้านและความดันพลวัตมากกว่า การนำวิถีแบบชัดแจ้งเหนือบรรยากาศเริ่มจากสภาพที่จรวดอยู่และจ่ายส่วนต่างด้วยเชื้อเพลิง'),
    { lessons: ['guid-maxq'] }),
  numeric('g-launch-azimuth', 4, 3, K, 'guidance.azimuth',
    T('Ignoring the Earth\'s rotation, at what azimuth must a rocket launch from latitude {phi}° to reach an orbit of inclination {i}° directly, heading north-east (°)?', 'Без учёта вращения Земли: под каким азимутом должна стартовать ракета с широты {phi}°, чтобы прямо выйти на орбиту наклонением {i}°, двигаясь на северо-восток (°)?', 'หากไม่คิดการหมุนของโลก จรวดที่ปล่อยจากละติจูด {phi}° ต้องออกตัวที่มุมทิศ (azimuth) เท่าใด เพื่อเข้าสู่วงโคจรความเอียง {i}° โดยตรง มุ่งไปทางตะวันออกเฉียงเหนือ (°)'),
    [{ name: 'phi', min: 28, max: 46, step: 1 }, { name: 'i', min: 52, max: 65, step: 1 }], 'asin(cos(i) / cos(phi))', '°', 3,
    T('On a sphere, cos i = cos φ · sin Az, so sin Az = cos i / cos φ. From Baikonur (45.6°) to 51.6° this gives about 63°; the Earth\'s rotation, added to the velocity, shifts the real azimuth a few degrees.',
      'На сфере cos i = cos φ · sin Az, откуда sin Az = cos i / cos φ. С Байконура (45,6°) на 51,6° это около 63°; вращение Земли, добавляясь к скорости, сдвигает фактический азимут на несколько градусов.',
      'บนทรงกลม cos i = cos φ · sin Az ดังนั้น sin Az = cos i / cos φ จากไบโคนูร์ (45.6°) ไปยัง 51.6° จะได้ประมาณ 63° การหมุนของโลกที่บวกเข้ากับความเร็วทำให้มุมทิศจริงเลื่อนไปไม่กี่องศา'),
    { lessons: ['orbit-range-safety'] }),
  order('g-order-kalman', 4, 3, K, 'navigation.kalmanSteps',
    T('Put one cycle of a Kalman filter blending inertial navigation with GNSS in order.', 'Расположите шаги одного цикла фильтра Калмана, объединяющего инерциальную навигацию и ГНСС, по порядку.', 'เรียงลำดับขั้นตอนหนึ่งรอบของตัวกรองคาลมานที่รวมการนำทางเฉื่อยกับ GNSS'),
    [T('Propagate the state with the inertial measurements', 'Прогноз состояния по инерциальным измерениям', 'คาดการณ์สถานะด้วยการวัดเฉื่อย'),
      T('Let the uncertainty grow with the sensors\' noise', 'Рост неопределённости с учётом шумов датчиков', 'ปล่อยให้ความไม่แน่นอนเพิ่มขึ้นตามสัญญาณรบกวนของเซนเซอร์'),
      T('Compare the GNSS fix with the predicted position', 'Сравнение отсчёта ГНСС с прогнозом положения', 'เปรียบเทียบตำแหน่งจาก GNSS กับตำแหน่งที่คาดการณ์'),
      T('Weigh the difference by the Kalman gain', 'Взвешивание невязки коэффициентом усиления фильтра', 'ถ่วงน้ำหนักผลต่างด้วยอัตราขยายคาลมาน'),
      T('Correct the state and shrink the uncertainty', 'Коррекция состояния и уменьшение неопределённости', 'แก้สถานะและลดความไม่แน่นอน')],
    T('Predict, then update: the prediction runs at the IMU\'s rate and its uncertainty grows; each GNSS fix is weighed against it — trusted more when the prediction has drifted, less when the fix is noisy — and the corrected state starts the next prediction.',
      'Прогноз, затем коррекция: прогноз идёт с частотой ИИБ, и его неопределённость растёт; каждый отсчёт ГНСС взвешивается относительно прогноза — ему доверяют больше, когда прогноз ушёл, и меньше, когда отсчёт зашумлён, — и исправленное состояние начинает следующий прогноз.',
      'คาดการณ์แล้วปรับแก้: การคาดการณ์ทำตามอัตราของ IMU และความไม่แน่นอนเพิ่มขึ้น ตำแหน่งจาก GNSS แต่ละครั้งถูกถ่วงน้ำหนักเทียบกับการคาดการณ์ เชื่อมากขึ้นเมื่อการคาดการณ์เลื่อนไป เชื่อน้อยลงเมื่อ GNSS มีสัญญาณรบกวน แล้วสถานะที่แก้แล้วเป็นจุดเริ่มของการคาดการณ์ครั้งถัดไป'),
    { lessons: ['guid-nav'] }),
  choice('g-open-loop', 4, 1, K, 'guidance.openLoop',
    T('Through the dense lower atmosphere, most launchers steer…', 'В плотных нижних слоях атмосферы большинство ракет-носителей управляется…', 'ในชั้นบรรยากาศล่างที่หนาแน่น จรวดนำส่งส่วนใหญ่บังคับทิศ…'),
    [O(T('…by a pitch programme worked out before flight, holding the angle of attack near zero', '…по программе тангажа, рассчитанной до полёта, с углом атаки около нуля', '…ตามโปรแกรมพิตช์ที่คำนวณไว้ก่อนบิน โดยรักษามุมปะทะให้ใกล้ศูนย์'), true),
      O(T('…by closed-loop guidance aimed at the orbit from the moment of lift-off', '…замкнутым наведением на орбиту с момента старта', '…ด้วยการนำวิถีวงปิดที่เล็งไปยังวงโคจรตั้งแต่ยกตัว')),
      O(T('…by GNSS alone', '…только по ГНСС', '…ด้วย GNSS เพียงอย่างเดียว')),
      O(T('…by a pilot in the crewed ones', '…пилотом — в пилотируемых', '…โดยนักบินในจรวดที่มีมนุษย์'))],
    T('In the dense air an angle of attack means a side load the structure must carry, so the ascent follows a pre-planned, load-relieving pitch programme; closed-loop explicit guidance takes over above the atmosphere.',
      'В плотном воздухе угол атаки означает поперечную нагрузку на конструкцию, поэтому выведение идёт по заранее рассчитанной программе тангажа, разгружающей конструкцию; замкнутое явное наведение включается выше атмосферы.',
      'ในอากาศหนาแน่น มุมปะทะหมายถึงแรงด้านข้างที่โครงสร้างต้องรับ การไต่ระดับจึงบินตามโปรแกรมพิตช์ที่วางแผนไว้ก่อนเพื่อลดภาระ แล้วการนำวิถีแบบชัดแจ้งวงปิดจึงรับช่วงเหนือชั้นบรรยากาศ'),
    { lessons: ['guid-maxq'] }),
];
