/** Area 2, orbital mechanics (roadmap E03). */
import { O, T, U, K, choice, numeric } from './helpers';

const CONST = T(' Take R = 6 378 km and μ = 398 600 km³/s².', ' Примите R = 6 378 км и μ = 398 600 км³/с².', ' ใช้ R = 6 378 กม. และ μ = 398 600 กม.³/วินาที²');
const withConst = (t: { en: string; ru: string; th: string }) => T(t.en + CONST.en, t.ru + CONST.ru, t.th + CONST.th);

export const ORBITS: readonly unknown[] = [
  choice('o-perigee', 2, 1, K, 'orbit.terms',
    T('What is the perigee of an orbit round the Earth?', 'Что такое перигей орбиты вокруг Земли?', 'จุดใกล้โลก (perigee) ของวงโคจรรอบโลกคืออะไร'),
    [O(T('The point of the orbit nearest the Earth', 'Ближайшая к Земле точка орбиты', 'จุดบนวงโคจรที่อยู่ใกล้โลกที่สุด'), true),
      O(T('The point farthest from the Earth', 'Наиболее удалённая от Земли точка', 'จุดที่อยู่ไกลโลกที่สุด')),
      O(T('Where the orbit crosses the equator going north', 'Точка, где орбита пересекает экватор с юга на север', 'จุดที่วงโคจรตัดเส้นศูนย์สูตรขณะขึ้นไปทางเหนือ')),
      O(T('The highest point of the rocket\'s ascent', 'Высшая точка участка выведения', 'จุดสูงสุดของเส้นทางไต่ระดับของจรวด'))],
    T('Perigee is the nearest point and apogee the farthest; the crossing of the equator northbound is the ascending node.',
      'Перигей — ближайшая точка, апогей — наиболее удалённая; пересечение экватора с юга на север — восходящий узел.',
      'จุดใกล้โลกคือจุดที่ใกล้ที่สุด จุดไกลโลกคือจุดที่ไกลที่สุด ส่วนจุดที่ตัดเส้นศูนย์สูตรขึ้นไปทางเหนือคือโหนดขึ้น'),
    { lessons: ['orbit-first'] }),
  choice('o-equatorial', 2, 1, K, 'orbit.inclination',
    T('What is the inclination of an orbit that lies exactly in the plane of the equator, going east?', 'Каково наклонение орбиты, лежащей точно в плоскости экватора, с движением на восток?', 'วงโคจรที่อยู่ในระนาบเส้นศูนย์สูตรพอดีและเคลื่อนไปทางตะวันออก มีความเอียงเท่าใด'),
    [O(T('0°', '0°', '0°'), true), O(T('90°', '90°', '90°')), O(T('180°', '180°', '180°')), O(T('23.4°, the tilt of the Earth\'s axis', '23,4°, наклон земной оси', '23.4° เท่ากับความเอียงของแกนโลก'))],
    T('Inclination is the angle between the orbit\'s plane and the equator\'s: 0° equatorial and prograde, 90° polar, 180° equatorial going west.',
      'Наклонение — угол между плоскостью орбиты и плоскостью экватора: 0° — экваториальная прямая, 90° — полярная, 180° — экваториальная обратная.',
      'ความเอียงคือมุมระหว่างระนาบวงโคจรกับระนาบเส้นศูนย์สูตร 0° คือวงโคจรเส้นศูนย์สูตรไปทางตะวันออก 90° คือวงโคจรขั้วโลก และ 180° คือวงโคจรเส้นศูนย์สูตรไปทางตะวันตก'),
    { fixedOrder: true }),
  choice('o-kepler3', 2, 1, K, 'orbit.kepler3',
    T('Kepler\'s third law relates…', 'Третий закон Кеплера связывает…', 'กฎข้อที่สามของเคปเลอร์เชื่อมโยง…'),
    [O(T('…the square of the period to the cube of the semi-major axis', '…квадрат периода с кубом большой полуоси', '…กำลังสองของคาบกับกำลังสามของกึ่งแกนเอก'), true),
      O(T('…the speed at perigee to the speed at apogee', '…скорость в перигее со скоростью в апогее', '…อัตราเร็วที่จุดใกล้โลกกับที่จุดไกลโลก')),
      O(T('…the mass of the satellite to its period', '…массу спутника с его периодом', '…มวลของดาวเทียมกับคาบ')),
      O(T('…the inclination to the latitude of the launch site', '…наклонение с широтой космодрома', '…ความเอียงกับละติจูดของฐานปล่อย'))],
    T('T² = 4π²a³/μ. The satellite\'s own mass does not appear: a feather and a station on the same orbit go round together.',
      'T² = 4π²a³/μ. Масса самого спутника в закон не входит: пёрышко и станция на одной орбите движутся вместе.',
      'T² = 4π²a³/μ มวลของดาวเทียมไม่ปรากฏในกฎ ขนนกกับสถานีอวกาศบนวงโคจรเดียวกันจะโคจรไปด้วยกัน'),
    { lessons: ['orbit-first'] }),
  choice('o-raan', 2, 1, K, 'orbit.raan',
    T('What does the longitude of the ascending node Ω fix?', 'Что задаёт долгота восходящего узла Ω?', 'ลองจิจูดของโหนดขึ้น Ω กำหนดอะไร'),
    [O(T('Which way the orbit\'s plane faces in space, measured from the vernal equinox', 'Ориентацию плоскости орбиты в пространстве, отсчитываемую от точки весеннего равноденствия', 'ทิศทางของระนาบวงโคจรในอวกาศ วัดจากจุดวสันตวิษุวัต'), true),
      O(T('The height of the orbit', 'Высоту орбиты', 'ความสูงของวงโคจร')),
      O(T('The shape of the orbit', 'Форму орбиты', 'รูปร่างของวงโคจร')),
      O(T('The longitude on the ground below the satellite', 'Географическую долготу подспутниковой точки', 'ลองจิจูดบนพื้นโลกใต้ดาวเทียม'))],
    T('Inclination tilts the plane; Ω turns it about the Earth\'s axis. Together they fix the plane — the ISS lesson is about matching both.',
      'Наклонение задаёт наклон плоскости, Ω — её поворот вокруг оси Земли. Вместе они определяют плоскость; урок про МКС посвящён совмещению обоих.',
      'ความเอียงกำหนดการเอียงของระนาบ ส่วน Ω กำหนดการหมุนของระนาบรอบแกนโลก ทั้งสองค่าร่วมกันกำหนดระนาบ บทเรียนเรื่อง ISS คือการทำให้ทั้งสองค่าตรงกัน'),
    { lessons: ['orbit-iss-plane'] }),
  choice('o-min-inclination', 2, 1, U, 'launch.latitude',
    T('What is the lowest inclination a rocket can reach directly, launching from latitude 46° N?', 'Какое наименьшее наклонение может получить ракета при прямом выведении со широты 46° с. ш.?', 'จรวดที่ปล่อยจากละติจูด 46° เหนือ เข้าสู่วงโคจรที่มีความเอียงต่ำสุดได้เท่าใดโดยตรง'),
    [O(T('46°', '46°', '46°'), true),
      O(T('0°, by launching due east', '0°, если стартовать строго на восток', '0° ถ้าปล่อยไปทางตะวันออกตรง ๆ'), false,
        T('launching due east gives an equatorial orbit from anywhere', 'старт строго на восток даёт экваториальную орбиту откуда угодно', 'การปล่อยไปทางตะวันออกตรง ๆ ให้วงโคจรเส้นศูนย์สูตรได้จากทุกที่')),
      O(T('23.4°', '23,4°', '23.4°')),
      O(T('90°', '90°', '90°'))],
    T('Every orbit\'s plane passes through the Earth\'s centre and the launch site, so the site\'s latitude is the least inclination it can reach: cos i = cos φ·sin A is at most cos φ. Lower needs a plane change later.',
      'Плоскость любой орбиты проходит через центр Земли и точку старта, поэтому широта космодрома — наименьшее достижимое наклонение: cos i = cos φ·sin A не больше cos φ. Меньшее требует последующего поворота плоскости.',
      'ระนาบวงโคจรทุกวงผ่านศูนย์กลางโลกและจุดปล่อย ละติจูดของฐานจึงเป็นความเอียงต่ำสุดที่ทำได้ เพราะ cos i = cos φ·sin A มีค่าไม่เกิน cos φ หากต้องการต่ำกว่านั้นต้องเปลี่ยนระนาบภายหลัง'),
    { lessons: ['orbit-range-safety', 'orbit-iss-plane'] }),
  numeric('o-circular-speed', 2, 2, K, 'orbit.speed',
    withConst(T('Work out the speed on a circular orbit {h} km up (km/s).', 'Рассчитайте скорость на круговой орбите высотой {h} км (км/с).', 'คำนวณอัตราเร็วบนวงโคจรวงกลมที่ความสูง {h} กม. (กม./วินาที)')),
    [{ name: 'h', min: 250, max: 1500, step: 50 }], 'sqrt(mu / (R + h * 1000)) / 1000', 'km/s', 1,
    T('v = √(μ/r) with r = R + h. Remember to add the Earth\'s radius: the orbit\'s radius is measured from the centre.',
      'v = √(μ/r), где r = R + h. Не забудьте прибавить радиус Земли: радиус орбиты отсчитывается от центра.',
      'v = √(μ/r) โดย r = R + h อย่าลืมบวกรัศมีโลก เพราะรัศมีวงโคจรวัดจากศูนย์กลางโลก'),
    { lessons: ['orbit-first'] }),
  numeric('o-period', 2, 2, K, 'orbit.period',
    withConst(T('Work out the period of a circular orbit {h} km up (min).', 'Рассчитайте период круговой орбиты высотой {h} км (мин).', 'คำนวณคาบของวงโคจรวงกลมที่ความสูง {h} กม. (นาที)')),
    [{ name: 'h', min: 250, max: 2000, step: 50 }], '2 * pi * sqrt((R + h * 1000)^3 / mu) / 60', 'min', 1,
    T('T = 2π√(r³/μ), in seconds when r is in metres and μ in m³/s²; divide by 60 for minutes.',
      'T = 2π√(r³/μ) — в секундах, если r в метрах и μ в м³/с²; для минут разделите на 60.',
      'T = 2π√(r³/μ) มีหน่วยเป็นวินาทีเมื่อ r เป็นเมตรและ μ เป็น ม.³/วินาที² หารด้วย 60 เพื่อให้เป็นนาที'),
    { lessons: ['orbit-first'] }),
  choice('o-window', 2, 2, U, 'launch.window',
    T('Why can a Soyuz to the space station leave Baikonur only at one moment each day?', 'Почему «Союз» к МКС может стартовать с Байконура лишь в определённый момент каждых суток?', 'ทำไมโซยุซที่จะไปสถานีอวกาศจึงออกจากไบโคนูร์ได้เพียงช่วงเวลาเดียวในแต่ละวัน'),
    [O(T('The station\'s orbital plane is fixed in space; the pad passes through it only as the Earth turns', 'Плоскость орбиты станции неподвижна в пространстве, а стартовый комплекс проходит через неё только за счёт вращения Земли', 'ระนาบวงโคจรของสถานีคงที่ในอวกาศ ฐานปล่อยจะผ่านระนาบนั้นก็ต่อเมื่อโลกหมุนไปถึง'), true),
      O(T('The station must be passing right overhead at launch', 'Станция должна пролетать прямо над стартом', 'สถานีต้องบินผ่านเหนือฐานปล่อยพอดีขณะปล่อย'), false,
        T('the window is about where the station is, not about where its plane is', 'окно определяется положением станции, а не её плоскостью', 'หน้าต่างการปล่อยขึ้นกับตำแหน่งของสถานี ไม่ใช่ระนาบของมัน')),
      O(T('The weather at Baikonur is only good once a day', 'Погода на Байконуре хороша лишь раз в сутки', 'สภาพอากาศที่ไบโคนูร์ดีเพียงวันละครั้ง')),
      O(T('The rocket must launch in darkness', 'Ракета должна стартовать в темноте', 'จรวดต้องปล่อยในความมืด'))],
    T('The plane matters most, because turning a plane is very expensive. Where the station is along that plane is fixed later by phasing: the Soyuz catches up over two to thirty-four orbits.',
      'Главное — плоскость, потому что её поворот очень дорог. Положение станции в этой плоскости выравнивают потом, фазированием: «Союз» догоняет её за два–тридцать четыре витка.',
      'ระนาบสำคัญที่สุด เพราะการหมุนระนาบสิ้นเปลืองมาก ส่วนตำแหน่งของสถานีบนระนาบนั้นจะปรับภายหลังด้วยการปรับเฟส โซยุซจะไล่ตามสถานีภายในสองถึงสามสิบสี่รอบโคจร'),
    { lessons: ['orbit-iss-plane'] }),
  choice('o-two-burns', 2, 2, U, 'orbit.hohmann',
    T('To go from one circular orbit to a higher circular orbit in the same plane with least propellant, a spacecraft needs…', 'Чтобы с наименьшим расходом перейти с одной круговой орбиты на более высокую в той же плоскости, аппарату нужно…', 'หากต้องการย้ายจากวงโคจรวงกลมหนึ่งไปวงโคจรวงกลมที่สูงกว่าในระนาบเดียวกันโดยใช้เชื้อเพลิงน้อยที่สุด ยานต้อง…'),
    [O(T('…two burns: one to enter a transfer ellipse, one at its apogee', '…два импульса: вход на переходный эллипс и импульс в его апогее', '…จุดเครื่องสองครั้ง: ครั้งแรกเข้าสู่วงรีถ่ายโอน ครั้งที่สองที่จุดไกลโลกของวงรี'), true),
      O(T('…one long burn pointing straight up', '…одно долгое включение вертикально вверх', '…จุดเครื่องครั้งเดียวนาน ๆ โดยชี้ขึ้นตรง'), false,
        T('to go higher you thrust upwards', 'чтобы подняться выше, нужно тянуть вверх', 'ถ้าจะขึ้นสูงต้องดันขึ้นข้างบน')),
      O(T('…one burn: the orbit comes out circular by itself', '…один импульс: орбита сама станет круговой', '…จุดเครื่องครั้งเดียว วงโคจรจะกลายเป็นวงกลมเอง')),
      O(T('…continuous thrust all the way round', '…непрерывная тяга на протяжении всего витка', '…แรงขับต่อเนื่องตลอดทั้งรอบ'))],
    T('One burn only makes an ellipse whose perigee is the burn point. The Hohmann transfer adds a second burn at the apogee to raise the perigee.',
      'Один импульс даёт лишь эллипс с перигеем в точке включения. Гомановский перелёт добавляет второй импульс в апогее, поднимающий перигей.',
      'การจุดเครื่องครั้งเดียวให้เพียงวงรีที่มีจุดใกล้โลกอยู่ที่ตำแหน่งจุดเครื่อง การถ่ายโอนแบบโฮมันน์จึงเพิ่มการจุดเครื่องครั้งที่สองที่จุดไกลโลกเพื่อยกจุดใกล้โลกขึ้น'),
    { lessons: ['orbit-hohmann'] }),
  choice('o-sso', 2, 2, K, 'orbit.sso',
    T('A sun-synchronous orbit 600 km up has an inclination of about 98°. Why slightly more than 90°?', 'Солнечно-синхронная орбита высотой 600 км имеет наклонение около 98°. Почему чуть больше 90°?', 'วงโคจรสัมพันธ์กับดวงอาทิตย์ที่ความสูง 600 กม. มีความเอียงประมาณ 98° ทำไมจึงมากกว่า 90° เล็กน้อย'),
    [O(T('The Earth\'s equatorial bulge turns such a plane eastward about 1° a day, keeping pace with the Sun', 'Экваториальное утолщение Земли поворачивает такую плоскость на восток примерно на 1° в сутки — вслед за Солнцем', 'ส่วนป่องที่เส้นศูนย์สูตรของโลกหมุนระนาบนั้นไปทางตะวันออกประมาณวันละ 1° ให้ทันดวงอาทิตย์'), true),
      O(T('The Sun\'s gravity pulls the orbit towards it', 'Притяжение Солнца наклоняет орбиту к себе', 'แรงโน้มถ่วงของดวงอาทิตย์ดึงวงโคจรเข้าหา')),
      O(T('To avoid flying over the poles', 'Чтобы не пролетать над полюсами', 'เพื่อเลี่ยงการบินผ่านขั้วโลก')),
      O(T('Because launch sites cannot reach exactly 90°', 'Потому что с космодромов нельзя попасть ровно в 90°', 'เพราะฐานปล่อยไม่สามารถปล่อยได้ 90° พอดี'))],
    T('The J2 term of the Earth\'s gravity precesses an orbit\'s node. A slightly retrograde plane at this height precesses +0.986°/day, once a year — so the satellite passes over each place at the same local time.',
      'Член J2 гравитационного поля Земли вызывает прецессию узла орбиты. Слегка обратная плоскость на этой высоте прецессирует на +0,986°/сут — один оборот в год, и спутник пролетает над каждым местом в одно и то же местное время.',
      'พจน์ J2 ของสนามโน้มถ่วงโลกทำให้โหนดของวงโคจรส่ายไป ระนาบที่ถอยหลังเล็กน้อยที่ระดับนี้ส่ายไป +0.986° ต่อวัน ครบรอบในหนึ่งปี ดาวเทียมจึงผ่านทุกจุดในเวลาท้องถิ่นเดียวกัน')),
  choice('o-plane-burn', 2, 2, U, 'orbit.plane',
    T('A satellite fires its engine at right angles to its orbital plane. What changes?', 'Спутник включает двигатель перпендикулярно плоскости своей орбиты. Что изменится?', 'ดาวเทียมจุดเครื่องยนต์ในทิศตั้งฉากกับระนาบวงโคจร อะไรจะเปลี่ยน'),
    [O(T('The orientation of its orbital plane', 'Ориентация плоскости орбиты', 'ทิศทางของระนาบวงโคจร'), true),
      O(T('Only its altitude', 'Только высота', 'เฉพาะความสูง')),
      O(T('Only its period', 'Только период', 'เฉพาะคาบ')),
      O(T('Nothing: sideways thrust has no effect in orbit', 'Ничего: боковая тяга на орбите не действует', 'ไม่มีอะไรเปลี่ยน แรงขับด้านข้างไม่มีผลในวงโคจร'), false,
        T('only thrust along the motion changes an orbit', 'орбиту меняет лишь тяга вдоль движения', 'มีเพียงแรงขับตามทิศการเคลื่อนที่เท่านั้นที่เปลี่ยนวงโคจรได้'))],
    T('A burn along the orbit\'s normal turns the velocity out of the plane: the plane rotates about the line to the burn point. Made at a node it changes the inclination; elsewhere it also moves Ω.',
      'Импульс по нормали к орбите выводит скорость из плоскости: плоскость поворачивается вокруг линии, проходящей через точку включения. В узле меняется наклонение, в другой точке — ещё и Ω.',
      'การจุดเครื่องตามแนวตั้งฉากกับวงโคจรทำให้ความเร็วเบนออกนอกระนาบ ระนาบจึงหมุนรอบแนวที่ผ่านจุดจุดเครื่อง ถ้าทำที่โหนดจะเปลี่ยนความเอียง ถ้าทำที่ตำแหน่งอื่นจะเปลี่ยน Ω ด้วย')),
  choice('o-molniya', 2, 2, K, 'orbit.molniya',
    T('Why do Molniya orbits have an inclination of 63.4°?', 'Почему у орбит типа «Молния» наклонение 63,4°?', 'ทำไมวงโคจรแบบโมลนิยาจึงมีความเอียง 63.4°'),
    [O(T('At that inclination the Earth\'s bulge does not turn the perigee round, so the apogee stays over the north', 'При таком наклонении сжатие Земли не поворачивает линию апсид, и апогей остаётся над северным полушарием', 'ที่ความเอียงนี้ส่วนป่องของโลกไม่ทำให้จุดใกล้โลกหมุนไป จุดไกลโลกจึงค้างอยู่เหนือซีกโลกเหนือ'), true),
      O(T('It is the latitude of Moscow', 'Это широта Москвы', 'เป็นละติจูดของมอสโก')),
      O(T('It is the lowest inclination Plesetsk can reach', 'Это наименьшее наклонение, доступное Плесецку', 'เป็นความเอียงต่ำสุดที่เพลเซตสค์ทำได้')),
      O(T('It gives exactly a 12-hour period', 'Оно даёт ровно 12-часовой период', 'ทำให้คาบเท่ากับ 12 ชั่วโมงพอดี'))],
    T('The apsidal precession from J2 is proportional to (5cos²i − 1), which is zero at 63.4° — the critical inclination. The 12-hour period comes from the semi-major axis, not the inclination.',
      'Прецессия линии апсид от J2 пропорциональна (5cos²i − 1) и равна нулю при 63,4° — критическом наклонении. 12-часовой период определяется большой полуосью, а не наклонением.',
      'การส่ายของแนวแอปไซด์จาก J2 แปรผันตาม (5cos²i − 1) ซึ่งเป็นศูนย์ที่ 63.4° เรียกว่าความเอียงวิกฤต ส่วนคาบ 12 ชั่วโมงมาจากกึ่งแกนเอก ไม่ใช่ความเอียง')),
  numeric('o-hohmann-first', 2, 3, K, 'orbit.hohmann',
    withConst(T('A spacecraft on a circular orbit {h1} km up starts a Hohmann transfer to a circular orbit {h2} km up. Work out the Δv of the first burn (m/s).',
      'Аппарат на круговой орбите высотой {h1} км начинает гомановский перелёт на круговую орбиту высотой {h2} км. Рассчитайте Δv первого импульса (м/с).',
      'ยานบนวงโคจรวงกลมสูง {h1} กม. เริ่มการถ่ายโอนแบบโฮมันน์ไปยังวงโคจรวงกลมสูง {h2} กม. คำนวณ Δv ของการจุดเครื่องครั้งแรก (ม./วินาที)')),
    [{ name: 'h1', min: 200, max: 400, step: 20 }, { name: 'h2', min: 800, max: 2000, step: 100 }],
    'sqrt(mu / (R + h1 * 1000)) * (sqrt(2 * (R + h2 * 1000) / ((R + h1 * 1000) + (R + h2 * 1000))) - 1)', 'm/s', 3,
    T('Δv₁ = √(μ/r₁)·(√(2r₂/(r₁+r₂)) − 1): the speed at perigee of the transfer ellipse, less the circular speed where the burn is made.',
      'Δv₁ = √(μ/r₁)·(√(2r₂/(r₁+r₂)) − 1): скорость в перигее переходного эллипса минус круговая скорость в точке включения.',
      'Δv₁ = √(μ/r₁)·(√(2r₂/(r₁+r₂)) − 1) คืออัตราเร็วที่จุดใกล้โลกของวงรีถ่ายโอน ลบด้วยอัตราเร็ววงกลม ณ ตำแหน่งที่จุดเครื่อง'),
    { lessons: ['orbit-hohmann'] }),
  numeric('o-plane-change', 2, 3, K, 'orbit.plane',
    T('A satellite moving at {v} km/s turns its orbital plane by {di}° in one burn at the node, keeping its speed. Work out the Δv (m/s).',
      'Спутник, движущийся со скоростью {v} км/с, одним импульсом в узле поворачивает плоскость орбиты на {di}°, сохраняя величину скорости. Рассчитайте Δv (м/с).',
      'ดาวเทียมที่เคลื่อนที่ด้วยอัตราเร็ว {v} กม./วินาที หมุนระนาบวงโคจรไป {di}° ด้วยการจุดเครื่องครั้งเดียวที่โหนดโดยคงอัตราเร็วไว้ คำนวณ Δv (ม./วินาที)'),
    [{ name: 'v', min: 1.6, max: 7.8, step: 0.1 }, { name: 'di', min: 2, max: 30, step: 1 }], '2 * v * 1000 * sin(di / 2)', 'm/s', 2,
    T('Δv = 2v·sin(Δi/2): the chord between two velocity vectors of equal length. It is why geostationary satellites make their plane change at apogee, where v is smallest.',
      'Δv = 2v·sin(Δi/2) — хорда между двумя векторами скорости одинаковой длины. Поэтому геостационарные спутники поворачивают плоскость в апогее, где скорость наименьшая.',
      'Δv = 2v·sin(Δi/2) คือคอร์ดระหว่างเวกเตอร์ความเร็วสองเวกเตอร์ที่ยาวเท่ากัน ดาวเทียมค้างฟ้าจึงเปลี่ยนระนาบที่จุดไกลโลกซึ่ง v มีค่าน้อยที่สุด'),
    { lessons: ['orbit-iss-plane'] }),
  choice('o-catch-up', 2, 3, U, 'orbit.phasing',
    T('Two spacecraft share a circular orbit; the chaser is 10 km behind the target. To catch up with the least propellant it should first…', 'Два аппарата на одной круговой орбите; догоняющий отстаёт на 10 км. Чтобы догнать цель с наименьшим расходом, он должен сначала…', 'ยานสองลำอยู่บนวงโคจรวงกลมเดียวกัน ยานไล่ตามอยู่ข้างหลังเป้าหมาย 10 กม. เพื่อไล่ทันโดยใช้เชื้อเพลิงน้อยที่สุด ยานไล่ตามควร…'),
    [O(T('…brake a little, dropping into a lower and faster orbit', '…немного притормозить и перейти на более низкую, более быструю орбиту', '…ชะลอความเร็วเล็กน้อย เพื่อลดลงสู่วงโคจรที่ต่ำกว่าและเร็วกว่า'), true),
      O(T('…fire forwards to speed up towards the target', '…включить двигатель вперёд и разогнаться к цели', '…จุดเครื่องไปข้างหน้าเพื่อเร่งเข้าหาเป้าหมาย'), false,
        T('speeding up along the orbit brings you closer to a target ahead', 'разгон вдоль орбиты приближает к цели, идущей впереди', 'การเร่งความเร็วตามวงโคจรจะพาเข้าใกล้เป้าหมายที่อยู่ข้างหน้า')),
      O(T('…fire straight towards the target', '…включить двигатель прямо на цель', '…จุดเครื่องพุ่งตรงไปยังเป้าหมาย')),
      O(T('…do nothing: they will meet in half an orbit', '…ничего не делать: они встретятся через пол-витка', '…ไม่ต้องทำอะไร จะพบกันเองในครึ่งรอบ'))],
    T('Speeding up raises the orbit and lengthens the period, so the chaser falls further behind. Braking lowers it and shortens the period: the chaser gains on the target each revolution and later brakes back up. This is phasing.',
      'Разгон поднимает орбиту и удлиняет период — догоняющий отстаёт ещё сильнее. Торможение понижает орбиту и сокращает период: за каждый виток догоняющий выигрывает у цели, а затем поднимается обратно. Это фазирование.',
      'การเร่งทำให้วงโคจรสูงขึ้นและคาบยาวขึ้น ยานไล่ตามจึงตกห่างมากขึ้น การชะลอทำให้วงโคจรต่ำลงและคาบสั้นลง ยานไล่ตามจึงได้ระยะคืนทุกรอบ แล้วค่อยยกวงโคจรกลับ นี่คือการปรับเฟส'),
    { lessons: ['adv-docking'] }),
  choice('o-geo-latitude', 2, 3, U, 'orbit.plane',
    T('Why does a satellite launched to geostationary orbit from Baikonur need more Δv than one launched from Kourou?', 'Почему спутнику, выводимому на геостационарную орбиту с Байконура, нужно больше Δv, чем при пуске с Куру?', 'ทำไมดาวเทียมที่ปล่อยจากไบโคนูร์ไปวงโคจรค้างฟ้าจึงต้องใช้ Δv มากกว่าดาวเทียมที่ปล่อยจากคูรู'),
    [O(T('It starts with an inclination of at least 46° and must turn its plane to 0°', 'Он начинает с наклонением не менее 46° и должен повернуть плоскость до 0°', 'มันเริ่มด้วยความเอียงอย่างน้อย 46° และต้องหมุนระนาบลงมาเป็น 0°'), true),
      O(T('Baikonur is higher above sea level', 'Байконур расположен выше над уровнем моря', 'ไบโคนูร์อยู่สูงจากระดับน้ำทะเลมากกว่า')),
      O(T('The air over the steppe is denser', 'Воздух над степью плотнее', 'อากาศเหนือทุ่งหญ้าสเตปป์หนาแน่นกว่า')),
      O(T('The Earth turns faster at Baikonur\'s latitude', 'На широте Байконура Земля вращается быстрее', 'โลกหมุนเร็วกว่าที่ละติจูดของไบโคนูร์'), false,
        T('the ground moves faster away from the equator', 'поверхность движется быстрее вдали от экватора', 'พื้นผิวโลกเคลื่อนเร็วขึ้นเมื่อห่างจากเส้นศูนย์สูตร'))],
    T('From 46° the transfer orbit is inclined at least 46°, and the plane change at apogee costs about 1.5 km/s more than Kourou\'s 5°. The ground at Baikonur also moves slower, 324 against 463 m/s.',
      'С широты 46° переходная орбита имеет наклонение не менее 46°, и поворот плоскости в апогее стоит примерно на 0,8 км/с больше, чем при 5° с Куру. К тому же поверхность на Байконуре движется медленнее: 324 против 463 м/с.',
      'จากละติจูด 46° วงโคจรถ่ายโอนจะเอียงอย่างน้อย 46° การเปลี่ยนระนาบที่จุดไกลโลกจึงใช้มากกว่าการปล่อยจากคูรูซึ่งเอียงเพียง 5° ราว 0.8 กม./วินาที อีกทั้งพื้นผิวที่ไบโคนูร์ยังเคลื่อนช้ากว่า คือ 324 เทียบกับ 463 ม./วินาที')),
  numeric('o-perigee-speed', 2, 3, K, 'orbit.visviva',
    withConst(T('An orbit has its perigee {hp} km and its apogee {ha} km above the Earth. Work out the speed at perigee (km/s).',
      'Перигей орбиты — {hp} км, апогей — {ha} км над Землёй. Рассчитайте скорость в перигее (км/с).',
      'วงโคจรมีจุดใกล้โลกสูง {hp} กม. และจุดไกลโลกสูง {ha} กม. คำนวณอัตราเร็วที่จุดใกล้โลก (กม./วินาที)')),
    [{ name: 'hp', min: 180, max: 400, step: 20 }, { name: 'ha', min: 1000, max: 36000, step: 1000 }],
    'sqrt(mu * (2 / (R + hp * 1000) - 2 / ((R + hp * 1000) + (R + ha * 1000)))) / 1000', 'km/s', 1,
    T('vis-viva: v² = μ(2/r − 1/a), with r the perigee radius and a the mean of the perigee and apogee radii.',
      'Интеграл энергии: v² = μ(2/r − 1/a), где r — радиус перигея, a — среднее радиусов перигея и апогея.',
      'vis-viva: v² = μ(2/r − 1/a) โดย r คือรัศมีที่จุดใกล้โลก และ a คือค่าเฉลี่ยของรัศมีจุดใกล้โลกกับจุดไกลโลก'),
    { lessons: ['orbit-hohmann'] }),
];
