/** Area 2, orbital mechanics (roadmap E03). */
import { K, O, T, U, choice, diagram, letters, multi, numeric, order } from './helpers';

const CONST = T(' Take R = 6 378 km and μ = 398 600 km³/s².', ' Примите R = 6 378 км и μ = 398 600 км³/с².', ' ใช้ R = 6 378 กม. และ μ = 398 600 กม.³/วินาที²');
const withConst = (t: { en: string; ru: string; th: string }) => T(t.en + CONST.en, t.ru + CONST.ru, t.th + CONST.th);

export const ORBITS: readonly unknown[] = [
  choice('o-perigee', 2, 1, K, 'orbit.terms',
    T('What is the perigee of an orbit round the Earth?', 'Что такое перигей орбиты вокруг Земли?', 'จุดใกล้โลก (perigee) ของวงโคจรรอบโลกคืออะไร'),
    [O(T('The point of the orbit nearest the Earth', 'Ближайшая к Земле точка орбиты', 'จุดบนวงโคจรที่อยู่ใกล้โลกที่สุด'), true),
      O(T('The point farthest from the Earth', 'Наиболее удалённая от Земли точка', 'จุดที่อยู่ไกลโลกที่สุด')),
      O(T('Where the orbit crosses the equator going north', 'Точка, где орбита пересекает экватор с юга на север', 'จุดที่วงโคจรตัดเส้นศูนย์สูตรขณะขึ้นไปทางเหนือ')),
      O(T('The highest point of the rocket\'s ascent', 'Высшая точка участка выведения', 'จุดสูงสุดของเส้นทางไต่ระดับของจรวด'))],
    T('Perigee is the nearest point and apogee the farthest; the crossing of the equator northbound is the ascending node.',
      'Перигей — ближайшая точка, апогей — наиболее удалённая; пересечение экватора с юга на север — восходящий узел.',
      'จุดใกล้โลกคือจุดที่ใกล้ที่สุด จุดไกลโลกคือจุดที่ไกลที่สุด ส่วนจุดที่ตัดเส้นศูนย์สูตรขึ้นไปทางเหนือคือโหนดขึ้น'),
    { lessons: ['orbit-first'] }),
  choice('o-equatorial', 2, 1, K, 'orbit.inclination',
    T('What is the inclination of an orbit that lies exactly in the plane of the equator, going east?', 'Каково наклонение орбиты, лежащей точно в плоскости экватора, с движением на восток?', 'วงโคจรที่อยู่ในระนาบเส้นศูนย์สูตรพอดีและเคลื่อนไปทางตะวันออก มีความเอียงเท่าใด'),
    [O(T('0°', '0°', '0°'), true), O(T('90°', '90°', '90°')), O(T('180°', '180°', '180°')), O(T('23.4°, the tilt of the Earth\'s axis', '23,4°, наклон земной оси', '23.4° เท่ากับความเอียงของแกนโลก'))],
    T('Inclination is the angle between the orbit\'s plane and the equator\'s: 0° equatorial and prograde, 90° polar, 180° equatorial going west.',
      'Наклонение — угол между плоскостью орбиты и плоскостью экватора: 0° — экваториальная прямая, 90° — полярная, 180° — экваториальная обратная.',
      'ความเอียงคือมุมระหว่างระนาบวงโคจรกับระนาบเส้นศูนย์สูตร 0° คือวงโคจรเส้นศูนย์สูตรไปทางตะวันออก 90° คือวงโคจรขั้วโลก และ 180° คือวงโคจรเส้นศูนย์สูตรไปทางตะวันตก'),
    { fixedOrder: true }),
  choice('o-kepler3', 2, 1, K, 'orbit.kepler3',
    T('Kepler\'s third law relates…', 'Третий закон Кеплера связывает…', 'กฎข้อที่สามของเคปเลอร์เชื่อมโยง…'),
    [O(T('…the square of the period to the cube of the semi-major axis', '…квадрат периода с кубом большой полуоси', '…กำลังสองของคาบกับกำลังสามของกึ่งแกนเอก'), true),
      O(T('…the speed at perigee to the speed at apogee', '…скорость в перигее со скоростью в апогее', '…อัตราเร็วที่จุดใกล้โลกกับที่จุดไกลโลก')),
      O(T('…the mass of the satellite to its period', '…массу спутника с его периодом', '…มวลของดาวเทียมกับคาบ')),
      O(T('…the inclination to the latitude of the launch site', '…наклонение с широтой космодрома', '…ความเอียงกับละติจูดของฐานปล่อย'))],
    T('T² = 4π²a³/μ. The satellite\'s own mass does not appear: a feather and a station on the same orbit go round together.',
      'T² = 4π²a³/μ. Масса самого спутника в закон не входит: пёрышко и станция на одной орбите движутся вместе.',
      'T² = 4π²a³/μ มวลของดาวเทียมไม่ปรากฏในกฎ ขนนกกับสถานีอวกาศบนวงโคจรเดียวกันจะโคจรไปด้วยกัน'),
    { lessons: ['orbit-first'] }),
  choice('o-raan', 2, 1, K, 'orbit.raan',
    T('What does the longitude of the ascending node Ω fix?', 'Что задаёт долгота восходящего узла Ω?', 'ลองจิจูดของโหนดขึ้น Ω กำหนดอะไร'),
    [O(T('Which way the orbit\'s plane faces in space, measured from the vernal equinox', 'Ориентацию плоскости орбиты в пространстве, отсчитываемую от точки весеннего равноденствия', 'ทิศทางของระนาบวงโคจรในอวกาศ วัดจากจุดวสันตวิษุวัต'), true),
      O(T('The height of the orbit', 'Высоту орбиты', 'ความสูงของวงโคจร')),
      O(T('The shape of the orbit', 'Форму орбиты', 'รูปร่างของวงโคจร')),
      O(T('The longitude on the ground below the satellite', 'Географическую долготу подспутниковой точки', 'ลองจิจูดบนพื้นโลกใต้ดาวเทียม'))],
    T('Inclination tilts the plane; Ω turns it about the Earth\'s axis. Together they fix the plane — the ISS lesson is about matching both.',
      'Наклонение задаёт наклон плоскости, Ω — её поворот вокруг оси Земли. Вместе они определяют плоскость; урок про МКС посвящён совмещению обоих.',
      'ความเอียงกำหนดการเอียงของระนาบ ส่วน Ω กำหนดการหมุนของระนาบรอบแกนโลก ทั้งสองค่าร่วมกันกำหนดระนาบ บทเรียนเรื่อง ISS คือการทำให้ทั้งสองค่าตรงกัน'),
    { lessons: ['orbit-iss-plane'] }),
  choice('o-min-inclination', 2, 1, U, 'launch.latitude',
    T('What is the lowest inclination a rocket can reach directly, launching from latitude 46° N?', 'Какое наименьшее наклонение может получить ракета при прямом выведении со широты 46° с. ш.?', 'จรวดที่ปล่อยจากละติจูด 46° เหนือ เข้าสู่วงโคจรที่มีความเอียงต่ำสุดได้เท่าใดโดยตรง'),
    [O(T('46°', '46°', '46°'), true),
      O(T('0°, by launching due east', '0°, если стартовать строго на восток', '0° ถ้าปล่อยไปทางตะวันออกตรง ๆ'), false,
        T('launching due east gives an equatorial orbit from anywhere', 'старт строго на восток даёт экваториальную орбиту откуда угодно', 'การปล่อยไปทางตะวันออกตรง ๆ ให้วงโคจรเส้นศูนย์สูตรได้จากทุกที่')),
      O(T('23.4°', '23,4°', '23.4°')),
      O(T('90°', '90°', '90°'))],
    T('Every orbit\'s plane passes through the Earth\'s centre and the launch site, so the site\'s latitude is the least inclination it can reach: cos i = cos φ·sin A is at most cos φ. Lower needs a plane change later.',
      'Плоскость любой орбиты проходит через центр Земли и точку старта, поэтому широта космодрома — наименьшее достижимое наклонение: cos i = cos φ·sin A не больше cos φ. Меньшее требует последующего поворота плоскости.',
      'ระนาบวงโคจรทุกวงผ่านศูนย์กลางโลกและจุดปล่อย ละติจูดของฐานจึงเป็นความเอียงต่ำสุดที่ทำได้ เพราะ cos i = cos φ·sin A มีค่าไม่เกิน cos φ หากต้องการต่ำกว่านั้นต้องเปลี่ยนระนาบภายหลัง'),
    { lessons: ['orbit-range-safety', 'orbit-iss-plane'] }),
  numeric('o-circular-speed', 2, 2, K, 'orbit.speed',
    withConst(T('Work out the speed on a circular orbit {h} km up (km/s).', 'Рассчитайте скорость на круговой орбите высотой {h} км (км/с).', 'คำนวณอัตราเร็วบนวงโคจรวงกลมที่ความสูง {h} กม. (กม./วินาที)')),
    [{ name: 'h', min: 250, max: 1500, step: 50 }], 'sqrt(mu / (R + h * 1000)) / 1000', 'km/s', 1,
    T('v = √(μ/r) with r = R + h. Remember to add the Earth\'s radius: the orbit\'s radius is measured from the centre.',
      'v = √(μ/r), где r = R + h. Не забудьте прибавить радиус Земли: радиус орбиты отсчитывается от центра.',
      'v = √(μ/r) โดย r = R + h อย่าลืมบวกรัศมีโลก เพราะรัศมีวงโคจรวัดจากศูนย์กลางโลก'),
    { lessons: ['orbit-first'] }),
  numeric('o-period', 2, 2, K, 'orbit.period',
    withConst(T('Work out the period of a circular orbit {h} km up (min).', 'Рассчитайте период круговой орбиты высотой {h} км (мин).', 'คำนวณคาบของวงโคจรวงกลมที่ความสูง {h} กม. (นาที)')),
    [{ name: 'h', min: 250, max: 2000, step: 50 }], '2 * pi * sqrt((R + h * 1000)^3 / mu) / 60', 'min', 1,
    T('T = 2π√(r³/μ), in seconds when r is in metres and μ in m³/s²; divide by 60 for minutes.',
      'T = 2π√(r³/μ) — в секундах, если r в метрах и μ в м³/с²; для минут разделите на 60.',
      'T = 2π√(r³/μ) มีหน่วยเป็นวินาทีเมื่อ r เป็นเมตรและ μ เป็น ม.³/วินาที² หารด้วย 60 เพื่อให้เป็นนาที'),
    { lessons: ['orbit-first'] }),
  choice('o-window', 2, 2, U, 'launch.window',
    T('Why can a Soyuz to the space station leave Baikonur only at one moment each day?', 'Почему «Союз» к МКС может стартовать с Байконура лишь в определённый момент каждых суток?', 'ทำไมโซยุซที่จะไปสถานีอวกาศจึงออกจากไบโคนูร์ได้เพียงช่วงเวลาเดียวในแต่ละวัน'),
    [O(T('The station\'s orbital plane is fixed in space; the pad passes through it only as the Earth turns', 'Плоскость орбиты станции неподвижна в пространстве, а стартовый комплекс проходит через неё только за счёт вращения Земли', 'ระนาบวงโคจรของสถานีคงที่ในอวกาศ ฐานปล่อยจะผ่านระนาบนั้นก็ต่อเมื่อโลกหมุนไปถึง'), true),
      O(T('The station must be passing right overhead at launch', 'Станция должна пролетать прямо над стартом', 'สถานีต้องบินผ่านเหนือฐานปล่อยพอดีขณะปล่อย'), false,
        T('the window is about where the station is, not about where its plane is', 'окно определяется положением станции, а не её плоскостью', 'หน้าต่างการปล่อยขึ้นกับตำแหน่งของสถานี ไม่ใช่ระนาบของมัน')),
      O(T('The weather at Baikonur is only good once a day', 'Погода на Байконуре хороша лишь раз в сутки', 'สภาพอากาศที่ไบโคนูร์ดีเพียงวันละครั้ง')),
      O(T('The rocket must launch in darkness', 'Ракета должна стартовать в темноте', 'จรวดต้องปล่อยในความมืด'))],
    T('The plane matters most, because turning a plane is very expensive. Where the station is along that plane is fixed later by phasing: the Soyuz catches up over two to thirty-four orbits.',
      'Главное — плоскость, потому что её поворот очень дорог. Положение станции в этой плоскости выравнивают потом, фазированием: «Союз» догоняет её за два–тридцать четыре витка.',
      'ระนาบสำคัญที่สุด เพราะการหมุนระนาบสิ้นเปลืองมาก ส่วนตำแหน่งของสถานีบนระนาบนั้นจะปรับภายหลังด้วยการปรับเฟส โซยุซจะไล่ตามสถานีภายในสองถึงสามสิบสี่รอบโคจร'),
    { lessons: ['orbit-iss-plane'] }),
  choice('o-two-burns', 2, 2, U, 'orbit.hohmann',
    T('To go from one circular orbit to a higher circular orbit in the same plane with least propellant, a spacecraft needs…', 'Чтобы с наименьшим расходом перейти с одной круговой орбиты на более высокую в той же плоскости, аппарату нужно…', 'หากต้องการย้ายจากวงโคจรวงกลมหนึ่งไปวงโคจรวงกลมที่สูงกว่าในระนาบเดียวกันโดยใช้เชื้อเพลิงน้อยที่สุด ยานต้อง…'),
    [O(T('…two burns: one to enter a transfer ellipse, one at its apogee', '…два импульса: вход на переходный эллипс и импульс в его апогее', '…จุดเครื่องสองครั้ง: ครั้งแรกเข้าสู่วงรีถ่ายโอน ครั้งที่สองที่จุดไกลโลกของวงรี'), true),
      O(T('…one long burn pointing straight up', '…одно долгое включение вертикально вверх', '…จุดเครื่องครั้งเดียวนาน ๆ โดยชี้ขึ้นตรง'), false,
        T('to go higher you thrust upwards', 'чтобы подняться выше, нужно тянуть вверх', 'ถ้าจะขึ้นสูงต้องดันขึ้นข้างบน')),
      O(T('…one burn: the orbit comes out circular by itself', '…один импульс: орбита сама станет круговой', '…จุดเครื่องครั้งเดียว วงโคจรจะกลายเป็นวงกลมเอง')),
      O(T('…continuous thrust all the way round', '…непрерывная тяга на протяжении всего витка', '…แรงขับต่อเนื่องตลอดทั้งรอบ'))],
    T('One burn only makes an ellipse whose perigee is the burn point. The Hohmann transfer adds a second burn at the apogee to raise the perigee.',
      'Один импульс даёт лишь эллипс с перигеем в точке включения. Гомановский перелёт добавляет второй импульс в апогее, поднимающий перигей.',
      'การจุดเครื่องครั้งเดียวให้เพียงวงรีที่มีจุดใกล้โลกอยู่ที่ตำแหน่งจุดเครื่อง การถ่ายโอนแบบโฮมันน์จึงเพิ่มการจุดเครื่องครั้งที่สองที่จุดไกลโลกเพื่อยกจุดใกล้โลกขึ้น'),
    { lessons: ['orbit-hohmann'] }),
  choice('o-sso', 2, 2, K, 'orbit.sso',
    T('A sun-synchronous orbit 600 km up has an inclination of about 98°. Why slightly more than 90°?', 'Солнечно-синхронная орбита высотой 600 км имеет наклонение около 98°. Почему чуть больше 90°?', 'วงโคจรสัมพันธ์กับดวงอาทิตย์ที่ความสูง 600 กม. มีความเอียงประมาณ 98° ทำไมจึงมากกว่า 90° เล็กน้อย'),
    [O(T('The Earth\'s equatorial bulge turns such a plane eastward about 1° a day, keeping pace with the Sun', 'Экваториальное утолщение Земли поворачивает такую плоскость на восток примерно на 1° в сутки — вслед за Солнцем', 'ส่วนป่องที่เส้นศูนย์สูตรของโลกหมุนระนาบนั้นไปทางตะวันออกประมาณวันละ 1° ให้ทันดวงอาทิตย์'), true),
      O(T('The Sun\'s gravity pulls the orbit towards it', 'Притяжение Солнца наклоняет орбиту к себе', 'แรงโน้มถ่วงของดวงอาทิตย์ดึงวงโคจรเข้าหา')),
      O(T('To avoid flying over the poles', 'Чтобы не пролетать над полюсами', 'เพื่อเลี่ยงการบินผ่านขั้วโลก')),
      O(T('Because launch sites cannot reach exactly 90°', 'Потому что с космодромов нельзя попасть ровно в 90°', 'เพราะฐานปล่อยไม่สามารถปล่อยได้ 90° พอดี'))],
    T('The J2 term of the Earth\'s gravity precesses an orbit\'s node. A slightly retrograde plane at this height precesses +0.986°/day, once a year — so the satellite passes over each place at the same local time.',
      'Член J2 гравитационного поля Земли вызывает прецессию узла орбиты. Слегка обратная плоскость на этой высоте прецессирует на +0,986°/сут — один оборот в год, и спутник пролетает над каждым местом в одно и то же местное время.',
      'พจน์ J2 ของสนามโน้มถ่วงโลกทำให้โหนดของวงโคจรส่ายไป ระนาบที่ถอยหลังเล็กน้อยที่ระดับนี้ส่ายไป +0.986° ต่อวัน ครบรอบในหนึ่งปี ดาวเทียมจึงผ่านทุกจุดในเวลาท้องถิ่นเดียวกัน')),
  choice('o-plane-burn', 2, 2, U, 'orbit.plane',
    T('A satellite fires its engine at right angles to its orbital plane. What changes?', 'Спутник включает двигатель перпендикулярно плоскости своей орбиты. Что изменится?', 'ดาวเทียมจุดเครื่องยนต์ในทิศตั้งฉากกับระนาบวงโคจร อะไรจะเปลี่ยน'),
    [O(T('The orientation of its orbital plane', 'Ориентация плоскости орбиты', 'ทิศทางของระนาบวงโคจร'), true),
      O(T('Only its altitude', 'Только высота', 'เฉพาะความสูง')),
      O(T('Only its period', 'Только период', 'เฉพาะคาบ')),
      O(T('Nothing: sideways thrust has no effect in orbit', 'Ничего: боковая тяга на орбите не действует', 'ไม่มีอะไรเปลี่ยน แรงขับด้านข้างไม่มีผลในวงโคจร'), false,
        T('only thrust along the motion changes an orbit', 'орбиту меняет лишь тяга вдоль движения', 'มีเพียงแรงขับตามทิศการเคลื่อนที่เท่านั้นที่เปลี่ยนวงโคจรได้'))],
    T('A burn along the orbit\'s normal turns the velocity out of the plane: the plane rotates about the line to the burn point. Made at a node it changes the inclination; elsewhere it also moves Ω.',
      'Импульс по нормали к орбите выводит скорость из плоскости: плоскость поворачивается вокруг линии, проходящей через точку включения. В узле меняется наклонение, в другой точке — ещё и Ω.',
      'การจุดเครื่องตามแนวตั้งฉากกับวงโคจรทำให้ความเร็วเบนออกนอกระนาบ ระนาบจึงหมุนรอบแนวที่ผ่านจุดจุดเครื่อง ถ้าทำที่โหนดจะเปลี่ยนความเอียง ถ้าทำที่ตำแหน่งอื่นจะเปลี่ยน Ω ด้วย')),
  choice('o-molniya', 2, 2, K, 'orbit.molniya',
    T('Why do Molniya orbits have an inclination of 63.4°?', 'Почему у орбит типа «Молния» наклонение 63,4°?', 'ทำไมวงโคจรแบบโมลนิยาจึงมีความเอียง 63.4°'),
    [O(T('At that inclination the Earth\'s bulge does not turn the perigee round, so the apogee stays over the north', 'При таком наклонении сжатие Земли не поворачивает линию апсид, и апогей остаётся над северным полушарием', 'ที่ความเอียงนี้ส่วนป่องของโลกไม่ทำให้จุดใกล้โลกหมุนไป จุดไกลโลกจึงค้างอยู่เหนือซีกโลกเหนือ'), true),
      O(T('It is the latitude of Moscow', 'Это широта Москвы', 'เป็นละติจูดของมอสโก')),
      O(T('It is the lowest inclination Plesetsk can reach', 'Это наименьшее наклонение, доступное Плесецку', 'เป็นความเอียงต่ำสุดที่เพลเซตสค์ทำได้')),
      O(T('It gives exactly a 12-hour period', 'Оно даёт ровно 12-часовой период', 'ทำให้คาบเท่ากับ 12 ชั่วโมงพอดี'))],
    T('The apsidal precession from J2 is proportional to (5cos²i − 1), which is zero at 63.4° — the critical inclination. The 12-hour period comes from the semi-major axis, not the inclination.',
      'Прецессия линии апсид от J2 пропорциональна (5cos²i − 1) и равна нулю при 63,4° — критическом наклонении. 12-часовой период определяется большой полуосью, а не наклонением.',
      'การส่ายของแนวแอปไซด์จาก J2 แปรผันตาม (5cos²i − 1) ซึ่งเป็นศูนย์ที่ 63.4° เรียกว่าความเอียงวิกฤต ส่วนคาบ 12 ชั่วโมงมาจากกึ่งแกนเอก ไม่ใช่ความเอียง')),
  numeric('o-hohmann-first', 2, 3, K, 'orbit.hohmann',
    withConst(T('A spacecraft on a circular orbit {h1} km up starts a Hohmann transfer to a circular orbit {h2} km up. Work out the Δv of the first burn (m/s).',
      'Аппарат на круговой орбите высотой {h1} км начинает гомановский перелёт на круговую орбиту высотой {h2} км. Рассчитайте Δv первого импульса (м/с).',
      'ยานบนวงโคจรวงกลมสูง {h1} กม. เริ่มการถ่ายโอนแบบโฮมันน์ไปยังวงโคจรวงกลมสูง {h2} กม. คำนวณ Δv ของการจุดเครื่องครั้งแรก (ม./วินาที)')),
    [{ name: 'h1', min: 200, max: 400, step: 20 }, { name: 'h2', min: 800, max: 2000, step: 100 }],
    'sqrt(mu / (R + h1 * 1000)) * (sqrt(2 * (R + h2 * 1000) / ((R + h1 * 1000) + (R + h2 * 1000))) - 1)', 'm/s', 3,
    T('Δv₁ = √(μ/r₁)·(√(2r₂/(r₁+r₂)) − 1): the speed at perigee of the transfer ellipse, less the circular speed where the burn is made.',
      'Δv₁ = √(μ/r₁)·(√(2r₂/(r₁+r₂)) − 1): скорость в перигее переходного эллипса минус круговая скорость в точке включения.',
      'Δv₁ = √(μ/r₁)·(√(2r₂/(r₁+r₂)) − 1) คืออัตราเร็วที่จุดใกล้โลกของวงรีถ่ายโอน ลบด้วยอัตราเร็ววงกลม ณ ตำแหน่งที่จุดเครื่อง'),
    { lessons: ['orbit-hohmann'] }),
  numeric('o-plane-change', 2, 3, K, 'orbit.plane',
    T('A satellite moving at {v} km/s turns its orbital plane by {di}° in one burn at the node, keeping its speed. Work out the Δv (m/s).',
      'Спутник, движущийся со скоростью {v} км/с, одним импульсом в узле поворачивает плоскость орбиты на {di}°, сохраняя величину скорости. Рассчитайте Δv (м/с).',
      'ดาวเทียมที่เคลื่อนที่ด้วยอัตราเร็ว {v} กม./วินาที หมุนระนาบวงโคจรไป {di}° ด้วยการจุดเครื่องครั้งเดียวที่โหนดโดยคงอัตราเร็วไว้ คำนวณ Δv (ม./วินาที)'),
    [{ name: 'v', min: 1.6, max: 7.8, step: 0.1 }, { name: 'di', min: 2, max: 30, step: 1 }], '2 * v * 1000 * sin(di / 2)', 'm/s', 2,
    T('Δv = 2v·sin(Δi/2): the chord between two velocity vectors of equal length. It is why geostationary satellites make their plane change at apogee, where v is smallest.',
      'Δv = 2v·sin(Δi/2) — хорда между двумя векторами скорости одинаковой длины. Поэтому геостационарные спутники поворачивают плоскость в апогее, где скорость наименьшая.',
      'Δv = 2v·sin(Δi/2) คือคอร์ดระหว่างเวกเตอร์ความเร็วสองเวกเตอร์ที่ยาวเท่ากัน ดาวเทียมค้างฟ้าจึงเปลี่ยนระนาบที่จุดไกลโลกซึ่ง v มีค่าน้อยที่สุด'),
    { lessons: ['orbit-iss-plane'] }),
  choice('o-catch-up', 2, 3, U, 'orbit.phasing',
    T('Two spacecraft share a circular orbit; the chaser is 10 km behind the target. To catch up with the least propellant it should first…', 'Два аппарата на одной круговой орбите; догоняющий отстаёт на 10 км. Чтобы догнать цель с наименьшим расходом, он должен сначала…', 'ยานสองลำอยู่บนวงโคจรวงกลมเดียวกัน ยานไล่ตามอยู่ข้างหลังเป้าหมาย 10 กม. เพื่อไล่ทันโดยใช้เชื้อเพลิงน้อยที่สุด ยานไล่ตามควร…'),
    [O(T('…brake a little, dropping into a lower and faster orbit', '…немного притормозить и перейти на более низкую, более быструю орбиту', '…ชะลอความเร็วเล็กน้อย เพื่อลดลงสู่วงโคจรที่ต่ำกว่าและเร็วกว่า'), true),
      O(T('…fire forwards to speed up towards the target', '…включить двигатель вперёд и разогнаться к цели', '…จุดเครื่องไปข้างหน้าเพื่อเร่งเข้าหาเป้าหมาย'), false,
        T('speeding up along the orbit brings you closer to a target ahead', 'разгон вдоль орбиты приближает к цели, идущей впереди', 'การเร่งความเร็วตามวงโคจรจะพาเข้าใกล้เป้าหมายที่อยู่ข้างหน้า')),
      O(T('…fire straight towards the target', '…включить двигатель прямо на цель', '…จุดเครื่องพุ่งตรงไปยังเป้าหมาย')),
      O(T('…do nothing: they will meet in half an orbit', '…ничего не делать: они встретятся через пол-витка', '…ไม่ต้องทำอะไร จะพบกันเองในครึ่งรอบ'))],
    T('Speeding up raises the orbit and lengthens the period, so the chaser falls further behind. Braking lowers it and shortens the period: the chaser gains on the target each revolution and later brakes back up. This is phasing.',
      'Разгон поднимает орбиту и удлиняет период — догоняющий отстаёт ещё сильнее. Торможение понижает орбиту и сокращает период: за каждый виток догоняющий выигрывает у цели, а затем поднимается обратно. Это фазирование.',
      'การเร่งทำให้วงโคจรสูงขึ้นและคาบยาวขึ้น ยานไล่ตามจึงตกห่างมากขึ้น การชะลอทำให้วงโคจรต่ำลงและคาบสั้นลง ยานไล่ตามจึงได้ระยะคืนทุกรอบ แล้วค่อยยกวงโคจรกลับ นี่คือการปรับเฟส'),
    { lessons: ['adv-docking'] }),
  choice('o-geo-latitude', 2, 3, U, 'orbit.plane',
    T('Why does a satellite launched to geostationary orbit from Baikonur need more Δv than one launched from Kourou?', 'Почему спутнику, выводимому на геостационарную орбиту с Байконура, нужно больше Δv, чем при пуске с Куру?', 'ทำไมดาวเทียมที่ปล่อยจากไบโคนูร์ไปวงโคจรค้างฟ้าจึงต้องใช้ Δv มากกว่าดาวเทียมที่ปล่อยจากคูรู'),
    [O(T('It starts with an inclination of at least 46° and must turn its plane to 0°', 'Он начинает с наклонением не менее 46° и должен повернуть плоскость до 0°', 'มันเริ่มด้วยความเอียงอย่างน้อย 46° และต้องหมุนระนาบลงมาเป็น 0°'), true),
      O(T('Baikonur is higher above sea level', 'Байконур расположен выше над уровнем моря', 'ไบโคนูร์อยู่สูงจากระดับน้ำทะเลมากกว่า')),
      O(T('The air over the steppe is denser', 'Воздух над степью плотнее', 'อากาศเหนือทุ่งหญ้าสเตปป์หนาแน่นกว่า')),
      O(T('The Earth turns faster at Baikonur\'s latitude', 'На широте Байконура Земля вращается быстрее', 'โลกหมุนเร็วกว่าที่ละติจูดของไบโคนูร์'), false,
        T('the ground moves faster away from the equator', 'поверхность движется быстрее вдали от экватора', 'พื้นผิวโลกเคลื่อนเร็วขึ้นเมื่อห่างจากเส้นศูนย์สูตร'))],
    T('From 46° the transfer orbit is inclined at least 46°, and the plane change at apogee costs about 1.5 km/s more than Kourou\'s 5°. The ground at Baikonur also moves slower, 324 against 463 m/s.',
      'С широты 46° переходная орбита имеет наклонение не менее 46°, и поворот плоскости в апогее стоит примерно на 0,8 км/с больше, чем при 5° с Куру. К тому же поверхность на Байконуре движется медленнее: 324 против 463 м/с.',
      'จากละติจูด 46° วงโคจรถ่ายโอนจะเอียงอย่างน้อย 46° การเปลี่ยนระนาบที่จุดไกลโลกจึงใช้มากกว่าการปล่อยจากคูรูซึ่งเอียงเพียง 5° ราว 0.8 กม./วินาที อีกทั้งพื้นผิวที่ไบโคนูร์ยังเคลื่อนช้ากว่า คือ 324 เทียบกับ 463 ม./วินาที')),
  numeric('o-perigee-speed', 2, 3, K, 'orbit.visviva',
    withConst(T('An orbit has its perigee {hp} km and its apogee {ha} km above the Earth. Work out the speed at perigee (km/s).',
      'Перигей орбиты — {hp} км, апогей — {ha} км над Землёй. Рассчитайте скорость в перигее (км/с).',
      'วงโคจรมีจุดใกล้โลกสูง {hp} กม. และจุดไกลโลกสูง {ha} กม. คำนวณอัตราเร็วที่จุดใกล้โลก (กม./วินาที)')),
    [{ name: 'hp', min: 180, max: 400, step: 20 }, { name: 'ha', min: 1000, max: 36000, step: 1000 }],
    'sqrt(mu * (2 / (R + hp * 1000) - 2 / ((R + hp * 1000) + (R + ha * 1000)))) / 1000', 'km/s', 1,
    T('vis-viva: v² = μ(2/r − 1/a), with r the perigee radius and a the mean of the perigee and apogee radii.',
      'Интеграл энергии: v² = μ(2/r − 1/a), где r — радиус перигея, a — среднее радиусов перигея и апогея.',
      'vis-viva: v² = μ(2/r − 1/a) โดย r คือรัศมีที่จุดใกล้โลก และ a คือค่าเฉลี่ยของรัศมีจุดใกล้โลกกับจุดไกลโลก'),
    { lessons: ['orbit-hohmann'] }),
  order('o-order-period', 2, 1, K, 'orbit.periods',
    T('Put these in order of the time they take to go once round the Earth, shortest first.', 'Расположите по периоду обращения вокруг Земли, начиная с наименьшего.', 'เรียงตามเวลาที่ใช้โคจรรอบโลกหนึ่งรอบ จากสั้นที่สุดไปยาวที่สุด'),
    [T('The ISS, about 420 km up', 'МКС, высота около 420 км', 'ISS สูงประมาณ 420 กม.'),
      T('A sun-synchronous satellite 800 km up', 'Солнечно-синхронный спутник на высоте 800 км', 'ดาวเทียมวงโคจรสัมพันธ์กับดวงอาทิตย์ที่ความสูง 800 กม.'),
      T('A GLONASS satellite, 19 100 km up', 'Спутник ГЛОНАСС, высота 19 100 км', 'ดาวเทียม GLONASS สูง 19 100 กม.'),
      T('A geostationary satellite', 'Геостационарный спутник', 'ดาวเทียมค้างฟ้า'),
      T('The Moon', 'Луна', 'ดวงจันทร์')],
    T('The higher the orbit, the longer the period (Kepler\'s third law): about 93 min, 101 min, 11 h 15 min, 23 h 56 min, 27.3 days.',
      'Чем выше орбита, тем больше период (третий закон Кеплера): около 93 мин, 101 мин, 11 ч 15 мин, 23 ч 56 мин, 27,3 сут.',
      'ยิ่งวงโคจรสูง คาบยิ่งยาว (กฎข้อที่สามของเคปเลอร์) ประมาณ 93 นาที 101 นาที 11 ชม. 15 นาที 23 ชม. 56 นาที และ 27.3 วัน'),
    { lessons: ['orbit-first'] }),
  choice('o-plane-node', 2, 2, K, 'orbit.planeDiagram',
    T('The diagram shows the equator\'s plane (blue) and a satellite\'s orbit (gold), flown the way the arrow points; N is the north pole. Which mark is the ascending node?', 'На схеме — плоскость экватора (синяя) и орбита спутника (золотая), направление движения показано стрелкой; N — северный полюс. Какая отметка — восходящий узел?', 'แผนภาพแสดงระนาบเส้นศูนย์สูตร (สีน้ำเงิน) และวงโคจรของดาวเทียม (สีทอง) ซึ่งโคจรตามทิศลูกศร N คือขั้วโลกเหนือ เครื่องหมายใดคือโหนดขึ้น'),
    letters('A', {}, ['A', 'B', 'C']),
    T('The ascending node is where the satellite crosses the equator going north: at A the arrow leaves the equator\'s plane upwards. B is the descending node; C marks the angle from the vernal equinox ♈ to the ascending node, the longitude of the ascending node Ω.',
      'Восходящий узел — точка, где спутник пересекает экватор, двигаясь на север: в точке A стрелка уходит из плоскости экватора вверх. B — нисходящий узел; C — угол от точки весеннего равноденствия ♈ до восходящего узла, долгота восходящего узла Ω.',
      'โหนดขึ้นคือจุดที่ดาวเทียมตัดเส้นศูนย์สูตรขณะเคลื่อนขึ้นไปทางเหนือ ที่ A ลูกศรออกจากระนาบเส้นศูนย์สูตรขึ้นด้านบน B คือโหนดลง ส่วน C คือมุมจากจุดวสันตวิษุวัต ♈ ถึงโหนดขึ้น หรือลองจิจูดของโหนดขึ้น Ω'),
    { figure: diagram('orbit-plane'), fixedOrder: true, lessons: ['orbit-iss-plane'] }),
  choice('o-plane-raan', 2, 3, K, 'orbit.planeDiagram',
    T('On the diagram (the equator\'s plane blue, the orbit gold, flown the way the arrow points, ♈ the direction of the vernal equinox), which mark is the angle Ω, the longitude of the ascending node?', 'На схеме (плоскость экватора — синяя, орбита — золотая, направление движения — по стрелке, ♈ — направление на точку весеннего равноденствия) какая отметка — угол Ω, долгота восходящего узла?', 'ในแผนภาพ (ระนาบเส้นศูนย์สูตรสีน้ำเงิน วงโคจรสีทองซึ่งโคจรตามทิศลูกศร ♈ คือทิศของจุดวสันตวิษุวัต) เครื่องหมายใดคือมุม Ω ลองจิจูดของโหนดขึ้น'),
    letters('C', {}, ['A', 'B', 'C']),
    T('Ω is measured in the equator\'s plane, eastwards from the vernal equinox ♈ to the ascending node A: the arc C. It turns the whole orbital plane about the polar axis; a launch window is the moment the launch site passes under the plane with the Ω asked for.',
      'Ω отсчитывается в плоскости экватора к востоку от точки весеннего равноденствия ♈ до восходящего узла A: дуга C. Она поворачивает всю плоскость орбиты вокруг оси полюсов; окно запуска — момент, когда космодром проходит под плоскостью с требуемой Ω.',
      'Ω วัดในระนาบเส้นศูนย์สูตร ไปทางตะวันออกจากจุดวสันตวิษุวัต ♈ ถึงโหนดขึ้น A คือส่วนโค้ง C ค่านี้หมุนระนาบวงโคจรทั้งระนาบรอบแกนขั้วโลก ช่วงเวลาปล่อยจรวดคือเวลาที่ฐานปล่อยเคลื่อนผ่านใต้ระนาบที่มี Ω ตามต้องการ'),
    { figure: diagram('orbit-plane'), fixedOrder: true, lessons: ['orbit-iss-plane'] }),
  choice('o-hohmann-burns', 2, 1, U, 'orbit.hohmannDiagram',
    T('A spacecraft moves from the inner circular orbit to the outer one along the dashed half-ellipse. Where does it fire its engine, and which way?', 'Корабль переходит с внутренней круговой орбиты на внешнюю по штриховой полуэллипсу. Где и в каком направлении он включает двигатель?', 'ยานอวกาศย้ายจากวงโคจรวงกลมด้านในไปยังวงนอกตามครึ่งวงรีเส้นประ ยานจุดเครื่องยนต์ที่ใดและไปทางใด'),
    [O(T('At A forwards, then at B forwards', 'В A — вперёд, затем в B — вперёд', 'ที่ A ไปข้างหน้า แล้วที่ B ไปข้างหน้า'), true),
      O(T('At A forwards, then at B backwards, to stop on the new orbit', 'В A — вперёд, затем в B — назад, чтобы остановиться на новой орбите', 'ที่ A ไปข้างหน้า แล้วที่ B ถอยหลังเพื่อหยุดบนวงโคจรใหม่'), false,
        T('Arriving at the top of the transfer the spacecraft is too fast and must brake.', 'В верхней точке перехода корабль движется слишком быстро и должен тормозить.', 'เมื่อไปถึงจุดสูงสุดของวงโคจรถ่ายโอน ยานเร็วเกินไปจึงต้องเบรก')),
      O(T('At A outwards, away from the Earth, then at C', 'В A — от Земли (радиально), затем в C', 'ที่ A พุ่งออกจากโลก แล้วที่ C'), false,
        T('To go higher, push away from the Earth.', 'Чтобы подняться выше, нужно толкать от Земли.', 'ถ้าจะขึ้นสูงต้องดันออกจากโลก')),
      O(T('At D forwards, then at C forwards', 'В D — вперёд, затем в C — вперёд', 'ที่ D ไปข้างหน้า แล้วที่ C ไปข้างหน้า'))],
    T('The first burn at A, forwards, lifts the far side of the orbit to the outer circle; at B, the apogee, the spacecraft is slower than the outer circle needs, so a second forward burn raises the perigee to make the orbit round. Radial burns waste propellant.',
      'Первый импульс в A вперёд поднимает противоположную сторону орбиты до внешней окружности; в апогее B скорость меньше круговой для внешней орбиты, поэтому второй импульс вперёд поднимает перигей и скругляет орбиту. Радиальные импульсы расходуют топливо впустую.',
      'การจุดครั้งแรกที่ A ไปข้างหน้ายกด้านไกลของวงโคจรขึ้นถึงวงนอก ที่ B ซึ่งเป็นจุดไกลโลก ยานช้ากว่าความเร็ววงกลมของวงนอก จึงต้องจุดไปข้างหน้าครั้งที่สองเพื่อยกจุดใกล้โลกให้วงโคจรกลม การจุดในแนวรัศมีเปลืองเชื้อเพลิงโดยเปล่าประโยชน์'),
    { figure: diagram('hohmann'), lessons: ['orbit-hohmann'] }),
  choice('o-ellipse-raise', 2, 2, U, 'orbit.apsisBurn',
    T('The satellite on this orbit must raise its perigee A with the least propellant. Where should it fire its engine forwards?', 'Спутнику на этой орбите нужно поднять перигей A с наименьшим расходом топлива. Где включить двигатель вперёд?', 'ดาวเทียมบนวงโคจรนี้ต้องยกจุดใกล้โลก A ให้สูงขึ้นโดยใช้เชื้อเพลิงน้อยที่สุด ควรจุดเครื่องยนต์ไปข้างหน้าที่ใด'),
    letters('B', {
      A: T('A change to a point is made at that point.', 'Изменить точку орбиты можно, только находясь в ней.', 'การเปลี่ยนจุดใดของวงโคจรต้องทำที่จุดนั้น'),
      D: T('Burning halfway round splits the change between both ends evenly.', 'Импульс посередине распределяет изменение поровну между обоими концами.', 'การจุดตรงกลางทางจะแบ่งการเปลี่ยนแปลงให้ทั้งสองปลายเท่า ๆ กัน'),
    }),
    T('A short burn changes the height of the opposite side of the orbit: forwards at the apogee B raises the perigee A. Burning at A itself would raise the apogee instead.',
      'Короткий импульс меняет высоту противоположной стороны орбиты: импульс вперёд в апогее B поднимает перигей A. Импульс в самой точке A поднял бы апогей.',
      'การจุดสั้น ๆ เปลี่ยนความสูงของด้านตรงข้ามของวงโคจร การจุดไปข้างหน้าที่จุดไกลโลก B จะยกจุดใกล้โลก A ถ้าจุดที่ A เองจะเป็นการยกจุดไกลโลกแทน'),
    { figure: diagram('orbit-ellipse'), fixedOrder: true, lessons: ['orbit-hohmann'] }),
  numeric('o-ground-track', 2, 2, K, 'orbit.groundTrack',
    T('The map shows two turns of the ground track of a satellite on a circular orbit (φ latitude, λ longitude). Read the orbit\'s inclination from it (°).', 'На карте — две витка трассы спутника на круговой орбите (φ — широта, λ — долгота). Определите по ней наклонение орбиты (°).', 'แผนที่แสดงแนวทางภาคพื้นดินสองรอบของดาวเทียมบนวงโคจรวงกลม (φ ละติจูด λ ลองจิจูด) อ่านความเอียงของวงโคจรจากแผนที่ (°)'),
    [{ name: 'i', min: 25, max: 72, step: 1 }], 'i', '°', 6,
    T('The track reaches the latitude equal to the inclination (for an orbit going east, i ≤ 90°): its highest point is the inclination. Each turn shifts west by the Earth\'s rotation during one period, about 23° for a 92-minute orbit.',
      'Трасса достигает широты, равной наклонению (для прямой орбиты, i ≤ 90°): её наивысшая точка и есть наклонение. Каждый виток смещается к западу на угол поворота Земли за период — около 23° при периоде 92 мин.',
      'แนวทางภาคพื้นดินขึ้นไปถึงละติจูดเท่ากับความเอียง (สำหรับวงโคจรที่ไปทางตะวันออก i ≤ 90°) จุดสูงสุดจึงเป็นค่าความเอียง แต่ละรอบเลื่อนไปทางตะวันตกเท่ากับมุมที่โลกหมุนในหนึ่งคาบ ประมาณ 23° สำหรับคาบ 92 นาที'),
    { figure: diagram('ground-track'), lessons: ['orbit-iss-plane'] }),
  multi('o-multi-perigee-burn', 2, 2, U, 'orbit.burnEffects',
    T('A satellite on an elliptical orbit fires its engine briefly forwards at perigee. What changes? Choose every one.', 'Спутник на эллиптической орбите кратковременно включает двигатель вперёд в перигее. Что изменится? Выберите всё.', 'ดาวเทียมบนวงโคจรวงรีจุดเครื่องยนต์ไปข้างหน้าช่วงสั้น ๆ ที่จุดใกล้โลก อะไรเปลี่ยนไปบ้าง เลือกทุกข้อที่ถูก'),
    [O(T('The apogee rises', 'Апогей поднимается', 'จุดไกลโลกสูงขึ้น'), true),
      O(T('The period grows longer', 'Период увеличивается', 'คาบยาวขึ้น'), true),
      O(T('The orbit\'s energy grows', 'Энергия орбиты растёт', 'พลังงานของวงโคจรเพิ่มขึ้น'), true),
      O(T('The perigee rises', 'Перигей поднимается', 'จุดใกล้โลกสูงขึ้น'), false,
        T('The orbit rises where the engine fires.', 'Орбита поднимается там, где работает двигатель.', 'วงโคจรสูงขึ้นตรงจุดที่จุดเครื่องยนต์')),
      O(T('The inclination changes', 'Наклонение меняется', 'ความเอียงเปลี่ยน'), false,
        T('Any burn tilts the orbital plane.', 'Любой импульс наклоняет плоскость орбиты.', 'การจุดเครื่องยนต์ทุกครั้งทำให้ระนาบวงโคจรเอียง'))],
    T('A forward burn adds energy, so the semi-major axis and the period grow; the extra speed lifts the far side, the apogee. The perigee stays where the burn was made, and a burn in the orbital plane cannot tilt it.',
      'Импульс вперёд добавляет энергию, поэтому большая полуось и период растут; избыток скорости поднимает противоположную сторону — апогей. Перигей остаётся в точке импульса, а импульс в плоскости орбиты не может её наклонить.',
      'การจุดไปข้างหน้าเพิ่มพลังงาน กึ่งแกนเอกและคาบจึงเพิ่มขึ้น ความเร็วที่เพิ่มยกด้านไกลคือจุดไกลโลก จุดใกล้โลกยังอยู่ที่ตำแหน่งที่จุดเครื่องยนต์ และการจุดในระนาบวงโคจรไม่ทำให้ระนาบเอียง')),
  numeric('o-period-height', 2, 3, K, 'orbit.kepler3Calc',
    T('A satellite on a circular orbit goes round the Earth once in {T} h. Work out its height above the Earth (km). Take R = 6 378 km and μ = 398 600 km³/s².', 'Спутник на круговой орбите совершает оборот вокруг Земли за {T} ч. Определите его высоту над Землёй (км). Примите R = 6 378 км и μ = 398 600 км³/с².', 'ดาวเทียมบนวงโคจรวงกลมโคจรรอบโลกหนึ่งรอบใน {T} ชม. จงหาความสูงเหนือพื้นโลก (กม.) ใช้ R = 6 378 กม. และ μ = 398 600 กม.³/วินาที²'),
    [{ name: 'T', min: 2, max: 12, step: 0.5 }], '((mu * (T * 3600)^2 / (4 * pi^2))^(1/3) - R) / 1000', 'km', 2,
    T('From Kepler\'s third law, r = (μT²/4π²)^(1/3), and h = r − R. For T = 12 h, r ≈ 26 600 km: the GPS satellites\' orbit.',
      'Из третьего закона Кеплера r = (μT²/4π²)^(1/3), h = r − R. При T = 12 ч r ≈ 26 600 км — орбита спутников GPS.',
      'จากกฎข้อที่สามของเคปเลอร์ r = (μT²/4π²)^(1/3) และ h = r − R เมื่อ T = 12 ชม. r ≈ 26 600 กม. ซึ่งเป็นวงโคจรของดาวเทียม GPS')),
  choice('o-nodal-regression', 2, 3, U, 'orbit.j2',
    T('The plane of the ISS\'s orbit (51.6°) turns westward by about 5° a day. What turns it?', 'Плоскость орбиты МКС (51,6°) поворачивается к западу примерно на 5° в сутки. Что её поворачивает?', 'ระนาบวงโคจรของ ISS (51.6°) หมุนไปทางตะวันตกประมาณ 5° ต่อวัน อะไรทำให้ระนาบหมุน'),
    [O(T('The Earth\'s equatorial bulge, pulling on the orbit (the J2 term)', 'Экваториальное утолщение Земли, притягивающее орбиту (член J2)', 'ส่วนป่องที่เส้นศูนย์สูตรของโลกซึ่งดึงวงโคจร (พจน์ J2)'), true),
      O(T('The Moon\'s gravity', 'Притяжение Луны', 'แรงโน้มถ่วงของดวงจันทร์'), false,
        T('The Moon is the strongest outside pull on a low orbit.', 'Луна — самое сильное внешнее возмущение низкой орбиты.', 'ดวงจันทร์เป็นแรงรบกวนภายนอกที่แรงที่สุดต่อวงโคจรต่ำ')),
      O(T('Atmospheric drag', 'Сопротивление атмосферы', 'แรงต้านของบรรยากาศ'), false,
        T('Drag changes every element of the orbit, the plane too.', 'Сопротивление меняет все элементы орбиты, в том числе плоскость.', 'แรงต้านเปลี่ยนองค์ประกอบวงโคจรทุกตัว รวมถึงระนาบด้วย')),
      O(T('The Earth turning underneath it', 'Вращение Земли под орбитой', 'การที่โลกหมุนอยู่ข้างใต้'))],
    T('The bulge makes the orbit precess about the polar axis, westward for an orbit going east, fastest for low, low-inclination orbits. Sun-synchronous orbits use it: tilted just past 90°, their plane turns eastward 0.986° a day, with the Sun. Drag lowers an orbit but does not turn its plane; the Earth\'s rotation moves the ground track, not the plane.',
      'Утолщение вызывает прецессию орбиты вокруг оси полюсов — к западу для прямой орбиты, быстрее всего для низких орбит с малым наклонением. Солнечно-синхронные орбиты используют это: при наклонении чуть больше 90° их плоскость поворачивается к востоку на 0,986° в сутки, вслед за Солнцем. Сопротивление снижает орбиту, но не поворачивает её плоскость; вращение Земли смещает трассу, а не плоскость.',
      'ส่วนป่องทำให้วงโคจรส่ายรอบแกนขั้วโลก ไปทางตะวันตกสำหรับวงโคจรที่ไปทางตะวันออก และเร็วที่สุดสำหรับวงโคจรต่ำที่เอียงน้อย วงโคจรสัมพันธ์กับดวงอาทิตย์ใช้ผลนี้ เมื่อเอียงเกิน 90° เล็กน้อย ระนาบจะหมุนไปทางตะวันออก 0.986° ต่อวันตามดวงอาทิตย์ แรงต้านลดความสูงแต่ไม่หมุนระนาบ ส่วนการหมุนของโลกเลื่อนแนวทางภาคพื้นดิน ไม่ใช่ระนาบ')),
];
