/** Area 2, rocket performance and flight through the atmosphere (roadmap E03). */
import { O, T, U, K, chart, choice, numeric } from './helpers';

export const ROCKETS: readonly unknown[] = [
  choice('r-isp', 2, 1, K, 'rocket.isp',
    T('What does an engine\'s specific impulse measure?', 'Что характеризует удельный импульс двигателя?', 'แรงดลจำเพาะ (specific impulse) ของเครื่องยนต์วัดอะไร'),
    [O(T('How much thrust it gets from each unit of propellant burnt per second: its efficiency', 'Сколько тяги даёт каждая единица расхода топлива в секунду — его экономичность', 'แรงขับที่ได้ต่อเชื้อเพลิงหนึ่งหน่วยที่เผาต่อวินาที หรือประสิทธิภาพของเครื่องยนต์'), true),
      O(T('Its total thrust', 'Его полную тягу', 'แรงขับทั้งหมด')),
      O(T('How long it can burn', 'Как долго он может работать', 'ระยะเวลาที่เผาไหม้ได้')),
      O(T('The shock it gives the rocket at ignition', 'Удар, который он передаёт ракете при запуске', 'แรงกระแทกที่ส่งให้จรวดตอนจุดระเบิด'))],
    T('Isp = F/(ṁ·g0), in seconds; the exhaust velocity is Isp·g0. A Merlin 1D gives about 282 s at sea level, an RD-0110 326 s in vacuum, a hydrogen engine about 450 s.',
      'Iуд = P/(ṁ·g0), в секундах; скорость истечения равна Iуд·g0. Merlin 1D даёт около 282 с у земли, РД-0110 — 326 с в пустоте, водородный двигатель — около 450 с.',
      'Isp = F/(ṁ·g0) มีหน่วยเป็นวินาที ความเร็วไอเสียเท่ากับ Isp·g0 เครื่อง Merlin 1D ให้ประมาณ 282 วินาทีที่ระดับน้ำทะเล RD-0110 ให้ 326 วินาทีในสุญญากาศ และเครื่องยนต์ไฮโดรเจนประมาณ 450 วินาที')),
  choice('r-tsiolkovsky', 2, 1, K, 'rocket.tsiolkovsky',
    T('Which is Tsiolkovsky\'s rocket equation?', 'Какая из формул — формула Циолковского?', 'ข้อใดคือสมการจรวดของซีออลคอฟสกี'),
    [O(T('Δv = Isp·g0·ln(m0/mf)', 'Δv = Iуд·g0·ln(m0/mк)', 'Δv = Isp·g0·ln(m0/mf)'), true),
      O(T('Δv = F·t/m', 'Δv = P·t/m', 'Δv = F·t/m')),
      O(T('Δv = √(2μ/r)', 'Δv = √(2μ/r)', 'Δv = √(2μ/r)')),
      O(T('Δv = Isp·g0·(m0 − mf)', 'Δv = Iуд·g0·(m0 − mк)', 'Δv = Isp·g0·(m0 − mf)'))],
    T('The velocity gained grows with the logarithm of the ratio of the mass at ignition to the mass at burn-out — which is why doubling the propellant does not double Δv.',
      'Приращение скорости растёт как логарифм отношения начальной массы к конечной, поэтому удвоение запаса топлива не удваивает Δv.',
      'ความเร็วที่เพิ่มขึ้นแปรตามลอการิทึมของอัตราส่วนมวลตอนจุดเครื่องต่อมวลตอนเชื้อเพลิงหมด การเพิ่มเชื้อเพลิงเป็นสองเท่าจึงไม่ทำให้ Δv เพิ่มเป็นสองเท่า'),
    { lessons: ['orbit-payload'] }),
  choice('r-q', 2, 1, K, 'aero.q',
    T('The dynamic pressure q on a rocket is…', 'Скоростной напор q, действующий на ракету, равен…', 'ความดันพลวัต q ที่กระทำต่อจรวดเท่ากับ…'),
    [O(T('½ρV²', '½ρV²', '½ρV²'), true), O(T('ρgh', 'ρgh', 'ρgh')), O(T('mV²', 'mV²', 'mV²')), O(T('F/A', 'P/S', 'F/A'))],
    T('q = ½ρV², with ρ the air density and V the airspeed. The aerodynamic forces on the vehicle scale with it, and so do the loads on its structure.',
      'q = ½ρV², где ρ — плотность воздуха, V — воздушная скорость. Пропорционально ему растут аэродинамические силы и нагрузки на конструкцию.',
      'q = ½ρV² โดย ρ คือความหนาแน่นอากาศ และ V คืออัตราเร็วเทียบอากาศ แรงทางอากาศพลศาสตร์และภาระต่อโครงสร้างแปรตามค่านี้'),
    { lessons: ['guid-maxq'] }),
  choice('r-twr', 2, 1, U, 'rocket.twr',
    T('A rocket\'s thrust-to-weight ratio at lift-off is 0.9. What happens when its engines reach full thrust?', 'Тяговооружённость ракеты на старте 0,9. Что произойдёт, когда двигатели выйдут на полную тягу?', 'จรวดมีอัตราส่วนแรงขับต่อน้ำหนักตอนออกตัว 0.9 จะเกิดอะไรขึ้นเมื่อเครื่องยนต์ทำงานเต็มแรงขับ'),
    [O(T('It stays on the pad until it has burnt off enough propellant — or never lifts off', 'Она останется на столе, пока не выработает достаточно топлива, — или не взлетит вовсе', 'จรวดจะค้างอยู่บนแท่นจนกว่าจะเผาเชื้อเพลิงไปมากพอ หรืออาจไม่ขึ้นเลย'), true),
      O(T('It rises slowly', 'Она медленно поднимется', 'จรวดจะค่อย ๆ ลอยขึ้น'), false,
        T('any thrust at all lifts a rocket, only more slowly', 'любая тяга поднимает ракету, только медленнее', 'แรงขับเท่าใดก็ยกจรวดขึ้นได้ เพียงแต่ช้ากว่า')),
      O(T('It rises normally: T/W only matters in orbit', 'Она нормально взлетит: тяговооружённость важна лишь на орбите', 'ขึ้นได้ตามปกติ อัตราส่วนนี้สำคัญเฉพาะในวงโคจร')),
      O(T('It tips over', 'Она опрокинется', 'จรวดจะล้มลง'))],
    T('Thrust must exceed weight to lift off: T/W > 1. Real launchers start at 1.2–1.5 (Falcon 9 about 1.4, Soyuz 1.4), both to climb and to spend less time fighting gravity.',
      'Чтобы оторваться, тяга должна превышать вес: тяговооружённость > 1. У реальных ракет она на старте 1,2–1,5 (Falcon 9 около 1,4, «Союз» 1,4) — чтобы набирать высоту и меньше терять на гравитацию.',
      'แรงขับต้องมากกว่าน้ำหนักจึงจะขึ้นได้ คือ T/W > 1 จรวดจริงเริ่มที่ 1.2–1.5 (Falcon 9 ประมาณ 1.4 โซยุซ 1.4) ทั้งเพื่อไต่ระดับและเพื่อเสียให้แรงโน้มถ่วงน้อยลง')),
  choice('r-propellants', 2, 1, K, 'rocket.propellant',
    T('Which propellant gives the highest specific impulse among these?', 'Какое из этих топлив даёт наибольший удельный импульс?', 'เชื้อเพลิงชนิดใดต่อไปนี้ให้แรงดลจำเพาะสูงที่สุด'),
    [O(T('Liquid hydrogen with liquid oxygen', 'Жидкий водород с жидким кислородом', 'ไฮโดรเจนเหลวกับออกซิเจนเหลว'), true),
      O(T('Kerosene with liquid oxygen', 'Керосин с жидким кислородом', 'น้ำมันก๊าดกับออกซิเจนเหลว')),
      O(T('Solid propellant', 'Твёрдое топливо', 'เชื้อเพลิงแข็ง')),
      O(T('UDMH with nitrogen tetroxide', 'НДМГ с азотным тетраоксидом', 'UDMH กับไนโตรเจนเตตรอกไซด์'))],
    T('Hydrogen–oxygen reaches about 450 s in vacuum, kerosene–oxygen 310–350 s, the storable hypergolics 310–330 s, solids 270–290 s. Hydrogen pays for it with its low density: large, heavy tanks.',
      'Водород–кислород даёт около 450 с в пустоте, керосин–кислород 310–350 с, высококипящие компоненты 310–330 с, твёрдое топливо 270–290 с. Платой за водород служит низкая плотность: большие тяжёлые баки.',
      'ไฮโดรเจน–ออกซิเจนให้ประมาณ 450 วินาทีในสุญญากาศ น้ำมันก๊าด–ออกซิเจน 310–350 วินาที เชื้อเพลิงไฮเปอร์โกลิกที่เก็บได้ 310–330 วินาที และเชื้อเพลิงแข็ง 270–290 วินาที ข้อเสียของไฮโดรเจนคือความหนาแน่นต่ำ ต้องใช้ถังใหญ่และหนัก')),
  choice('r-soyuz-mass', 2, 1, K, 'rocket.staging',
    T('The chart shows the mass of a Soyuz-2.1a flown in this simulator. What makes the mass fall in a step at about T+120 s?', 'На графике — масса «Союза-2.1а», полёт которого выполнен в этом симуляторе. Почему масса скачком падает около T+120 с?', 'กราฟแสดงมวลของ Soyuz-2.1a ที่บินในโปรแกรมนี้ อะไรทำให้มวลลดลงเป็นขั้นที่ประมาณ T+120 วินาที'),
    [O(T('The four strap-on boosters separate', 'Отделяются четыре боковых блока', 'บูสเตอร์ด้านข้างทั้งสี่แยกตัวออก'), true),
      O(T('The fairing separates', 'Сбрасывается головной обтекатель', 'ฝาครอบส่วนหัวแยกออก')),
      O(T('The spacecraft separates', 'Отделяется корабль', 'ยานอวกาศแยกตัว')),
      O(T('The engines throttle down', 'Двигатели дросселируются', 'เครื่องยนต์ลดแรงขับ'))],
    T('The four blocks B, V, G and D burn out together at about T+120 s and fall away with their empty tanks. The fairing, a few tonnes, goes at T+157 s: only a small step on this scale.',
      'Четыре блока Б, В, Г и Д одновременно выключаются около T+120 с и отделяются вместе с пустыми баками. Головной обтекатель массой в несколько тонн сбрасывается на T+157 с — на этом масштабе это лишь небольшая ступенька.',
      'บล็อก B, V, G และ D ทั้งสี่ดับพร้อมกันที่ประมาณ T+120 วินาทีแล้วหลุดออกไปพร้อมถังเปล่า ส่วนฝาครอบซึ่งหนักไม่กี่ตันแยกที่ T+157 วินาที เป็นเพียงขั้นเล็ก ๆ บนมาตราส่วนนี้'),
    { figure: chart('soyuz-iss', 'mass', undefined, 320) }),
  numeric('r-tsiolkovsky-calc', 2, 2, K, 'rocket.tsiolkovsky',
    T('A stage with a specific impulse of {isp} s burns from {m0} t down to {mf} t. Work out its Δv (m/s), taking g0 = 9.81 m/s².',
      'Ступень с удельным импульсом {isp} с вырабатывает топливо, и её масса уменьшается с {m0} т до {mf} т. Рассчитайте Δv (м/с), приняв g0 = 9,81 м/с².',
      'ขั้นจรวดที่มีแรงดลจำเพาะ {isp} วินาที เผาเชื้อเพลิงจนมวลลดจาก {m0} ตัน เหลือ {mf} ตัน คำนวณ Δv (ม./วินาที) โดยใช้ g0 = 9.81 ม./วินาที²'),
    [{ name: 'isp', min: 280, max: 450, step: 5 }, { name: 'm0', min: 100, max: 500, step: 10 }, { name: 'mf', min: 20, max: 90, step: 5 }],
    'isp * 9.81 * ln(m0 / mf)', 'm/s', 1,
    T('Δv = Isp·g0·ln(m0/mf). The mass units cancel in the ratio.', 'Δv = Iуд·g0·ln(m0/mк). Единицы массы в отношении сокращаются.', 'Δv = Isp·g0·ln(m0/mf) หน่วยของมวลตัดกันในอัตราส่วน'),
    { lessons: ['orbit-payload'] }),
  choice('r-maxq-chart', 2, 2, U, 'aero.maxq',
    T('The chart is the dynamic pressure of a Falcon 9 flown in this simulator. When is max-Q, and why does q fall afterwards although the rocket keeps speeding up?', 'На графике — скоростной напор Falcon 9 в полёте, выполненном в этом симуляторе. Когда наступает максимальный напор и почему потом q падает, хотя ракета продолжает разгоняться?', 'กราฟคือความดันพลวัตของ Falcon 9 ที่บินในโปรแกรมนี้ ค่าสูงสุด (max-Q) เกิดเมื่อใด และทำไม q จึงลดลงหลังจากนั้นทั้งที่จรวดยังเร่งความเร็วอยู่'),
    [O(T('At about T+50 s; the air density ρ falls faster than V² grows', 'Около T+50 с; плотность воздуха ρ падает быстрее, чем растёт V²', 'ประมาณ T+50 วินาที เพราะความหนาแน่นอากาศ ρ ลดลงเร็วกว่าที่ V² เพิ่มขึ้น'), true),
      O(T('At about T+50 s; the engines throttle down', 'Около T+50 с; двигатели дросселируются', 'ประมาณ T+50 วินาที เพราะเครื่องยนต์ลดแรงขับ'), false,
        T('q falls because the engines give less thrust', 'q падает из-за уменьшения тяги', 'q ลดลงเพราะเครื่องยนต์ให้แรงขับน้อยลง')),
      O(T('At about T+150 s, at stage separation', 'Около T+150 с, при разделении ступеней', 'ประมาณ T+150 วินาที ตอนแยกขั้น')),
      O(T('At about T+20 s, just after the pitch-over', 'Около T+20 с, сразу после начала разворота по тангажу', 'ประมาณ T+20 วินาที หลังเริ่มเอียงพิตช์'))],
    T('Density falls roughly tenfold every 16 km. Low down, speed wins and q climbs; from about 7–12 km the thinning air wins and q falls. Here max-Q is 22.8 kPa at T+50 s.',
      'Плотность падает примерно в десять раз на каждые 16 км. Внизу побеждает скорость, и q растёт; примерно с 7–12 км побеждает разрежение воздуха, и q падает. Здесь максимальный напор — 22,8 кПа на T+50 с.',
      'ความหนาแน่นอากาศลดลงราวสิบเท่าทุก ๆ 16 กม. ช่วงต่ำ ความเร็วชนะ q จึงเพิ่มขึ้น ตั้งแต่ประมาณ 7–12 กม. อากาศที่เบาบางลงชนะ q จึงลดลง ในเที่ยวบินนี้ max-Q คือ 22.8 kPa ที่ T+50 วินาที'),
    { figure: chart('f9-leo', 'q', undefined, 200), lessons: ['guid-maxq'] }),
  choice('r-gravity-loss', 2, 2, U, 'rocket.losses',
    T('Two rockets have the same Δv, but one lifts off at T/W 1.15 and the other at 1.6. Which loses more to gravity on the way up, and why?', 'У двух ракет одинаковый запас Δv, но одна стартует с тяговооружённостью 1,15, другая — 1,6. Какая больше теряет на гравитацию и почему?', 'จรวดสองลำมี Δv เท่ากัน ลำหนึ่งออกตัวด้วย T/W 1.15 อีกลำ 1.6 ลำใดเสียให้แรงโน้มถ่วงมากกว่าระหว่างไต่ระดับ เพราะอะไร'),
    [O(T('The 1.15 one: it climbs for longer while gravity takes g·sin θ from its speed every second', 'С 1,15: она дольше набирает высоту, а тяготение каждую секунду отнимает g·sin θ скорости', 'ลำที่ 1.15 เพราะใช้เวลาไต่นานกว่า ขณะที่แรงโน้มถ่วงดึงความเร็วไป g·sin θ ทุกวินาที'), true),
      O(T('The 1.6 one: more thrust means more loss', 'С 1,6: больше тяга — больше потери', 'ลำที่ 1.6 เพราะแรงขับมากกว่าจึงเสียมากกว่า'), false,
        T('losses grow with thrust', 'потери растут с тягой', 'การสูญเสียเพิ่มขึ้นตามแรงขับ')),
      O(T('Both the same: gravity loss depends only on the orbit', 'Одинаково: гравитационные потери зависят только от орбиты', 'เท่ากัน เพราะการสูญเสียจากแรงโน้มถ่วงขึ้นกับวงโคจรเท่านั้น')),
      O(T('Neither: gravity loss only happens in orbit', 'Никакая: гравитационные потери бывают только на орбите', 'ไม่มีลำใดเสีย การสูญเสียจากแรงโน้มถ่วงเกิดในวงโคจรเท่านั้น'))],
    T('The gravity loss is the integral of g·sin θ over the powered flight. A sluggish rocket spends longer climbing steeply, so it loses more; too much thrust costs structure and aerodynamic loads instead. Real launchers lose 1–1.5 km/s to gravity.',
      'Гравитационные потери — интеграл g·sin θ по активному участку. «Вялая» ракета дольше летит круто вверх и теряет больше; избыточная тяга, наоборот, обходится массой конструкции и аэродинамическими нагрузками. Реальные носители теряют на гравитацию 1–1,5 км/с.',
      'การสูญเสียจากแรงโน้มถ่วงคือปริพันธ์ของ g·sin θ ตลอดช่วงที่เครื่องยนต์ทำงาน จรวดที่อืดใช้เวลาไต่ชันนานกว่าจึงเสียมากกว่า แต่แรงขับที่มากเกินไปก็ต้องแลกด้วยน้ำหนักโครงสร้างและภาระทางอากาศพลศาสตร์ จรวดจริงเสียให้แรงโน้มถ่วง 1–1.5 กม./วินาที'),
    { lessons: ['fail-engine-out'] }),
  choice('r-throttle-maxq', 2, 2, K, 'aero.maxq',
    T('Why do many launchers throttle their engines down through max-Q?', 'Зачем многие носители дросселируют двигатели в районе максимального напора?', 'ทำไมจรวดนำส่งหลายลำจึงลดแรงขับช่วง max-Q'),
    [O(T('To keep the aerodynamic loads on the structure within limits', 'Чтобы аэродинамические нагрузки на конструкцию не превысили допустимых', 'เพื่อให้ภาระทางอากาศพลศาสตร์ต่อโครงสร้างอยู่ในขีดจำกัด'), true),
      O(T('To save propellant for orbit', 'Чтобы сэкономить топливо для орбиты', 'เพื่อประหยัดเชื้อเพลิงไว้ใช้ในวงโคจร')),
      O(T('To reduce the noise near the pad', 'Чтобы уменьшить шум у стартового комплекса', 'เพื่อลดเสียงดังใกล้ฐานปล่อย')),
      O(T('Because the engines overheat at that altitude', 'Потому что на этой высоте двигатели перегреваются', 'เพราะเครื่องยนต์ร้อนเกินไปที่ระดับนั้น'))],
    T('Loads scale with q and with the angle of attack. Flying slower through the densest part of the ascent lowers the peak q, at the price of a little more gravity loss.',
      'Нагрузки пропорциональны q и углу атаки. Медленнее проходя самый плотный участок, ракета снижает пик q ценой небольшого роста гравитационных потерь.',
      'ภาระแปรตาม q และมุมปะทะ การบินช้าลงผ่านช่วงที่อากาศหนาแน่นที่สุดช่วยลดค่า q สูงสุด โดยแลกกับการสูญเสียจากแรงโน้มถ่วงเพิ่มขึ้นเล็กน้อย'),
    { lessons: ['guid-maxq'] }),
  choice('r-g-peak', 2, 2, U, 'rocket.acceleration',
    T('The chart is the load factor of a Falcon 9 flown in this simulator. Why does it climb to its highest just before the first stage cuts off?', 'На графике — перегрузка Falcon 9 в полёте, выполненном в этом симуляторе. Почему она достигает максимума непосредственно перед выключением первой ступени?', 'กราฟคือตัวประกอบภาระของ Falcon 9 ที่บินในโปรแกรมนี้ ทำไมจึงขึ้นไปสูงสุดก่อนขั้นที่ 1 ดับเครื่องพอดี'),
    [O(T('The thrust stays about the same while the mass keeps falling, so the acceleration grows', 'Тяга почти постоянна, а масса всё уменьшается, поэтому ускорение растёт', 'แรงขับเกือบคงที่ ขณะที่มวลลดลงเรื่อย ๆ ความเร่งจึงเพิ่มขึ้น'), true),
      O(T('The air pushes harder at that altitude', 'На этой высоте сильнее давит воздух', 'อากาศดันแรงขึ้นที่ระดับนั้น')),
      O(T('Gravity is strongest there', 'Там сильнее всего тяготение', 'แรงโน้มถ่วงแรงที่สุดที่ตรงนั้น'), false,
        T('the load factor includes gravity, so it peaks where gravity is strongest', 'перегрузка включает тяготение и потому максимальна там, где оно сильнее', 'ตัวประกอบภาระรวมแรงโน้มถ่วงไว้ จึงสูงสุดตรงที่แรงโน้มถ่วงแรงที่สุด')),
      O(T('The second stage has already lit', 'Уже включилась вторая ступень', 'ขั้นที่ 2 จุดเครื่องไปแล้ว'))],
    T('n = F/(m·g0): a stage that has burnt most of its propellant is light, so the same thrust accelerates it far harder — 4.6 g here. At cut-off it drops to zero, and the lighter second stage begins again below 1 g.',
      'n = P/(m·g0): выработавшая топливо ступень лёгкая, и та же тяга разгоняет её гораздо сильнее — здесь до 4,6. При выключении перегрузка падает до нуля, а вторая ступень начинает снова ниже единицы.',
      'n = F/(m·g0) ขั้นที่เผาเชื้อเพลิงไปเกือบหมดจะเบา แรงขับเท่าเดิมจึงเร่งได้แรงกว่ามาก ในที่นี้ถึง 4.6 g เมื่อดับเครื่องค่าจะตกเป็นศูนย์ แล้วขั้นที่ 2 เริ่มใหม่ที่ต่ำกว่า 1 g'),
    { figure: chart('f9-leo', 'gLoad', undefined, 540) }),
  choice('r-isp-vacuum', 2, 2, U, 'rocket.isp',
    T('The same engine has a higher specific impulse in vacuum than at sea level. Why?', 'У одного и того же двигателя удельный импульс в пустоте выше, чем у земли. Почему?', 'เครื่องยนต์ตัวเดียวกันมีแรงดลจำเพาะในสุญญากาศสูงกว่าที่ระดับน้ำทะเล เพราะอะไร'),
    [O(T('The atmosphere\'s pressure on the nozzle exit pushes back against the thrust', 'Атмосферное давление на срез сопла противодействует тяге', 'ความดันบรรยากาศที่ปากหัวฉีดดันต้านแรงขับ'), true),
      O(T('The propellant burns hotter in vacuum', 'В пустоте топливо горит горячее', 'เชื้อเพลิงเผาไหม้ร้อนกว่าในสุญญากาศ')),
      O(T('Gravity is weaker higher up', 'Выше тяготение слабее', 'ที่สูงขึ้นแรงโน้มถ่วงอ่อนลง'), false,
        T('Isp depends on the local gravity', 'удельный импульс зависит от местного ускорения свободного падения', 'แรงดลจำเพาะขึ้นกับความเร่งโน้มถ่วงเฉพาะที่')),
      O(T('There is no drag in vacuum', 'В пустоте нет сопротивления', 'ในสุญญากาศไม่มีแรงต้าน'))],
    T('Thrust = ṁ·ve + (pe − pa)·Ae. With pa = 0 the last term grows, and a vacuum engine can use a far larger nozzle: Merlin 1D 282 s at sea level, Merlin Vacuum 348 s.',
      'P = ṁ·wa + (pa − pн)·Sa. При pн = 0 последний член растёт, а высотный двигатель может иметь гораздо большее сопло: Merlin 1D — 282 с у земли, Merlin Vacuum — 348 с.',
      'แรงขับ = ṁ·ve + (pe − pa)·Ae เมื่อ pa = 0 พจน์สุดท้ายเพิ่มขึ้น และเครื่องยนต์สำหรับสุญญากาศใช้หัวฉีดที่ใหญ่กว่ามากได้ Merlin 1D ให้ 282 วินาทีที่ระดับน้ำทะเล ส่วน Merlin Vacuum ให้ 348 วินาที')),
  choice('r-dv-leo', 2, 2, K, 'rocket.budget',
    T('About how much Δv must a launcher deliver to reach a low orbit, counting the losses to gravity and drag?', 'Какую примерно характеристическую скорость должен обеспечить носитель для выхода на низкую орбиту с учётом гравитационных и аэродинамических потерь?', 'จรวดนำส่งต้องให้ Δv ประมาณเท่าใดจึงจะเข้าวงโคจรต่ำได้ เมื่อรวมการสูญเสียจากแรงโน้มถ่วงและแรงต้าน'),
    [O(T('About 9.3–10 km/s', 'Около 9,3–10 км/с', 'ประมาณ 9.3–10 กม./วินาที'), true),
      O(T('Exactly 7.8 km/s, the orbital speed', 'Ровно 7,8 км/с — орбитальную скорость', 'เท่ากับ 7.8 กม./วินาทีพอดี คืออัตราเร็ววงโคจร')),
      O(T('About 3 km/s', 'Около 3 км/с', 'ประมาณ 3 กม./วินาที')),
      O(T('About 20 km/s', 'Около 20 км/с', 'ประมาณ 20 กม./วินาที'))],
    T('7.8 km/s of orbital speed, plus 1–1.5 km/s to gravity, 0.1–0.2 km/s to drag and some to steering, less the Earth\'s rotation. The flights in this simulator spend 9.5–9.8 km/s.',
      '7,8 км/с орбитальной скорости плюс 1–1,5 км/с гравитационных потерь, 0,1–0,2 км/с аэродинамических и немного на управление, минус вклад вращения Земли. Полёты в этом симуляторе расходуют 9,5–9,8 км/с.',
      'อัตราเร็ววงโคจร 7.8 กม./วินาที บวกการสูญเสียจากแรงโน้มถ่วง 1–1.5 กม./วินาที แรงต้าน 0.1–0.2 กม./วินาที และการบังคับทิศอีกเล็กน้อย ลบด้วยความเร็วจากการหมุนของโลก เที่ยวบินในโปรแกรมนี้ใช้ 9.5–9.8 กม./วินาที')),
  numeric('r-mass-ratio', 2, 3, K, 'rocket.tsiolkovsky',
    T('A stage must give {dv} m/s with a specific impulse of {isp} s. What mass ratio m0/mf does it need? (g0 = 9.81 m/s²)',
      'Ступень должна обеспечить {dv} м/с при удельном импульсе {isp} с. Какое отношение масс m0/mк для этого нужно? (g0 = 9,81 м/с²)',
      'ขั้นจรวดต้องให้ Δv {dv} ม./วินาที ด้วยแรงดลจำเพาะ {isp} วินาที ต้องมีอัตราส่วนมวล m0/mf เท่าใด (g0 = 9.81 ม./วินาที²)'),
    [{ name: 'dv', min: 2000, max: 6000, step: 100 }, { name: 'isp', min: 280, max: 450, step: 5 }], 'exp(dv / (isp * 9.81))', '', 2,
    T('Invert Tsiolkovsky: m0/mf = exp(Δv/(Isp·g0)). Past about 10 the structure can hardly be built light enough — the reason for staging.',
      'Обратите формулу Циолковского: m0/mк = exp(Δv/(Iуд·g0)). При отношении больше примерно 10 конструкцию почти невозможно сделать достаточно лёгкой — отсюда многоступенчатость.',
      'กลับสมการซีออลคอฟสกี: m0/mf = exp(Δv/(Isp·g0)) เมื่ออัตราส่วนเกินราว 10 แทบสร้างโครงสร้างให้เบาพอไม่ได้ จึงต้องแบ่งเป็นหลายขั้น'),
    { lessons: ['orbit-payload'] }),
  numeric('r-q-calc', 2, 3, K, 'aero.q',
    T('A rocket flies at {v} m/s through air of density {rho} kg/m³. Work out the dynamic pressure (kPa).',
      'Ракета летит со скоростью {v} м/с в воздухе плотностью {rho} кг/м³. Рассчитайте скоростной напор (кПа).',
      'จรวดบินด้วยอัตราเร็ว {v} ม./วินาที ผ่านอากาศที่มีความหนาแน่น {rho} กก./ม.³ คำนวณความดันพลวัต (kPa)'),
    [{ name: 'v', min: 200, max: 700, step: 10 }, { name: 'rho', min: 0.1, max: 0.6, step: 0.02 }], '0.5 * rho * v^2 / 1000', 'kPa', 2,
    T('q = ½ρV², in pascals when ρ is in kg/m³ and V in m/s; divide by 1 000 for kPa. Launchers peak at 25–40 kPa.',
      'q = ½ρV² — в паскалях, если ρ в кг/м³ и V в м/с; для кПа разделите на 1 000. У носителей максимум 25–40 кПа.',
      'q = ½ρV² มีหน่วยปาสกาลเมื่อ ρ เป็น กก./ม.³ และ V เป็น ม./วินาที หารด้วย 1 000 เพื่อเป็น kPa จรวดนำส่งมีค่าสูงสุดราว 25–40 kPa'),
    { lessons: ['guid-maxq'] }),
  choice('r-engine-out-predict', 2, 3, U, 'failure.engineOut',
    T('Predict: one of Falcon 9\'s nine first-stage engines fails at T+80 s and the flight goes on. When does the first stage cut off, compared with a flight without the failure? After answering, compare the thrust of the two flights on the chart.',
      'Предскажите: один из девяти двигателей первой ступени Falcon 9 отказывает на T+80 с, полёт продолжается. Когда выключится первая ступень по сравнению с полётом без отказа? После ответа сравните тягу двух полётов на графике.',
      'จงทำนาย: เครื่องยนต์หนึ่งในเก้าเครื่องของขั้นที่ 1 ของ Falcon 9 ดับที่ T+80 วินาทีและการบินดำเนินต่อไป ขั้นที่ 1 จะดับเครื่องเมื่อใดเทียบกับเที่ยวบินที่ไม่มีความล้มเหลว เมื่อตอบแล้วให้เปรียบเทียบแรงขับของทั้งสองเที่ยวบินบนกราฟ'),
    [O(T('Later: the same propellant is burnt by fewer engines', 'Позже: то же топливо вырабатывают меньше двигателей', 'ช้ากว่า เพราะเชื้อเพลิงเท่าเดิมถูกเผาด้วยเครื่องยนต์ที่น้อยลง'), true),
      O(T('Earlier: the rocket has lost thrust', 'Раньше: ракета потеряла тягу', 'เร็วกว่า เพราะจรวดสูญเสียแรงขับ'), false,
        T('losing an engine shortens the burn', 'отказ двигателя сокращает время работы ступени', 'การเสียเครื่องยนต์ทำให้เผาไหม้สั้นลง')),
      O(T('At the same time: the guidance keeps to its schedule', 'Одновременно: наведение выдерживает циклограмму', 'เวลาเดียวกัน เพราะระบบนำวิถีรักษาตารางเวลาไว้')),
      O(T('Never: the stage has to be shut down at once', 'Никогда: ступень немедленно отключается', 'ไม่ดับเอง เพราะต้องสั่งปิดขั้นทันที'))],
    T('Eight engines burn 8/9 of the propellant flow, so the stage runs about 8 s longer (MECO at T+159.5 s against T+151.7 s here). The thrust drops by a ninth at T+80 s and the rest of the flight pays for it in gravity loss.',
      'Восемь двигателей потребляют 8/9 расхода, поэтому ступень работает примерно на 8 с дольше (здесь выключение на T+159,5 с против T+151,7 с). Тяга на T+80 с падает на девятую часть, и оставшийся полёт расплачивается за это гравитационными потерями.',
      'เครื่องยนต์แปดเครื่องใช้อัตราการไหลของเชื้อเพลิงเพียง 8/9 ขั้นจึงทำงานนานขึ้นประมาณ 8 วินาที (ในที่นี้ดับที่ T+159.5 วินาที เทียบกับ T+151.7 วินาที) แรงขับลดลงหนึ่งในเก้าที่ T+80 วินาที และช่วงที่เหลือของการบินต้องจ่ายคืนเป็นการสูญเสียจากแรงโน้มถ่วง'),
    { observe: chart('f9-leo', 'thrust', ['f9-leo-engine-out'], 200), lessons: ['fail-engine-out'] }),
  choice('r-payload-upper', 2, 3, U, 'rocket.staging',
    T('Adding 100 kg of payload to a two-stage rocket costs Δv in both stages. Where does it cost more?', 'Добавление 100 кг полезной нагрузки к двухступенчатой ракете отнимает Δv у обеих ступеней. У какой больше?', 'การเพิ่มน้ำหนักบรรทุก 100 กก. ให้จรวดสองขั้นทำให้เสีย Δv ทั้งสองขั้น ขั้นใดเสียมากกว่า'),
    [O(T('In the second stage: 100 kg is a much larger part of its mass', 'У второй ступени: для неё 100 кг — гораздо большая доля массы', 'ขั้นที่ 2 เพราะ 100 กก. เป็นสัดส่วนที่ใหญ่กว่ามากของมวลขั้นนี้'), true),
      O(T('In the first stage: it lifts the whole rocket', 'У первой ступени: она поднимает всю ракету', 'ขั้นที่ 1 เพราะต้องยกจรวดทั้งลำ'), false,
        T('the first stage feels payload most because it carries the most', 'первая ступень сильнее всего чувствует нагрузку, раз несёт больше всех', 'ขั้นที่ 1 รับผลของน้ำหนักบรรทุกมากที่สุดเพราะแบกมากที่สุด')),
      O(T('The same in both', 'Одинаково у обеих', 'เท่ากันทั้งสองขั้น')),
      O(T('Neither: 100 kg is too little to matter', 'Ни у какой: 100 кг слишком мало', 'ไม่มีขั้นใดเสีย 100 กก. น้อยเกินจะมีผล'))],
    T('The stage\'s Δv depends on ln(m0/mf). 100 kg changes the first stage\'s 550 t hardly at all, but a second stage ending at 15 t feels it: about 17 m/s on Falcon 9, against 1–2 m/s on the first stage.',
      'Δv ступени определяется ln(m0/mк). 100 кг почти не меняют 550 т первой ступени, но ощутимы для второй, конечная масса которой около 15 т: примерно 17 м/с у Falcon 9 против 1–2 м/с у первой ступени.',
      'Δv ของแต่ละขั้นขึ้นกับ ln(m0/mf) มวล 100 กก. แทบไม่เปลี่ยน 550 ตันของขั้นที่ 1 แต่ขั้นที่ 2 ซึ่งมีมวลตอนหมดเชื้อเพลิงราว 15 ตันจะรู้สึกได้ ประมาณ 17 ม./วินาทีสำหรับ Falcon 9 เทียบกับเพียง 1–2 ม./วินาทีที่ขั้นที่ 1'),
    { lessons: ['orbit-payload'] }),
];
