/** Area 3, rocket performance and flight through the atmosphere (roadmap E03). */
import { K, O, T, U, chart, choice, diagram, multi, numeric, order } from './helpers';
import flights from '../flights.json';

// the values the chart-reading questions ask for, as the recorded flight has them
const F9 = flights['f9-leo'];
const MAX_Q = Math.max(...F9.series.q);
const MECO_T = (F9.events as Array<[number, string]>).find(([, key]) => key === 'evt.meco')![0];

export const ROCKETS: readonly unknown[] = [
  choice('r-isp', 3, 1, K, 'rocket.isp',
    T('What does an engine\'s specific impulse measure?', 'Что характеризует удельный импульс двигателя?', 'แรงดลจำเพาะ (specific impulse) ของเครื่องยนต์วัดอะไร'),
    [O(T('How much thrust it gets from each unit of propellant burnt per second: its efficiency', 'Сколько тяги даёт каждая единица расхода топлива в секунду — его экономичность', 'แรงขับที่ได้ต่อเชื้อเพลิงหนึ่งหน่วยที่เผาต่อวินาที หรือประสิทธิภาพของเครื่องยนต์'), true),
      O(T('Its total thrust', 'Его полную тягу', 'แรงขับทั้งหมด')),
      O(T('How long it can burn', 'Как долго он может работать', 'ระยะเวลาที่เผาไหม้ได้')),
      O(T('The shock it gives the rocket at ignition', 'Удар, который он передаёт ракете при запуске', 'แรงกระแทกที่ส่งให้จรวดตอนจุดระเบิด'))],
    T('Isp = F/(ṁ·g0), in seconds; the exhaust velocity is Isp·g0. A Merlin 1D gives about 282 s at sea level, an RD-0110 326 s in vacuum, a hydrogen engine about 450 s.',
      'Iуд = P/(ṁ·g0), в секундах; скорость истечения равна Iуд·g0. Merlin 1D даёт около 282 с у земли, РД-0110 — 326 с в пустоте, водородный двигатель — около 450 с.',
      'Isp = F/(ṁ·g0) มีหน่วยเป็นวินาที ความเร็วไอเสียเท่ากับ Isp·g0 เครื่อง Merlin 1D ให้ประมาณ 282 วินาทีที่ระดับน้ำทะเล RD-0110 ให้ 326 วินาทีในสุญญากาศ และเครื่องยนต์ไฮโดรเจนประมาณ 450 วินาที')),
  choice('r-tsiolkovsky', 3, 1, K, 'rocket.tsiolkovsky',
    T('Which is Tsiolkovsky\'s rocket equation?', 'Какая из формул — формула Циолковского?', 'ข้อใดคือสมการจรวดของซีออลคอฟสกี'),
    [O(T('Δv = Isp·g0·ln(m0/mf)', 'Δv = Iуд·g0·ln(m0/mк)', 'Δv = Isp·g0·ln(m0/mf)'), true),
      O(T('Δv = F·t/m', 'Δv = P·t/m', 'Δv = F·t/m')),
      O(T('Δv = √(2μ/r)', 'Δv = √(2μ/r)', 'Δv = √(2μ/r)')),
      O(T('Δv = Isp·g0·(m0 − mf)', 'Δv = Iуд·g0·(m0 − mк)', 'Δv = Isp·g0·(m0 − mf)'))],
    T('The velocity gained grows with the logarithm of the ratio of the mass at ignition to the mass at burn-out — which is why doubling the propellant does not double Δv.',
      'Приращение скорости растёт как логарифм отношения начальной массы к конечной, поэтому удвоение запаса топлива не удваивает Δv.',
      'ความเร็วที่เพิ่มขึ้นแปรตามลอการิทึมของอัตราส่วนมวลตอนจุดเครื่องต่อมวลตอนเชื้อเพลิงหมด การเพิ่มเชื้อเพลิงเป็นสองเท่าจึงไม่ทำให้ Δv เพิ่มเป็นสองเท่า'),
    { lessons: ['orbit-payload'] }),
  choice('r-q', 3, 1, K, 'aero.q',
    T('The dynamic pressure q on a rocket is…', 'Скоростной напор q, действующий на ракету, равен…', 'ความดันพลวัต q ที่กระทำต่อจรวดเท่ากับ…'),
    [O(T('½ρV²', '½ρV²', '½ρV²'), true), O(T('ρgh', 'ρgh', 'ρgh')), O(T('mV²', 'mV²', 'mV²')), O(T('F/A', 'P/S', 'F/A'))],
    T('q = ½ρV², with ρ the air density and V the airspeed. The aerodynamic forces on the vehicle scale with it, and so do the loads on its structure.',
      'q = ½ρV², где ρ — плотность воздуха, V — воздушная скорость. Пропорционально ему растут аэродинамические силы и нагрузки на конструкцию.',
      'q = ½ρV² โดย ρ คือความหนาแน่นอากาศ และ V คืออัตราเร็วเทียบอากาศ แรงทางอากาศพลศาสตร์และภาระต่อโครงสร้างแปรตามค่านี้'),
    { lessons: ['guid-maxq'] }),
  choice('r-twr', 3, 1, U, 'rocket.twr',
    T('A rocket\'s thrust-to-weight ratio at lift-off is 0.9. What happens when its engines reach full thrust?', 'Тяговооружённость ракеты на старте 0,9. Что произойдёт, когда двигатели выйдут на полную тягу?', 'จรวดมีอัตราส่วนแรงขับต่อน้ำหนักตอนออกตัว 0.9 จะเกิดอะไรขึ้นเมื่อเครื่องยนต์ทำงานเต็มแรงขับ'),
    [O(T('It stays on the pad until it has burnt off enough propellant — or never lifts off', 'Она останется на столе, пока не выработает достаточно топлива, — или не взлетит вовсе', 'จรวดจะค้างอยู่บนแท่นจนกว่าจะเผาเชื้อเพลิงไปมากพอ หรืออาจไม่ขึ้นเลย'), true),
      O(T('It rises slowly', 'Она медленно поднимется', 'จรวดจะค่อย ๆ ลอยขึ้น'), false,
        T('any thrust at all lifts a rocket, only more slowly', 'любая тяга поднимает ракету, только медленнее', 'แรงขับเท่าใดก็ยกจรวดขึ้นได้ เพียงแต่ช้ากว่า')),
      O(T('It rises normally: T/W only matters in orbit', 'Она нормально взлетит: тяговооружённость важна лишь на орбите', 'ขึ้นได้ตามปกติ อัตราส่วนนี้สำคัญเฉพาะในวงโคจร')),
      O(T('It tips over', 'Она опрокинется', 'จรวดจะล้มลง'))],
    T('Thrust must exceed weight to lift off: T/W > 1. Real launchers start at 1.2–1.5 (Falcon 9 about 1.4, Soyuz 1.4), both to climb and to spend less time fighting gravity.',
      'Чтобы оторваться, тяга должна превышать вес: тяговооружённость > 1. У реальных ракет она на старте 1,2–1,5 (Falcon 9 около 1,4, «Союз» 1,4) — чтобы набирать высоту и меньше терять на гравитацию.',
      'แรงขับต้องมากกว่าน้ำหนักจึงจะขึ้นได้ คือ T/W > 1 จรวดจริงเริ่มที่ 1.2–1.5 (Falcon 9 ประมาณ 1.4 โซยุซ 1.4) ทั้งเพื่อไต่ระดับและเพื่อเสียให้แรงโน้มถ่วงน้อยลง')),
  choice('r-propellants', 3, 1, K, 'rocket.propellant',
    T('Which propellant gives the highest specific impulse among these?', 'Какое из этих топлив даёт наибольший удельный импульс?', 'เชื้อเพลิงชนิดใดต่อไปนี้ให้แรงดลจำเพาะสูงที่สุด'),
    [O(T('Liquid hydrogen with liquid oxygen', 'Жидкий водород с жидким кислородом', 'ไฮโดรเจนเหลวกับออกซิเจนเหลว'), true),
      O(T('Kerosene with liquid oxygen', 'Керосин с жидким кислородом', 'น้ำมันก๊าดกับออกซิเจนเหลว')),
      O(T('Solid propellant', 'Твёрдое топливо', 'เชื้อเพลิงแข็ง')),
      O(T('UDMH with nitrogen tetroxide', 'НДМГ с азотным тетраоксидом', 'UDMH กับไนโตรเจนเตตรอกไซด์'))],
    T('Hydrogen–oxygen reaches about 450 s in vacuum, kerosene–oxygen 310–350 s, the storable hypergolics 310–330 s, solids 270–290 s. Hydrogen pays for it with its low density: large, heavy tanks.',
      'Водород–кислород даёт около 450 с в пустоте, керосин–кислород 310–350 с, высококипящие компоненты 310–330 с, твёрдое топливо 270–290 с. Платой за водород служит низкая плотность: большие тяжёлые баки.',
      'ไฮโดรเจน–ออกซิเจนให้ประมาณ 450 วินาทีในสุญญากาศ น้ำมันก๊าด–ออกซิเจน 310–350 วินาที เชื้อเพลิงไฮเปอร์โกลิกที่เก็บได้ 310–330 วินาที และเชื้อเพลิงแข็ง 270–290 วินาที ข้อเสียของไฮโดรเจนคือความหนาแน่นต่ำ ต้องใช้ถังใหญ่และหนัก')),
  choice('r-soyuz-mass', 3, 1, K, 'rocket.staging',
    T('The chart shows the mass of a Soyuz-2.1a flown in this simulator. What makes the mass fall in a step at about T+120 s?', 'На графике — масса «Союза-2.1а», полёт которого выполнен в этом симуляторе. Почему масса скачком падает около T+120 с?', 'กราฟแสดงมวลของ Soyuz-2.1a ที่บินในโปรแกรมนี้ อะไรทำให้มวลลดลงเป็นขั้นที่ประมาณ T+120 วินาที'),
    [O(T('The four strap-on boosters separate', 'Отделяются четыре боковых блока', 'บูสเตอร์ด้านข้างทั้งสี่แยกตัวออก'), true),
      O(T('The fairing separates', 'Сбрасывается головной обтекатель', 'ฝาครอบส่วนหัวแยกออก')),
      O(T('The spacecraft separates', 'Отделяется корабль', 'ยานอวกาศแยกตัว')),
      O(T('The engines throttle down', 'Двигатели дросселируются', 'เครื่องยนต์ลดแรงขับ'))],
    T('The four blocks B, V, G and D burn out together at about T+120 s and fall away with their empty tanks. The fairing, a few tonnes, goes at T+157 s: only a small step on this scale.',
      'Четыре блока Б, В, Г и Д одновременно выключаются около T+120 с и отделяются вместе с пустыми баками. Головной обтекатель массой в несколько тонн сбрасывается на T+157 с — на этом масштабе это лишь небольшая ступенька.',
      'บล็อก B, V, G และ D ทั้งสี่ดับพร้อมกันที่ประมาณ T+120 วินาทีแล้วหลุดออกไปพร้อมถังเปล่า ส่วนฝาครอบซึ่งหนักไม่กี่ตันแยกที่ T+157 วินาที เป็นเพียงขั้นเล็ก ๆ บนมาตราส่วนนี้'),
    { figure: chart('soyuz-iss', 'mass', undefined, 320) }),
  numeric('r-tsiolkovsky-calc', 3, 2, K, 'rocket.tsiolkovsky',
    T('A stage with a specific impulse of {isp} s burns from {m0} t down to {mf} t. Work out its Δv (m/s), taking g0 = 9.81 m/s².',
      'Ступень с удельным импульсом {isp} с вырабатывает топливо, и её масса уменьшается с {m0} т до {mf} т. Рассчитайте Δv (м/с), приняв g0 = 9,81 м/с².',
      'ขั้นจรวดที่มีแรงดลจำเพาะ {isp} วินาที เผาเชื้อเพลิงจนมวลลดจาก {m0} ตัน เหลือ {mf} ตัน คำนวณ Δv (ม./วินาที) โดยใช้ g0 = 9.81 ม./วินาที²'),
    [{ name: 'isp', min: 280, max: 450, step: 5 }, { name: 'm0', min: 100, max: 500, step: 10 }, { name: 'mf', min: 20, max: 90, step: 5 }],
    'isp * 9.81 * ln(m0 / mf)', 'm/s', 1,
    T('Δv = Isp·g0·ln(m0/mf). The mass units cancel in the ratio.', 'Δv = Iуд·g0·ln(m0/mк). Единицы массы в отношении сокращаются.', 'Δv = Isp·g0·ln(m0/mf) หน่วยของมวลตัดกันในอัตราส่วน'),
    { lessons: ['orbit-payload'] }),
  choice('r-maxq-chart', 3, 2, U, 'aero.maxq',
    T('The chart is the dynamic pressure of a Falcon 9 flown in this simulator. When is max-Q, and why does q fall afterwards although the rocket keeps speeding up?', 'На графике — скоростной напор Falcon 9 в полёте, выполненном в этом симуляторе. Когда наступает максимальный напор и почему потом q падает, хотя ракета продолжает разгоняться?', 'กราฟคือความดันพลวัตของ Falcon 9 ที่บินในโปรแกรมนี้ ค่าสูงสุด (max-Q) เกิดเมื่อใด และทำไม q จึงลดลงหลังจากนั้นทั้งที่จรวดยังเร่งความเร็วอยู่'),
    [O(T('At about T+50 s; the air density ρ falls faster than V² grows', 'Около T+50 с; плотность воздуха ρ падает быстрее, чем растёт V²', 'ประมาณ T+50 วินาที เพราะความหนาแน่นอากาศ ρ ลดลงเร็วกว่าที่ V² เพิ่มขึ้น'), true),
      O(T('At about T+50 s; the engines throttle down', 'Около T+50 с; двигатели дросселируются', 'ประมาณ T+50 วินาที เพราะเครื่องยนต์ลดแรงขับ'), false,
        T('q falls because the engines give less thrust', 'q падает из-за уменьшения тяги', 'q ลดลงเพราะเครื่องยนต์ให้แรงขับน้อยลง')),
      O(T('At about T+150 s, at stage separation', 'Около T+150 с, при разделении ступеней', 'ประมาณ T+150 วินาที ตอนแยกขั้น')),
      O(T('At about T+20 s, just after the pitch-over', 'Около T+20 с, сразу после начала разворота по тангажу', 'ประมาณ T+20 วินาที หลังเริ่มเอียงพิตช์'))],
    T('Density falls roughly tenfold every 16 km. Low down, speed wins and q climbs; from about 7–12 km the thinning air wins and q falls. Here max-Q is 22.4 kPa at T+50 s.',
      'Плотность падает примерно в десять раз на каждые 16 км. Внизу побеждает скорость, и q растёт; примерно с 7–12 км побеждает разрежение воздуха, и q падает. Здесь максимальный напор — 22,4 кПа на T+50 с.',
      'ความหนาแน่นอากาศลดลงราวสิบเท่าทุก ๆ 16 กม. ช่วงต่ำ ความเร็วชนะ q จึงเพิ่มขึ้น ตั้งแต่ประมาณ 7–12 กม. อากาศที่เบาบางลงชนะ q จึงลดลง ในเที่ยวบินนี้ max-Q คือ 22.4 kPa ที่ T+50 วินาที'),
    { figure: chart('f9-leo', 'q', undefined, 200), lessons: ['guid-maxq'] }),
  choice('r-gravity-loss', 3, 2, U, 'rocket.losses',
    T('Two rockets have the same Δv, but one lifts off at T/W 1.15 and the other at 1.6. Which loses more to gravity on the way up, and why?', 'У двух ракет одинаковый запас Δv, но одна стартует с тяговооружённостью 1,15, другая — 1,6. Какая больше теряет на гравитацию и почему?', 'จรวดสองลำมี Δv เท่ากัน ลำหนึ่งออกตัวด้วย T/W 1.15 อีกลำ 1.6 ลำใดเสียให้แรงโน้มถ่วงมากกว่าระหว่างไต่ระดับ เพราะอะไร'),
    [O(T('The 1.15 one: it climbs for longer while gravity takes g·sin θ from its speed every second', 'С 1,15: она дольше набирает высоту, а тяготение каждую секунду отнимает g·sin θ скорости', 'ลำที่ 1.15 เพราะใช้เวลาไต่นานกว่า ขณะที่แรงโน้มถ่วงดึงความเร็วไป g·sin θ ทุกวินาที'), true),
      O(T('The 1.6 one: more thrust means more loss', 'С 1,6: больше тяга — больше потери', 'ลำที่ 1.6 เพราะแรงขับมากกว่าจึงเสียมากกว่า'), false,
        T('losses grow with thrust', 'потери растут с тягой', 'การสูญเสียเพิ่มขึ้นตามแรงขับ')),
      O(T('Both the same: gravity loss depends only on the orbit', 'Одинаково: гравитационные потери зависят только от орбиты', 'เท่ากัน เพราะการสูญเสียจากแรงโน้มถ่วงขึ้นกับวงโคจรเท่านั้น')),
      O(T('Neither: gravity loss only happens in orbit', 'Никакая: гравитационные потери бывают только на орбите', 'ไม่มีลำใดเสีย การสูญเสียจากแรงโน้มถ่วงเกิดในวงโคจรเท่านั้น'))],
    T('The gravity loss is the integral of g·sin θ over the powered flight. A sluggish rocket spends longer climbing steeply, so it loses more; too much thrust costs structure and aerodynamic loads instead. Real launchers lose 1–1.5 km/s to gravity.',
      'Гравитационные потери — интеграл g·sin θ по активному участку. «Вялая» ракета дольше летит круто вверх и теряет больше; избыточная тяга, наоборот, обходится массой конструкции и аэродинамическими нагрузками. Реальные носители теряют на гравитацию 1–1,5 км/с.',
      'การสูญเสียจากแรงโน้มถ่วงคือปริพันธ์ของ g·sin θ ตลอดช่วงที่เครื่องยนต์ทำงาน จรวดที่อืดใช้เวลาไต่ชันนานกว่าจึงเสียมากกว่า แต่แรงขับที่มากเกินไปก็ต้องแลกด้วยน้ำหนักโครงสร้างและภาระทางอากาศพลศาสตร์ จรวดจริงเสียให้แรงโน้มถ่วง 1–1.5 กม./วินาที'),
    { lessons: ['fail-engine-out'] }),
  choice('r-throttle-maxq', 3, 2, K, 'aero.maxq',
    T('Why do many launchers throttle their engines down through max-Q?', 'Зачем многие носители дросселируют двигатели в районе максимального напора?', 'ทำไมจรวดนำส่งหลายลำจึงลดแรงขับช่วง max-Q'),
    [O(T('To keep the aerodynamic loads on the structure within limits', 'Чтобы аэродинамические нагрузки на конструкцию не превысили допустимых', 'เพื่อให้ภาระทางอากาศพลศาสตร์ต่อโครงสร้างอยู่ในขีดจำกัด'), true),
      O(T('To save propellant for orbit', 'Чтобы сэкономить топливо для орбиты', 'เพื่อประหยัดเชื้อเพลิงไว้ใช้ในวงโคจร')),
      O(T('To reduce the noise near the pad', 'Чтобы уменьшить шум у стартового комплекса', 'เพื่อลดเสียงดังใกล้ฐานปล่อย')),
      O(T('Because the engines overheat at that altitude', 'Потому что на этой высоте двигатели перегреваются', 'เพราะเครื่องยนต์ร้อนเกินไปที่ระดับนั้น'))],
    T('Loads scale with q and with the angle of attack. Flying slower through the densest part of the ascent lowers the peak q, at the price of a little more gravity loss.',
      'Нагрузки пропорциональны q и углу атаки. Медленнее проходя самый плотный участок, ракета снижает пик q ценой небольшого роста гравитационных потерь.',
      'ภาระแปรตาม q และมุมปะทะ การบินช้าลงผ่านช่วงที่อากาศหนาแน่นที่สุดช่วยลดค่า q สูงสุด โดยแลกกับการสูญเสียจากแรงโน้มถ่วงเพิ่มขึ้นเล็กน้อย'),
    { lessons: ['guid-maxq'] }),
  choice('r-g-peak', 3, 2, U, 'rocket.acceleration',
    T('The chart is the load factor of a Falcon 9 flown in this simulator. Why does it climb to its highest just before the first stage cuts off?', 'На графике — перегрузка Falcon 9 в полёте, выполненном в этом симуляторе. Почему она достигает максимума непосредственно перед выключением первой ступени?', 'กราฟคือตัวประกอบภาระของ Falcon 9 ที่บินในโปรแกรมนี้ ทำไมจึงขึ้นไปสูงสุดก่อนขั้นที่ 1 ดับเครื่องพอดี'),
    [O(T('The thrust stays about the same while the mass keeps falling, so the acceleration grows', 'Тяга почти постоянна, а масса всё уменьшается, поэтому ускорение растёт', 'แรงขับเกือบคงที่ ขณะที่มวลลดลงเรื่อย ๆ ความเร่งจึงเพิ่มขึ้น'), true),
      O(T('The air pushes harder at that altitude', 'На этой высоте сильнее давит воздух', 'อากาศดันแรงขึ้นที่ระดับนั้น')),
      O(T('Gravity is strongest there', 'Там сильнее всего тяготение', 'แรงโน้มถ่วงแรงที่สุดที่ตรงนั้น'), false,
        T('the load factor includes gravity, so it peaks where gravity is strongest', 'перегрузка включает тяготение и потому максимальна там, где оно сильнее', 'ตัวประกอบภาระรวมแรงโน้มถ่วงไว้ จึงสูงสุดตรงที่แรงโน้มถ่วงแรงที่สุด')),
      O(T('The second stage has already lit', 'Уже включилась вторая ступень', 'ขั้นที่ 2 จุดเครื่องไปแล้ว'))],
    T('n = F/(m·g0): a stage that has burnt most of its propellant is light, so the same thrust accelerates it far harder — 4.6 g here. At cut-off it drops to zero, and the lighter second stage begins again below 1 g.',
      'n = P/(m·g0): выработавшая топливо ступень лёгкая, и та же тяга разгоняет её гораздо сильнее — здесь до 4,6. При выключении перегрузка падает до нуля, а вторая ступень начинает снова ниже единицы.',
      'n = F/(m·g0) ขั้นที่เผาเชื้อเพลิงไปเกือบหมดจะเบา แรงขับเท่าเดิมจึงเร่งได้แรงกว่ามาก ในที่นี้ถึง 4.6 g เมื่อดับเครื่องค่าจะตกเป็นศูนย์ แล้วขั้นที่ 2 เริ่มใหม่ที่ต่ำกว่า 1 g'),
    { figure: chart('f9-leo', 'gLoad', undefined, 540) }),
  choice('r-isp-vacuum', 3, 2, U, 'rocket.isp',
    T('The same engine has a higher specific impulse in vacuum than at sea level. Why?', 'У одного и того же двигателя удельный импульс в пустоте выше, чем у земли. Почему?', 'เครื่องยนต์ตัวเดียวกันมีแรงดลจำเพาะในสุญญากาศสูงกว่าที่ระดับน้ำทะเล เพราะอะไร'),
    [O(T('The atmosphere\'s pressure on the nozzle exit pushes back against the thrust', 'Атмосферное давление на срез сопла противодействует тяге', 'ความดันบรรยากาศที่ปากหัวฉีดดันต้านแรงขับ'), true),
      O(T('The propellant burns hotter in vacuum', 'В пустоте топливо горит горячее', 'เชื้อเพลิงเผาไหม้ร้อนกว่าในสุญญากาศ')),
      O(T('Gravity is weaker higher up', 'Выше тяготение слабее', 'ที่สูงขึ้นแรงโน้มถ่วงอ่อนลง'), false,
        T('Isp depends on the local gravity', 'удельный импульс зависит от местного ускорения свободного падения', 'แรงดลจำเพาะขึ้นกับความเร่งโน้มถ่วงเฉพาะที่')),
      O(T('There is no drag in vacuum', 'В пустоте нет сопротивления', 'ในสุญญากาศไม่มีแรงต้าน'))],
    T('Thrust = ṁ·ve + (pe − pa)·Ae. With pa = 0 the last term grows, and a vacuum engine can use a far larger nozzle: Merlin 1D 282 s at sea level, Merlin Vacuum 348 s.',
      'P = ṁ·wa + (pa − pн)·Sa. При pн = 0 последний член растёт, а высотный двигатель может иметь гораздо большее сопло: Merlin 1D — 282 с у земли, Merlin Vacuum — 348 с.',
      'แรงขับ = ṁ·ve + (pe − pa)·Ae เมื่อ pa = 0 พจน์สุดท้ายเพิ่มขึ้น และเครื่องยนต์สำหรับสุญญากาศใช้หัวฉีดที่ใหญ่กว่ามากได้ Merlin 1D ให้ 282 วินาทีที่ระดับน้ำทะเล ส่วน Merlin Vacuum ให้ 348 วินาที')),
  choice('r-dv-leo', 3, 2, K, 'rocket.budget',
    T('About how much Δv must a launcher deliver to reach a low orbit, counting the losses to gravity and drag?', 'Какую примерно характеристическую скорость должен обеспечить носитель для выхода на низкую орбиту с учётом гравитационных и аэродинамических потерь?', 'จรวดนำส่งต้องให้ Δv ประมาณเท่าใดจึงจะเข้าวงโคจรต่ำได้ เมื่อรวมการสูญเสียจากแรงโน้มถ่วงและแรงต้าน'),
    [O(T('About 9.3–10 km/s', 'Около 9,3–10 км/с', 'ประมาณ 9.3–10 กม./วินาที'), true),
      O(T('Exactly 7.8 km/s, the orbital speed', 'Ровно 7,8 км/с — орбитальную скорость', 'เท่ากับ 7.8 กม./วินาทีพอดี คืออัตราเร็ววงโคจร')),
      O(T('About 3 km/s', 'Около 3 км/с', 'ประมาณ 3 กม./วินาที')),
      O(T('About 20 km/s', 'Около 20 км/с', 'ประมาณ 20 กม./วินาที'))],
    T('7.8 km/s of orbital speed, plus 1–1.5 km/s to gravity, 0.1–0.2 km/s to drag and some to steering, less the Earth\'s rotation. The flights in this simulator spend 9.5–9.8 km/s.',
      '7,8 км/с орбитальной скорости плюс 1–1,5 км/с гравитационных потерь, 0,1–0,2 км/с аэродинамических и немного на управление, минус вклад вращения Земли. Полёты в этом симуляторе расходуют 9,5–9,8 км/с.',
      'อัตราเร็ววงโคจร 7.8 กม./วินาที บวกการสูญเสียจากแรงโน้มถ่วง 1–1.5 กม./วินาที แรงต้าน 0.1–0.2 กม./วินาที และการบังคับทิศอีกเล็กน้อย ลบด้วยความเร็วจากการหมุนของโลก เที่ยวบินในโปรแกรมนี้ใช้ 9.5–9.8 กม./วินาที')),
  numeric('r-mass-ratio', 3, 3, K, 'rocket.tsiolkovsky',
    T('A stage must give {dv} m/s with a specific impulse of {isp} s. What mass ratio m0/mf does it need? (g0 = 9.81 m/s²)',
      'Ступень должна обеспечить {dv} м/с при удельном импульсе {isp} с. Какое отношение масс m0/mк для этого нужно? (g0 = 9,81 м/с²)',
      'ขั้นจรวดต้องให้ Δv {dv} ม./วินาที ด้วยแรงดลจำเพาะ {isp} วินาที ต้องมีอัตราส่วนมวล m0/mf เท่าใด (g0 = 9.81 ม./วินาที²)'),
    [{ name: 'dv', min: 2000, max: 6000, step: 100 }, { name: 'isp', min: 280, max: 450, step: 5 }], 'exp(dv / (isp * 9.81))', '', 2,
    T('Invert Tsiolkovsky: m0/mf = exp(Δv/(Isp·g0)). Past about 10 the structure can hardly be built light enough — the reason for staging.',
      'Обратите формулу Циолковского: m0/mк = exp(Δv/(Iуд·g0)). При отношении больше примерно 10 конструкцию почти невозможно сделать достаточно лёгкой — отсюда многоступенчатость.',
      'กลับสมการซีออลคอฟสกี: m0/mf = exp(Δv/(Isp·g0)) เมื่ออัตราส่วนเกินราว 10 แทบสร้างโครงสร้างให้เบาพอไม่ได้ จึงต้องแบ่งเป็นหลายขั้น'),
    { lessons: ['orbit-payload'] }),
  numeric('r-q-calc', 3, 3, K, 'aero.q',
    T('A rocket flies at {v} m/s through air of density {rho} kg/m³. Work out the dynamic pressure (kPa).',
      'Ракета летит со скоростью {v} м/с в воздухе плотностью {rho} кг/м³. Рассчитайте скоростной напор (кПа).',
      'จรวดบินด้วยอัตราเร็ว {v} ม./วินาที ผ่านอากาศที่มีความหนาแน่น {rho} กก./ม.³ คำนวณความดันพลวัต (kPa)'),
    [{ name: 'v', min: 200, max: 700, step: 10 }, { name: 'rho', min: 0.1, max: 0.6, step: 0.02 }], '0.5 * rho * v^2 / 1000', 'kPa', 2,
    T('q = ½ρV², in pascals when ρ is in kg/m³ and V in m/s; divide by 1 000 for kPa. Launchers peak at 25–40 kPa.',
      'q = ½ρV² — в паскалях, если ρ в кг/м³ и V в м/с; для кПа разделите на 1 000. У носителей максимум 25–40 кПа.',
      'q = ½ρV² มีหน่วยปาสกาลเมื่อ ρ เป็น กก./ม.³ และ V เป็น ม./วินาที หารด้วย 1 000 เพื่อเป็น kPa จรวดนำส่งมีค่าสูงสุดราว 25–40 kPa'),
    { lessons: ['guid-maxq'] }),
  choice('r-engine-out-predict', 3, 3, U, 'failure.engineOut',
    T('Predict: one of Falcon 9\'s nine first-stage engines fails at T+80 s and the flight goes on. When does the first stage cut off, compared with a flight without the failure? After answering, compare the thrust of the two flights on the chart.',
      'Предскажите: один из девяти двигателей первой ступени Falcon 9 отказывает на T+80 с, полёт продолжается. Когда выключится первая ступень по сравнению с полётом без отказа? После ответа сравните тягу двух полётов на графике.',
      'จงทำนาย: เครื่องยนต์หนึ่งในเก้าเครื่องของขั้นที่ 1 ของ Falcon 9 ดับที่ T+80 วินาทีและการบินดำเนินต่อไป ขั้นที่ 1 จะดับเครื่องเมื่อใดเทียบกับเที่ยวบินที่ไม่มีความล้มเหลว เมื่อตอบแล้วให้เปรียบเทียบแรงขับของทั้งสองเที่ยวบินบนกราฟ'),
    [O(T('Later: the same propellant is burnt by fewer engines', 'Позже: то же топливо вырабатывают меньше двигателей', 'ช้ากว่า เพราะเชื้อเพลิงเท่าเดิมถูกเผาด้วยเครื่องยนต์ที่น้อยลง'), true),
      O(T('Earlier: the rocket has lost thrust', 'Раньше: ракета потеряла тягу', 'เร็วกว่า เพราะจรวดสูญเสียแรงขับ'), false,
        T('losing an engine shortens the burn', 'отказ двигателя сокращает время работы ступени', 'การเสียเครื่องยนต์ทำให้เผาไหม้สั้นลง')),
      O(T('At the same time: the guidance keeps to its schedule', 'Одновременно: наведение выдерживает циклограмму', 'เวลาเดียวกัน เพราะระบบนำวิถีรักษาตารางเวลาไว้')),
      O(T('Never: the stage has to be shut down at once', 'Никогда: ступень немедленно отключается', 'ไม่ดับเอง เพราะต้องสั่งปิดขั้นทันที'))],
    T('Eight engines burn 8/9 of the propellant flow, so the stage runs about 8 s longer (MECO at T+165.4 s against T+157.1 s here). The thrust drops by a ninth at T+80 s and the rest of the flight pays for it in gravity loss.',
      'Восемь двигателей потребляют 8/9 расхода, поэтому ступень работает примерно на 8 с дольше (здесь выключение на T+165,4 с против T+157,1 с). Тяга на T+80 с падает на девятую часть, и оставшийся полёт расплачивается за это гравитационными потерями.',
      'เครื่องยนต์แปดเครื่องใช้อัตราการไหลของเชื้อเพลิงเพียง 8/9 ขั้นจึงทำงานนานขึ้นประมาณ 8 วินาที (ในที่นี้ดับที่ T+165.4 วินาที เทียบกับ T+157.1 วินาที) แรงขับลดลงหนึ่งในเก้าที่ T+80 วินาที และช่วงที่เหลือของการบินต้องจ่ายคืนเป็นการสูญเสียจากแรงโน้มถ่วง'),
    { observe: chart('f9-leo', 'thrust', ['f9-leo-engine-out'], 200), lessons: ['fail-engine-out'] }),
  choice('r-payload-upper', 3, 3, U, 'rocket.staging',
    T('Adding 100 kg of payload to a two-stage rocket costs Δv in both stages. Where does it cost more?', 'Добавление 100 кг полезной нагрузки к двухступенчатой ракете отнимает Δv у обеих ступеней. У какой больше?', 'การเพิ่มน้ำหนักบรรทุก 100 กก. ให้จรวดสองขั้นทำให้เสีย Δv ทั้งสองขั้น ขั้นใดเสียมากกว่า'),
    [O(T('In the second stage: 100 kg is a much larger part of its mass', 'У второй ступени: для неё 100 кг — гораздо большая доля массы', 'ขั้นที่ 2 เพราะ 100 กก. เป็นสัดส่วนที่ใหญ่กว่ามากของมวลขั้นนี้'), true),
      O(T('In the first stage: it lifts the whole rocket', 'У первой ступени: она поднимает всю ракету', 'ขั้นที่ 1 เพราะต้องยกจรวดทั้งลำ'), false,
        T('the first stage feels payload most because it carries the most', 'первая ступень сильнее всего чувствует нагрузку, раз несёт больше всех', 'ขั้นที่ 1 รับผลของน้ำหนักบรรทุกมากที่สุดเพราะแบกมากที่สุด')),
      O(T('The same in both', 'Одинаково у обеих', 'เท่ากันทั้งสองขั้น')),
      O(T('Neither: 100 kg is too little to matter', 'Ни у какой: 100 кг слишком мало', 'ไม่มีขั้นใดเสีย 100 กก. น้อยเกินจะมีผล'))],
    T('The stage\'s Δv depends on ln(m0/mf). 100 kg changes the first stage\'s 550 t hardly at all, but a second stage ending at 15 t feels it: about 17 m/s on Falcon 9, against 1–2 m/s on the first stage.',
      'Δv ступени определяется ln(m0/mк). 100 кг почти не меняют 550 т первой ступени, но ощутимы для второй, конечная масса которой около 15 т: примерно 17 м/с у Falcon 9 против 1–2 м/с у первой ступени.',
      'Δv ของแต่ละขั้นขึ้นกับ ln(m0/mf) มวล 100 กก. แทบไม่เปลี่ยน 550 ตันของขั้นที่ 1 แต่ขั้นที่ 2 ซึ่งมีมวลตอนหมดเชื้อเพลิงราว 15 ตันจะรู้สึกได้ ประมาณ 17 ม./วินาทีสำหรับ Falcon 9 เทียบกับเพียง 1–2 ม./วินาทีที่ขั้นที่ 1'),
    { lessons: ['orbit-payload'] }),
  order('r-order-isp', 3, 2, K, 'rocket.ispOrder',
    T('Put these in order of specific impulse in vacuum, lowest first.', 'Расположите по удельному импульсу в пустоте, начиная с наименьшего.', 'เรียงตามแรงดลจำเพาะในสุญญากาศ จากน้อยที่สุดไปมากที่สุด'),
    [T('A cold-gas nitrogen thruster', 'Двигатель на холодном газе (азот)', 'ทรัสเตอร์ก๊าซเย็น (ไนโตรเจน)'),
      T('A solid rocket motor', 'Твердотопливный двигатель', 'มอเตอร์จรวดเชื้อเพลิงแข็ง'),
      T('A kerosene and liquid oxygen engine', 'Двигатель на керосине и жидком кислороде', 'เครื่องยนต์น้ำมันก๊าดกับออกซิเจนเหลว'),
      T('A liquid hydrogen and oxygen engine', 'Двигатель на жидких водороде и кислороде', 'เครื่องยนต์ไฮโดรเจนเหลวกับออกซิเจนเหลว'),
      T('An electric ion thruster', 'Электрический ионный двигатель', 'ทรัสเตอร์ไอออนไฟฟ้า')],
    T('About 70 s, 270–290 s, 310–360 s, 450–465 s and 1 500–4 000 s. The faster the exhaust, the higher the impulse: an ion thruster\'s is fastest of all, but its thrust is a fraction of a newton, useful only in orbit.',
      'Около 70 с, 270–290 с, 310–360 с, 450–465 с и 1 500–4 000 с. Чем быстрее истечение, тем выше импульс: у ионного двигателя оно самое быстрое, но тяга — доли ньютона, пригодна только на орбите.',
      'ประมาณ 70 วินาที 270–290 วินาที 310–360 วินาที 450–465 วินาที และ 1 500–4 000 วินาที ยิ่งไอเสียพุ่งเร็ว แรงดลจำเพาะยิ่งสูง ทรัสเตอร์ไอออนมีไอเสียเร็วที่สุด แต่แรงขับเพียงเศษเสี้ยวนิวตัน ใช้ได้เฉพาะในวงโคจร')),
  order('r-order-events', 3, 1, K, 'launch.sequence',
    T('Put the events of a Falcon 9 launch to low orbit in order.', 'Расположите события запуска Falcon 9 на низкую орбиту по порядку.', 'เรียงลำดับเหตุการณ์ของการปล่อย Falcon 9 สู่วงโคจรต่ำ'),
    [T('Lift-off', 'Старт', 'ยกตัวออกจากฐาน'),
      T('Max-Q, the highest dynamic pressure', 'Max-Q, наибольший скоростной напор', 'Max-Q ความดันพลวัตสูงสุด'),
      T('Main engine cut-off of the first stage (MECO)', 'Выключение двигателей первой ступени (MECO)', 'ดับเครื่องยนต์ขั้นที่หนึ่ง (MECO)'),
      T('Stage separation', 'Разделение ступеней', 'แยกขั้น'),
      T('Fairing jettison', 'Сброс головного обтекателя', 'ปลดฝาครอบส่วนหัว'),
      T('Second-stage engine cut-off (SECO)', 'Выключение двигателя второй ступени (SECO)', 'ดับเครื่องยนต์ขั้นที่สอง (SECO)')],
    T('In this simulator\'s flight: max-Q at about T+50 s, MECO at T+157 s, separation 3 s later, the fairing at T+217 s once the air is too thin to heat the payload, SECO at T+506 s.',
      'В полёте этого симулятора: max-Q около T+50 с, MECO — T+157 с, разделение через 3 с, обтекатель — T+217 с, когда воздух уже слишком разрежен, чтобы нагреть полезную нагрузку, SECO — T+506 с.',
      'ในการบินของโปรแกรมนี้: max-Q ประมาณ T+50 วินาที MECO ที่ T+157 วินาที แยกขั้นหลังจากนั้น 3 วินาที ปลดฝาครอบที่ T+217 วินาที เมื่ออากาศเบาบางจนไม่ทำให้สัมภาระร้อน และ SECO ที่ T+506 วินาที')),
  multi('r-multi-losses', 3, 2, U, 'rocket.lossKinds',
    T('Where does a launcher lose some of the Δv its engines give on the way to orbit? Choose every one.', 'На что ракета-носитель теряет часть Δv, сообщаемой двигателями, при выведении? Выберите всё.', 'ระหว่างทางสู่วงโคจร จรวดสูญเสีย Δv ที่เครื่องยนต์ให้ไปกับอะไรบ้าง เลือกทุกข้อที่ถูก'),
    [O(T('Gravity, while the thrust holds the rocket up', 'Гравитационные потери, пока тяга удерживает ракету', 'แรงโน้มถ่วง ขณะที่แรงขับต้องพยุงจรวดไว้'), true),
      O(T('Aerodynamic drag', 'Аэродинамическое сопротивление', 'แรงต้านอากาศ'), true),
      O(T('Steering: thrust not pointed along the velocity', 'Потери на управление: тяга не по вектору скорости', 'การบังคับทิศ: แรงขับไม่ได้ชี้ตามทิศความเร็ว'), true),
      O(T('The Earth\'s rotation', 'Вращение Земли', 'การหมุนของโลก'), false,
        T('The Earth turning under the rocket takes speed away from it.', 'Вращение Земли под ракетой отнимает у неё скорость.', 'โลกที่หมุนอยู่ใต้จรวดดึงความเร็วไปจากจรวด')),
      O(T('Burning in the vacuum of space', 'Работа двигателя в пустоте', 'การจุดเครื่องยนต์ในสุญญากาศ'), false,
        T('An engine loses efficiency with no air to push against.', 'Без воздуха, от которого можно оттолкнуться, двигатель теряет эффективность.', 'เครื่องยนต์ด้อยประสิทธิภาพเมื่อไม่มีอากาศให้ผลักดัน'))],
    T('Of the 9–10 km/s a launcher gives, about 1.5 km/s goes to gravity, 0.1–0.2 km/s to drag and some to steering. Launching east the Earth\'s rotation is a gain (up to 0.46 km/s at the equator), and an engine is most efficient in vacuum.',
      'Из 9–10 км/с, сообщаемых ракетой, около 1,5 км/с уходит на гравитационные потери, 0,1–0,2 км/с — на сопротивление и немного — на управление. При пуске на восток вращение Земли — это выигрыш (до 0,46 км/с на экваторе), а двигатель эффективнее всего в пустоте.',
      'จาก Δv 9–10 กม./วินาที ที่จรวดให้ ประมาณ 1.5 กม./วินาที เสียไปกับแรงโน้มถ่วง 0.1–0.2 กม./วินาทีกับแรงต้านอากาศ และบางส่วนกับการบังคับทิศ การปล่อยไปทางตะวันออกได้ประโยชน์จากการหมุนของโลก (สูงสุด 0.46 กม./วินาทีที่เส้นศูนย์สูตร) และเครื่องยนต์มีประสิทธิภาพสูงสุดในสุญญากาศ'),
    { lessons: ['orbit-payload'] }),
  numeric('r-read-maxq', 3, 1, K, 'aero.qRead',
    T('The chart is the dynamic pressure of a Falcon 9 flown in this simulator. Read the highest dynamic pressure it met (kPa).', 'На графике — скоростной напор Falcon 9 в полёте этого симулятора. Определите наибольший скоростной напор (кПа).', 'กราฟคือความดันพลวัตของ Falcon 9 ที่บินในโปรแกรมนี้ อ่านค่าความดันพลวัตสูงสุดที่จรวดเผชิญ (kPa)'),
    [], String(MAX_Q), 'kPa', 8,
    T('The peak of the curve, max-Q, is where the air is still dense and the speed already high; the rocket\'s structure and its control are sized for it.',
      'Пик кривой, max-Q, — там, где воздух ещё плотный, а скорость уже велика; на него рассчитаны конструкция ракеты и её система управления.',
      'ยอดของเส้นกราฟ คือ max-Q ซึ่งอากาศยังหนาแน่นแต่ความเร็วสูงแล้ว โครงสร้างและระบบควบคุมของจรวดออกแบบมาสำหรับค่านี้'),
    { figure: chart('f9-leo', 'q', undefined, 200), lessons: ['guid-maxq'] }),
  numeric('r-read-meco', 3, 2, K, 'rocket.thrustRead',
    T('The chart is the thrust of a Falcon 9 flown in this simulator. Read the moment the first stage\'s engines cut off (s).', 'На графике — тяга Falcon 9 в полёте этого симулятора. Определите момент выключения двигателей первой ступени (с).', 'กราฟคือแรงขับของ Falcon 9 ที่บินในโปรแกรมนี้ อ่านเวลาที่เครื่องยนต์ขั้นที่หนึ่งดับ (วินาที)'),
    [], String(MECO_T), 's', 4,
    T('The thrust falls to zero at MECO; after the separation the single second-stage engine lights with less than a tenth of it. The first stage\'s thrust grows a little on the way up: the nozzles lose less to the outside air.',
      'Тяга падает до нуля при MECO; после разделения включается единственный двигатель второй ступени с тягой меньше десятой части. Тяга первой ступени немного растёт при подъёме: сопла меньше теряют на противодавлении воздуха.',
      'แรงขับลดลงเป็นศูนย์ที่ MECO หลังแยกขั้น เครื่องยนต์เดียวของขั้นที่สองจุดขึ้นด้วยแรงขับไม่ถึงหนึ่งในสิบ แรงขับของขั้นที่หนึ่งเพิ่มขึ้นเล็กน้อยขณะไต่ระดับ เพราะหัวฉีดสูญเสียน้อยลงจากความดันอากาศภายนอก'),
    { figure: chart('f9-leo', 'thrust', undefined, 260) }),
  multi('r-multi-solid', 3, 2, K, 'rocket.solids',
    T('Which are true of solid rocket motors, compared with liquid engines? Choose every one.', 'Что верно для твердотопливных двигателей по сравнению с жидкостными? Выберите всё.', 'ข้อใดเป็นจริงสำหรับมอเตอร์จรวดเชื้อเพลิงแข็ง เมื่อเทียบกับเครื่องยนต์เชื้อเพลิงเหลว เลือกทุกข้อที่ถูก'),
    [O(T('Once lit, they burn to the end: they cannot be shut down and restarted at will', 'Будучи запущенным, заряд горит до конца: его нельзя выключить и включить повторно по команде', 'เมื่อจุดแล้วจะเผาไหม้จนหมด ปิดและจุดใหม่ตามต้องการไม่ได้'), true),
      O(T('They give a large thrust for their size', 'Дают большую тягу при малых размерах', 'ให้แรงขับสูงเมื่อเทียบกับขนาด'), true),
      O(T('They can be kept loaded and ready for a long time', 'Могут долго храниться снаряжёнными и готовыми к пуску', 'เก็บไว้แบบบรรจุพร้อมใช้ได้เป็นเวลานาน'), true),
      O(T('Their specific impulse is higher than a hydrogen-oxygen engine\'s', 'Их удельный импульс выше, чем у кислородно-водородного двигателя', 'แรงดลจำเพาะสูงกว่าเครื่องยนต์ไฮโดรเจน-ออกซิเจน')),
      O(T('Their thrust is set freely in flight with a valve', 'Их тягу в полёте свободно регулируют клапаном', 'ปรับแรงขับได้อย่างอิสระระหว่างบินด้วยวาล์ว'))],
    T('The thrust of a solid motor follows the shape of its propellant grain, fixed when it is cast; its specific impulse (about 280 s) is well below a liquid engine\'s. It is simple, dense and storable, which is why boosters and missiles use it.',
      'Тяга твердотопливного двигателя задаётся формой заряда, определённой при его изготовлении; удельный импульс (около 280 с) заметно ниже, чем у жидкостного. Он прост, компактен и долго хранится — поэтому его применяют в ускорителях и ракетах военного назначения.',
      'แรงขับของมอเตอร์เชื้อเพลิงแข็งเป็นไปตามรูปทรงของก้อนเชื้อเพลิงที่หล่อไว้ แรงดลจำเพาะ (ประมาณ 280 วินาที) ต่ำกว่าเครื่องยนต์เชื้อเพลิงเหลวอย่างชัดเจน แต่เรียบง่าย กะทัดรัด และเก็บได้นาน จึงใช้เป็นบูสเตอร์และขีปนาวุธ')),
  choice('r-trajectories', 3, 3, U, 'aero.trajectoryShape',
    T('Three ascents to the same 200 km orbit (h height, L range). Which pays the most in drag, and which the most in gravity losses?', 'Три траектории выведения на одну и ту же орбиту 200 км (h — высота, L — дальность). На какой больше всего потери на сопротивление, а на какой — гравитационные?', 'เส้นทางไต่ระดับสามแบบสู่วงโคจร 200 กม. เดียวกัน (h ความสูง L ระยะทาง) แบบใดเสียให้แรงต้านอากาศมากที่สุด และแบบใดเสียให้แรงโน้มถ่วงมากที่สุด'),
    [O(T('C the most drag, A the most gravity', 'C — больше всего на сопротивление, A — гравитационные', 'C เสียให้แรงต้านมากที่สุด A เสียให้แรงโน้มถ่วงมากที่สุด'), true),
      O(T('A the most of both, being the highest', 'A — больше всего и того и другого, раз она самая высокая', 'A เสียมากที่สุดทั้งสองอย่างเพราะสูงที่สุด'), false,
        T('The more a trajectory climbs, the more of every loss it pays.', 'Чем круче траектория, тем больше любые потери.', 'ยิ่งเส้นทางไต่สูงชัน ยิ่งเสียทุกอย่างมาก')),
      O(T('C the most of both, being the longest', 'C — больше всего и того и другого, раз она самая длинная', 'C เสียมากที่สุดทั้งสองอย่างเพราะยาวที่สุด')),
      O(T('The same for all three: they reach the same orbit', 'Одинаковые у всех: орбита ведь одна', 'เท่ากันทั้งสามแบบ เพราะไปถึงวงโคจรเดียวกัน'), false,
        T('The losses depend only on where the flight ends.', 'Потери зависят только от конечной точки полёта.', 'การสูญเสียขึ้นอยู่กับจุดสิ้นสุดของการบินเท่านั้น'))],
    T('The depressed trajectory C stays low, in dense air, at high speed: the most drag and heating. The lofted A climbs steeply and spends longest holding itself up against gravity. The nominal B is the compromise the guidance flies.',
      'Пологая траектория C дольше идёт низко, в плотном воздухе, на большой скорости: наибольшее сопротивление и нагрев. Крутая A быстро набирает высоту и дольше всего «держит» себя против тяготения. Номинальная B — компромисс, по которому летит система наведения.',
      'เส้นทางต่ำ C อยู่ในอากาศหนาแน่นนานด้วยความเร็วสูง จึงเสียให้แรงต้านและความร้อนมากที่สุด เส้นทางสูงชัน A ไต่เร็วและใช้เวลานานที่สุดในการพยุงตัวต้านแรงโน้มถ่วง ส่วนเส้นทางปกติ B คือจุดสมดุลที่ระบบนำวิถีเลือกบิน'),
    { figure: diagram('trajectories') }),
  numeric('r-liftoff-accel', 3, 2, K, 'rocket.twrCalc',
    T('A rocket of {m} t lifts off with {F} kN of thrust. Work out its acceleration just after lift-off (m/s²). Take g0 = 9.81 m/s².', 'Ракета массой {m} т стартует с тягой {F} кН. Определите её ускорение сразу после старта (м/с²). Примите g0 = 9,81 м/с².', 'จรวดมวล {m} ตัน ยกตัวด้วยแรงขับ {F} kN จงหาความเร่งทันทีหลังยกตัว (ม./วินาที²) ใช้ g0 = 9.81 ม./วินาที²'),
    [{ name: 'm', min: 300, max: 550, step: 10 }, { name: 'F', min: 7000, max: 9000, step: 100 }], 'F / m - g0', 'm/s²', 3,
    T('a = F/m − g: the thrust per tonne, less the weight it must first carry. At T/W = 1.3 only 0.3 g is left to accelerate; the rest holds the rocket up, the gravity loss.',
      'a = F/m − g: тяга на тонну массы минус вес, который она сначала должна удержать. При T/W = 1,3 на разгон остаётся лишь 0,3 g; остальное удерживает ракету — это гравитационные потери.',
      'a = F/m − g คือแรงขับต่อมวลหนึ่งตัน ลบด้วยน้ำหนักที่ต้องพยุงก่อน ที่ T/W = 1.3 เหลือความเร่งเพียง 0.3 g ส่วนที่เหลือใช้พยุงจรวด ซึ่งคือการสูญเสียจากแรงโน้มถ่วง')),
  choice('r-hydrogen-first', 3, 3, U, 'rocket.density',
    T('Hydrogen and oxygen give a far higher specific impulse than kerosene, yet most first stages burn kerosene or methane. Why?', 'Водород с кислородом дают гораздо больший удельный импульс, чем керосин, но большинство первых ступеней работает на керосине или метане. Почему?', 'ไฮโดรเจนกับออกซิเจนให้แรงดลจำเพาะสูงกว่าน้ำมันก๊าดมาก แต่ขั้นที่หนึ่งส่วนใหญ่ใช้น้ำมันก๊าดหรือมีเทน เพราะเหตุใด'),
    [O(T('Hydrogen is so light that its tanks are huge and heavy, and its engines give less thrust for their size, which a first stage lifting off needs most', 'Водород настолько лёгок, что баки огромны и тяжелы, а двигатели дают меньшую тягу на свой размер — а первой ступени на старте тяга нужнее всего', 'ไฮโดรเจนเบามากจนถังต้องใหญ่และหนัก และเครื่องยนต์ให้แรงขับต่อขนาดน้อยกว่า ซึ่งขั้นที่หนึ่งตอนยกตัวต้องการแรงขับมากที่สุด'), true),
      O(T('Hydrogen does not burn at sea-level pressure', 'Водород не горит при давлении у поверхности Земли', 'ไฮโดรเจนไม่เผาไหม้ที่ความดันระดับน้ำทะเล'), false,
        T('A hydrogen engine can only work in vacuum.', 'Водородный двигатель может работать только в пустоте.', 'เครื่องยนต์ไฮโดรเจนทำงานได้เฉพาะในสุญญากาศ')),
      O(T('Specific impulse does not matter in the atmosphere', 'В атмосфере удельный импульс не имеет значения', 'ในชั้นบรรยากาศ แรงดลจำเพาะไม่มีความสำคัญ'), false,
        T('Efficiency counts only in space.', 'Эффективность важна только в космосе.', 'ประสิทธิภาพสำคัญเฉพาะในอวกาศ')),
      O(T('Kerosene gives more Δv from the same mass of propellant', 'Керосин даёт большую Δv при той же массе топлива', 'น้ำมันก๊าดให้ Δv มากกว่าที่มวลเชื้อเพลิงเท่ากัน'))],
    T('Liquid hydrogen is 14 times less dense than water: a hydrogen stage is big and its structure heavy. At lift-off what counts is thrust against gravity, which dense propellants give from compact engines; hydrogen pays off in upper stages (Centaur, the Ariane core with solid boosters, the Shuttle with its SRBs).',
      'Жидкий водород в 14 раз менее плотен, чем вода: водородная ступень велика, а её конструкция тяжела. На старте важна тяга против тяготения, которую плотные компоненты дают компактными двигателями; водород окупается на верхних ступенях (Centaur, центральный блок Ariane с твердотопливными ускорителями, «Шаттл» с SRB).',
      'ไฮโดรเจนเหลวมีความหนาแน่นน้อยกว่าน้ำ 14 เท่า ขั้นที่ใช้ไฮโดรเจนจึงใหญ่และโครงสร้างหนัก ตอนยกตัวสิ่งสำคัญคือแรงขับต้านแรงโน้มถ่วง ซึ่งเชื้อเพลิงหนาแน่นให้ได้จากเครื่องยนต์ขนาดกะทัดรัด ไฮโดรเจนคุ้มค่าในขั้นบน (Centaur, ลำตัวหลักของ Ariane ที่มีบูสเตอร์เชื้อเพลิงแข็ง, กระสวยอวกาศกับ SRB)')),
];
