#!/usr/bin/env python3
"""Turn the JPL Horizons tables here (DE441, geocentric, ICRF, km and km/s, hourly TDB)
into src/data/ephemeris-1969.ts, for Apollo 11 (roadmap C01, docs/PHYSICS.md §13.10).

    python3 docs/data/horizons/make-ephemeris.py
"""
import os, re
here = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(os.path.dirname(os.path.dirname(here)))

def rows(name):
    text = open(os.path.join(here, name)).read()
    body = text.split('$$SOE')[1].split('$$EOE')[0]
    out = []
    for line in body.strip().splitlines():
        parts = [p.strip() for p in line.split(',')]
        jd = float(parts[0]); vals = [float(x) for x in parts[2:8]]
        out.append((jd, vals))
    return out

def table(name):
    r = rows(name)
    jd0, step = r[0][0], round((r[1][0] - r[0][0]) * 24, 6)
    flat = []
    for _, v in r:
        flat += [round(v[0], 3), round(v[1], 3), round(v[2], 3), round(v[3], 7), round(v[4], 7), round(v[5], 7)]
    return jd0, step, len(r), flat

out = ['/**',
       ' * The Moon and the Sun, geocentric, from JPL Horizons (DE441), hourly from 1969-07-16 13:00 to',
       ' * 1969-07-24 18:00 TDB: position (km) and velocity (km/s) in the ICRF, six numbers a row.',
       ' * Generated by docs/data/horizons/make-ephemeris.py from the tables beside it; do not edit.',
       ' */']
for key, name in (('MOON', 'moon-1969-07-icrf.txt'), ('SUN', 'sun-1969-07-icrf.txt')):
    jd0, step, n, flat = table(name)
    out.append(f'export const {key}_1969 = {{ jd0: {jd0}, stepHours: {step}, count: {n}, data: [')
    for i in range(0, len(flat), 6):
        out.append('  ' + ', '.join(repr(x) for x in flat[i:i + 6]) + ',')
    out.append('] } as const;')
open(os.path.join(root, 'src', 'data', 'ephemeris-1969.ts'), 'w').write('\n'.join(out) + '\n')
print('written')
